/*
 * Wise World - Données du quiz (Français)
 * ⚠ Traduction par IA depuis l'original japonais. La révision par un locuteur
 *    natif ou un expert en santé est recommandée avant utilisation.
 * Garde id / answerIndex / emoji identiques dans toutes les langues.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).fr = [
  { id:1, topic:"Eau potable", emoji:"💧",
    question:"Quelle eau est sûre et ne te fera pas mal au ventre ?",
    choices:["L'eau de rivière","L'eau de puits","L'eau bien bouillie sur le feu","L'eau de pluie"],
    answerIndex:2,
    explanation:"L'eau de rivière, de puits et de pluie peut paraître parfaitement claire et propre, mais elle peut être pleine de minuscules êtres vivants que nos yeux ne peuvent pas voir (des microbes et des virus). Si tu bois cette eau telle quelle, elle peut provoquer de fortes douleurs au ventre ou une maladie grave qui met la vie en danger. Mais quand tu mets l'eau sur le feu et que tu la fais bouillir fort jusqu'à ce qu'elle fasse des bulles, la chaleur tue tous ces êtres nuisibles. C'est pourquoi l'eau bien bouillie puis refroidie est l'eau la plus sûre du monde, celle que tu peux boire en toute confiance." },
  { id:2, topic:"Se laver les mains", emoji:"🧼",
    question:"Que dois-tu faire avant de manger ?",
    choices:["Te laver les mains à l'eau et au savon","T'essuyer les mains sur tes vêtements","Ne rien faire","Toucher la terre"],
    answerIndex:0,
    explanation:"Nos mains touchent beaucoup d'objets et le sol chaque jour, alors sans le remarquer elles ramassent beaucoup de microbes invisibles. Si tu touches la nourriture avec ces mains, les microbes passent sur la nourriture et tu les avales dans ton corps en même temps. T'essuyer les mains sur des vêtements sales, ou juste les mouiller à l'eau, n'enlève pas les microbes : ils restent accrochés. Ce n'est qu'en utilisant du savon et en frottant les paumes, le dos des mains et entre les doigts avec une bonne mousse, puis en rinçant à l'eau, que tu peux vraiment enlever les microbes." },
  { id:3, topic:"Se laver les mains", emoji:"🚽",
    question:"Que dois-tu faire après être allé aux toilettes ?",
    choices:["Aller jouer tout de suite","Te laver les mains à l'eau et au savon","Te frotter les mains sur tes vêtements","T'essuyer les mains sur ton pantalon"],
    answerIndex:1,
    explanation:"Après être allé aux toilettes, des microbes très puissants, venus des selles et de l'urine et qui causent des maladies, se collent facilement à tes mains. Si tu vas jouer sans te laver, ces microbes passent sur les poignées et les jouets que tu touches, et transmettent la maladie au prochain ami ou membre de la famille qui les touche. Et si tu touches ta bouche ou tes yeux avec ces mains, tu peux aussi tomber malade. Même si tu es très pressé, te laver toujours bien les mains à l'eau et au savon après les toilettes est une règle qui protège ta vie et celle des autres." },
  { id:4, topic:"Santé", emoji:"💧",
    question:"Quand tu as mal au ventre et que tes selles deviennent liquides (la diarrhée), qu'est-ce qui compte le plus ?",
    choices:["Manger beaucoup","Ne rien boire","Boire beaucoup d'eau sûre","Courir et jouer"],
    answerIndex:2,
    explanation:"Quand tu as mal au ventre et que des selles liquides (la diarrhée) sortent encore et encore, ton corps perd sans arrêt de l'eau et des éléments nourrissants précieux. Cela s'appelle la déshydratation. Quand le corps manque d'eau, les fonctions importantes qui nous gardent en vie commencent à s'arrêter, et les petits enfants surtout peuvent perdre la vie soudainement. Quand tu as la diarrhée, plutôt que de te forcer à manger des aliments solides, le mieux est d'abord de remplacer l'eau que tu as perdue. En buvant de l'eau sûre, bouillie puis refroidie, petit à petit et de nombreuses fois, tu peux garder tes forces et protéger ta vie." },
  { id:5, topic:"Soigner les blessures", emoji:"🩹",
    question:"Quand tu tombes et que tu saignes, que dois-tu faire d'abord ?",
    choices:["Mettre de la terre dessus","La laver bien à l'eau propre","La laisser sans rien faire","La frotter avec une feuille"],
    answerIndex:1,
    explanation:"Quand tu tombes et que tu te fais une blessure qui saigne, la plaie est couverte de terre, de boue et de poussière du sol, avec beaucoup de microbes. Si tu crois aux vieilles croyances et que tu y mets de la terre, que tu la frottes avec une feuille sale ou que tu la laisses ainsi, les microbes entrent profondément dans la plaie et se multiplient. Alors la plaie enfle, devient rouge et fait très mal, et au pire un bras ou une jambe peut pourrir et ne plus bouger. Quand tu te blesses, le premier bon geste pour éviter que la plaie devienne grave est d'utiliser de l'eau propre et sûre pour rincer avec force la boue et la saleté de la plaie." },
  { id:6, topic:"Aliments", emoji:"🦠",
    question:"Que se passe-t-il quand la nourriture pourrit (s'abîme) ?",
    choices:["Elle devient délicieuse","Elle pourrit et donne mal au ventre","Elle devient dure","Rien ne change"],
    answerIndex:1,
    explanation:"La nourriture contient naturellement, dès le début, un petit nombre de microbes invisibles. Dans un endroit frais, les microbes ne peuvent pas être actifs, mais si tu laisses la nourriture longtemps dans un endroit chaud, cela devient l'environnement parfait pour eux, et en quelques heures ils se multiplient par millions, un nombre effrayant. Quand les microbes se multiplient autant et que la forme et la nature de la nourriture changent, on dit qu'elle a pourri. La nourriture pourrie renferme le poison puissant fabriqué par les microbes ; la manger provoque donc de fortes douleurs au ventre, de la diarrhée et des nausées, et abîme ton corps." },
  { id:7, topic:"Aliments", emoji:"👃",
    question:"Quel est le signe qu'un aliment est avarié ?",
    choices:["Une odeur ou un goût bizarre","Une couleur rouge","Quelque chose de froid","Quelque chose de bien cuit"],
    answerIndex:0,
    explanation:"Tu peux utiliser ton propre nez et ta langue pour vérifier si un aliment est avarié et n'est plus sûr. S'il a une odeur aigre inhabituelle ou une odeur forte et désagréable, ou un goût bizarre quand tu en mets un peu en bouche, ou s'il est gluant et fait des fils, c'est la preuve que les microbes se sont beaucoup multipliés et qu'un poison s'est formé. Si tu te forces à le manger parce que ce serait du gaspillage, tu mets ta vie en danger à cause d'une forte intoxication. Si l'odeur ou le goût sont ne serait-ce qu'un peu suspects, décide de le jeter et ne l'avale jamais." },
  { id:8, topic:"Aliments", emoji:"🪰",
    question:"Que dois-tu faire d'un aliment sur lequel une mouche s'est posée ?",
    choices:["Le manger tel quel","Ne pas manger la partie touchée par la mouche (la jeter)","Élever la mouche","La regarder fixement"],
    answerIndex:1,
    explanation:"L'insecte qu'on appelle mouche aime se promener dans des endroits très sales et pleins de microbes, comme les excréments d'animaux, les cadavres et les décharges. C'est pourquoi des microbes qui causent des maladies terribles se collent à ses fines pattes et à son corps. Quand une telle mouche se pose sur notre nourriture, à cet instant les microbes de ses pattes passent sur la nourriture. Si tu manges l'endroit qu'elle a touché, tu mets indirectement dans ta bouche des microbes d'excréments et d'ordures, ce qui peut causer une grave maladie. Même si cela semble du gaspillage, il est plus sûr de couper et de jeter la partie où la mouche s'est posée." },
  { id:9, topic:"Prévenir les maladies", emoji:"🦟",
    question:"Que se passe-t-il si tu laisses de l'eau stagner longtemps ?",
    choices:["L'eau devient propre","Des moustiques nuisibles se multiplient","Ton argent augmente","Il ne se passe rien"],
    answerIndex:1,
    explanation:"L'eau ancienne qui reste à un seul endroit sans couler devient l'endroit parfait pour que l'insecte appelé moustique ponde ses œufs. Si tu laisses des seaux, de vieux pneus ou des boîtes vides avec de l'eau autour de ta cour ou de ta maison, des centaines et des milliers de nouveaux moustiques y naissent et volent partout. Quand un moustique aspire le sang d'une personne, il lui injecte dans le corps les microbes de maladies très effrayantes et mortelles comme le paludisme et la dengue. Supprimer les flaques d'eau autour de la maison est un plan important pour protéger ta famille de ces terribles maladies." },
  { id:10, topic:"Propreté", emoji:"✋",
    question:"Quand tes ongles sont longs, qu'est-ce qui s'accumule dedans ?",
    choices:["Tes mains deviennent plus fortes","De la saleté noire et des microbes s'accumulent sous les ongles","La nourriture a meilleur goût","Rien ne change"],
    answerIndex:1,
    explanation:"Quand les ongles poussent longs, de la boue et de la saleté noires se tassent dans l'espace étroit entre l'ongle et la peau quand tu joues dans la terre, que tu aides ou que tu travailles. La saleté qui entre dans cet espace ne part pas facilement avec un lavage de mains normal, et devient la cachette parfaite pour les microbes. Avec des ongles longs, quand tu manges avec les mains ou que tu touches ton visage ou une plaie, ces microbes cachés entrent facilement dans ton corps. Garder les ongles toujours courts est un moyen de base pour prévenir les maladies." },
  { id:11, topic:"En toussant", emoji:"🤧",
    question:"Que dois-tu faire quand tu tousses ou éternues ?",
    choices:["Le faire vers le visage de quelqu'un","Couvrir ta bouche et ton nez avec ta main ou ta manche","Crier fort","Ne rien faire"],
    answerIndex:1,
    explanation:"Quand tu as un rhume ou une maladie des poumons, une seule toux ou un seul éternuement projette de minuscules gouttelettes d'eau invisibles depuis ta bouche et ton nez, à plusieurs mètres et avec force. Chaque gouttelette peut contenir des dizaines de milliers de microbes de maladie. Si tu tousses vers le visage de quelqu'un, tu le contamines directement, et si tu ne couvres rien, les microbes se répandent dans l'air et tout le monde dans la même pièce peut tomber malade. Quand tu tousses, bien couvrir ta bouche et ton nez avec ta manche ou ta main t'évite de transmettre la maladie à ta famille et à tes amis qui te sont chers." },
  { id:12, topic:"Propreté", emoji:"🗑️",
    question:"Que se passe-t-il si tu laisses des ordures près de la maison ?",
    choices:["La maison devient propre","Des rats et des insectes nuisibles s'attroupent et la maladie se propage","Les ordures deviennent des fleurs","Rien de grave"],
    answerIndex:1,
    explanation:"Si tu jettes des restes de nourriture et des ordures juste à côté de ta maison, l'odeur attire beaucoup d'êtres comme les rats, les mouches et les cafards. Ces êtres se promènent souvent dans les égouts et les endroits sales, alors ils portent sur le corps beaucoup de microbes qui causent des maladies effrayantes. En se multipliant autour des ordures, ils finissent par entrer dans la maison et salissent la nourriture et l'eau à boire qui s'y trouvent. Les ordures doivent être jetées à un endroit fixe assez loin de la maison, ou enterrées profondément dans un trou." },
  { id:13, topic:"Dents saines", emoji:"🪥",
    question:"Quelle est la raison principale de se brosser les dents ?",
    choices:["Peindre les dents en blanc","Réduire les microbes de caries dans la bouche et protéger les dents","Rendre la mâchoire plus forte","Se remplir l'estomac"],
    answerIndex:1,
    explanation:"Après avoir mangé, de petits restes de nourriture demeurent toujours dans les creux et à la surface des dents. Les êtres invisibles appelés microbes de caries qui vivent dans notre bouche adorent ces restes. Si tu les laisses là, les microbes de caries s'en nourrissent et fabriquent un acide puissant qui dissout les dents. À cause de cet acide, des trous s'ouvrent peu à peu dans les dents, qui devraient être la partie la plus dure du corps, et quand cela atteint le nerf, cela provoque une douleur si vive que tu ne peux pas dormir la nuit. Se brosser les dents après manger est un travail tout à fait nécessaire pour enlever la nourriture des microbes et protéger tes dents." },
  { id:14, topic:"Prévenir les blessures", emoji:"👟",
    question:"Pourquoi portes-tu des chaussures quand tu marches dehors ?",
    choices:["Pour que tes pieds grandissent","Pour empêcher les vers et les microbes du sol d'entrer par la peau de tes pieds","Pour t'entraîner à courir","Pour ne pas salir tes vêtements"],
    answerIndex:1,
    explanation:"Quand tu marches pieds nus sur la terre et la boue, de minuscules êtres cachés dans le sol, trop petits pour être vus (les larves de parasites), et des microbes peuvent percer la peau tendre de la plante de tes pieds et entrer d'eux-mêmes dans ton corps. Les vers qui entrent s'installent dans ton ventre (les intestins) et volent les éléments nourrissants que tu manges, te rendant très anémique, arrêtant ta croissance et te vidant de ton énergie. Porter des chaussures te protège aussi des blessures graves dues au fait de marcher sur du verre cassé, des pierres pointues ou des épines. Porte toujours des chaussures ou des sandales quand tu sors." },
  { id:15, topic:"Propreté", emoji:"👕",
    question:"Que se passe-t-il si tu continues à porter des vêtements sales ?",
    choices:["Les vêtements deviennent plus solides","Ta peau démange ou tu tombes malade","Ton corps devient plus fort","Rien ne change"],
    answerIndex:1,
    explanation:"Si tu continues à porter des vêtements trempés de sueur ou tachés de boue pendant plusieurs jours, les moisissures et les microbes se nourrissent de la sueur et du gras de la peau présents sur les vêtements et se multiplient énormément dans les fibres. Comme ces vêtements sales frottent ta peau tout le temps, la peau peut enfler et rougir, beaucoup démanger, ou développer une maladie avec des plaies qui suintent. Les vêtements sales peuvent être débarrassés des microbes en les lavant bien à l'eau et au savon et en les séchant bien au soleil (les rayons ultraviolets). Porter toujours des vêtements propres est important pour protéger la barrière de ta peau." },
  { id:16, topic:"Propreté", emoji:"🚿",
    question:"Qu'y a-t-il de bien à se laver le corps ?",
    choices:["La peau devient propre et tu préviens les maladies de peau","Tu grandis","Tes cheveux tombent","Tu as faim"],
    answerIndex:0,
    explanation:"Chaque jour, du gras invisible (le sébum) et de la sueur sortent de la peau humaine, et la poussière et la terre du dehors s'y mêlent, salissant tout le corps. Si tu laisses cette saleté plusieurs jours, les mauvais microbes se multiplient à la surface de la peau, et tu peux avoir de terribles furoncles ou une maladie effrayante où la peau s'ulcère et pourrit. En lavant régulièrement tout ton corps en douceur, à l'eau et au savon, et en enlevant le vieux gras et la saleté, ta peau reste saine et forte, formant une barrière puissante qui empêche la maladie d'entrer depuis l'extérieur." },
  { id:17, topic:"Eau potable", emoji:"💧",
    question:"Quand tu n'as que de l'eau boueuse, comment la boire en sécurité ?",
    choices:["La boire telle quelle","Filtrer la boue avec un tissu ou du sable, puis la faire bouillir sur le feu","La laisser juste au soleil et la boire","En boire seulement un peu"],
    answerIndex:1,
    explanation:"Quand tout ce que tu peux trouver est de l'eau boueuse, la boire telle quelle met dans ton corps une énorme quantité de microbes avec la boue et cause une grave maladie. La rendre sûre demande deux savoirs. D'abord, fais passer l'eau à travers un tissu propre et fin, ou un récipient rempli de sable et de petits cailloux, pour filtrer la boue et les gros morceaux et rendre l'eau claire. Mais être claire ne suffit pas : les microbes invisibles sont toujours vivants. Ensuite, tu dois la mettre sur le feu et la faire bouillir fort jusqu'à ce qu'elle fasse des bulles, pour que la chaleur élimine les microbes et qu'elle devienne enfin une eau sûre à boire. Avec de la sagesse, tu peux faire une eau qui sauve la vie même à partir d'eau boueuse." },
  { id:18, topic:"Bébés", emoji:"🍼",
    question:"Quel est le meilleur aliment pour un bébé ?",
    choices:["Le lait de vache (cru)","Le lait de la mère (le lait maternel)","L'eau de rivière","L'eau sucrée"],
    answerIndex:1,
    explanation:"Le corps d'un nouveau-né est très faible et n'a presque pas de force pour vaincre les microbes des maladies. Le lait de la mère (le lait maternel) contient non seulement l'aliment parfait pour que le bébé grandisse, mais aussi de grandes quantités d'un élément protecteur spécial appelé immunité, qui le défend contre les maladies. De plus, le lait maternel sort directement du corps, alors il ne touche jamais d'eau sale du dehors ni de microbes des récipients : c'est le plus propre et le plus sûr du monde. Le lait cru d'autres animaux, l'eau de rivière ou l'eau sucrée peuvent abîmer l'estomac et l'intestin fragiles du bébé et lui ôter la vie, alors tu ne dois jamais les lui donner." },
  { id:19, topic:"Prévenir les maladies", emoji:"😷",
    question:"Que dois-tu faire près de quelqu'un qui tousse fort ?",
    choices:["Garder un peu de distance et détourner le visage en passant","Respirer un grand coup devant cette personne","Lui serrer la main","Te tenir juste devant elle"],
    answerIndex:0,
    explanation:"Les maladies respiratoires graves comme la tuberculose flottent longtemps dans l'air, portées par les minuscules gouttelettes invisibles qui se dispersent quand une personne malade tousse. Si tu respires un grand coup tout près, ou si tu restes près longtemps, tu inspires ces microbes au fond de tes poumons et tu peux attraper la même maladie grave. Quand quelqu'un tousse fort, il ne s'agit pas d'être méchant ni de le traiter différemment ; pour te protéger, garde plusieurs mètres de distance, et en passant, détourne le visage et expire doucement : c'est ainsi que vous vous protégez tous les deux." },
  { id:20, topic:"Air frais", emoji:"🪟",
    question:"Comment garder l'air d'une pièce propre ?",
    choices:["Fermer hermétiquement toutes les portes et fenêtres","Ouvrir les fenêtres et les portes pour renouveler l'air","Que tout le monde crie fort ensemble","Rien ne change"],
    answerIndex:1,
    explanation:"Quand beaucoup de gens se rassemblent dans une petite pièce fermée, les microbes et les virus que quelqu'un porte s'accumulent de plus en plus dans l'air, jusqu'à ce que l'air de la pièce soit plein de microbes. Si tu restes longtemps dans cette pièce, tout le monde respire l'air sale et tombe malade ensemble (une contamination de groupe). En ouvrant les fenêtres et les portes à deux endroits ou plus pour échanger l'air frais du dehors avec l'air sale de la pièce (aérer), tu peux chasser les microbes hors de l'air et protéger la santé de tous ceux qui sont dans la pièce." }
];
