/*
 * Wise World - Dados do quiz (Português)
 * ⚠ Tradução por IA a partir do original em japonês. Recomenda-se a revisão
 *    por um falante nativo ou especialista em saúde antes de usar.
 * Mantenha id / answerIndex / emoji iguais em todos os idiomas.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).pt = [
  { id:1, topic:"Água segura", emoji:"💧",
    question:"Qual água é segura e não vai te dar dor de barriga?",
    choices:["Água de rio","Água de poço","Água bem fervida no fogo","Água da chuva"],
    answerIndex:2,
    explanation:"A água de rio, de poço e da chuva pode parecer perfeitamente clara e limpa, mas pode estar cheia de seres vivos minúsculos que nossos olhos não conseguem ver (germes e vírus). Se você beber essa água do jeito que está, ela pode causar uma forte dor de estômago ou uma doença grave que põe a vida em risco. Mas quando você põe a água no fogo e a ferve bem até borbulhar, o calor mata todos esses seres nocivos. Por isso, a água que foi bem fervida e depois deixada esfriar é a mais segura do mundo, e a que você pode beber com confiança." },
  { id:2, topic:"Lavar as mãos", emoji:"🧼",
    question:"O que você deve fazer antes de comer?",
    choices:["Lavar as mãos com água e sabão","Limpar as mãos na roupa","Não fazer nada","Tocar na terra"],
    answerIndex:0,
    explanation:"Nossas mãos tocam muitos objetos e o chão todos os dias, então sem perceber elas pegam muitos germes invisíveis. Se você tocar a comida com essas mãos, os germes passam para a comida e você os engole para dentro do corpo junto com ela. Limpar as mãos em roupa suja, ou só molhá-las com água, não tira os germes: eles ficam grudados. Só usando sabão e esfregando as palmas, o dorso das mãos e entre os dedos com bastante espuma, e depois enxaguando com água, é que você consegue de fato eliminar os germes." },
  { id:3, topic:"Lavar as mãos", emoji:"🚽",
    question:"O que você deve fazer depois de usar o banheiro?",
    choices:["Ir brincar na hora","Lavar as mãos com água e sabão","Esfregar as mãos na roupa","Secar as mãos na calça"],
    answerIndex:1,
    explanation:"Depois de usar o banheiro, germes muito fortes das fezes e da urina, que causam doenças, grudam facilmente nas suas mãos. Se você for brincar sem lavar, esses germes passam para as maçanetas e brinquedos que você toca, e transmitem a doença ao próximo amigo ou familiar que os tocar. E se você tocar a própria boca ou os olhos com essas mãos, também pode ficar doente. Por mais pressa que você tenha, lavar sempre bem as mãos com água e sabão depois do banheiro é uma regra que protege a sua vida e a de quem está ao seu redor." },
  { id:4, topic:"Saúde", emoji:"💧",
    question:"Quando você está de barriga ruim e as fezes ficam aguadas (diarreia), o que é mais importante?",
    choices:["Comer bastante","Não beber nada","Beber bastante água segura","Correr e brincar"],
    answerIndex:2,
    explanation:"Quando você está de barriga ruim e fezes aguadas (diarreia) saem várias vezes, o seu corpo perde água e nutrientes valiosos sem parar. Isso se chama desidratação. Quando falta água no corpo, as funções importantes que nos mantêm vivos começam a parar, e as crianças pequenas, principalmente, podem perder a vida de repente. Quando você está com diarreia, em vez de se forçar a comer alimentos sólidos, o melhor é primeiro repor a água que perdeu. Bebendo água segura, fervida e esfriada, aos poucos e muitas vezes, você consegue manter as forças e proteger a sua vida." },
  { id:5, topic:"Cuidar de ferimentos", emoji:"🩹",
    question:"Quando você cai e sangra, o que deve fazer primeiro?",
    choices:["Pôr terra","Lavar bem com água limpa","Deixar sem fazer nada","Esfregar com uma folha"],
    answerIndex:1,
    explanation:"Quando você cai e faz um ferimento que sangra, a ferida fica coberta de terra, lama e poeira do chão, junto com muitos germes. Se você acreditar em ditados antigos e passar terra, esfregar com uma folha suja ou deixar assim, os germes entram fundo na ferida e se multiplicam. Aí a ferida incha, fica vermelha e dói muito, e no pior caso um braço ou uma perna pode apodrecer e parar de se mexer. Quando você se machuca, o primeiro passo certo para a ferida não ficar grave é usar água limpa e segura para lavar com força a lama e a sujeira da ferida." },
  { id:6, topic:"Alimentos", emoji:"🦠",
    question:"O que acontece quando a comida estraga (apodrece)?",
    choices:["Fica gostosa","Apodrece e dá dor de barriga","Fica dura","Não muda nada"],
    answerIndex:1,
    explanation:"A comida contém naturalmente, desde o começo, uma pequena quantidade de micróbios invisíveis. Num lugar fresco os micróbios não conseguem agir, mas se você deixar a comida muito tempo num lugar quente, vira o ambiente perfeito para eles, e em poucas horas eles se multiplicam aos milhões, um número assustador. Quando os micróbios se multiplicam tanto e a forma e a natureza da comida mudam, dizemos que ela estragou. A comida estragada guarda o veneno forte que os micróbios produziram, então comê-la causa forte dor de estômago, diarreia e enjoo, e faz mal ao seu corpo." },
  { id:7, topic:"Alimentos", emoji:"👃",
    question:"Qual é um sinal de que a comida estragou?",
    choices:["Um cheiro ou gosto estranho","Uma cor vermelha","Algo frio","Algo bem cozido"],
    answerIndex:0,
    explanation:"Você pode usar o próprio nariz e a língua para checar se a comida estragou e não está mais segura. Se ela tiver um cheiro azedo estranho ou um cheiro forte e ruim, ou um gosto esquisito quando você prova um pouco, ou se estiver grudenta e fizer fios, isso é prova de que os germes se multiplicaram muito e que se formou veneno. Se você se forçar a comer porque seria desperdício, coloca a sua vida em risco por uma forte intoxicação. Se o cheiro ou o gosto estiverem, mesmo que um pouco, suspeitos, decida jogar fora e nunca engula." },
  { id:8, topic:"Alimentos", emoji:"🪰",
    question:"O que fazer com a comida em que uma mosca pousou?",
    choices:["Comer do jeito que está","Não comer a parte que a mosca tocou (jogar fora)","Criar a mosca","Ficar olhando"],
    answerIndex:1,
    explanation:"O inseto que chamamos de mosca gosta de andar por lugares muito sujos e cheios de germes, como fezes de animais, carcaças e lixões. Por isso, germes que causam doenças terríveis grudam nas suas patinhas finas e no corpo. Quando uma mosca dessas pousa na nossa comida, naquele instante os germes das patas passam para a comida. Se você comer o lugar que ela tocou, está colocando na boca, de forma indireta, germes de fezes e lixo, o que pode causar uma doença grave. Mesmo que pareça desperdício, é mais seguro cortar e jogar fora a parte onde a mosca pousou." },
  { id:9, topic:"Prevenir doenças", emoji:"🦟",
    question:"O que acontece se você deixar água parada por muito tempo?",
    choices:["A água fica limpa","Mosquitos nocivos se multiplicam","Seu dinheiro aumenta","Não acontece nada"],
    answerIndex:1,
    explanation:"A água velha que fica parada num só lugar sem correr vira o lugar perfeito para o inseto chamado mosquito pôr os ovos. Se você deixar baldes, pneus velhos ou latas vazias com água ao redor do quintal ou da casa, ali nascem centenas e milhares de mosquitos novos que voam por toda parte. Quando um mosquito chupa o sangue de uma pessoa, injeta no corpo os germes de doenças muito assustadoras e mortais, como a malária e a dengue. Acabar com as poças de água ao redor da casa é um plano importante para proteger a sua família dessas doenças terríveis." },
  { id:10, topic:"Limpeza", emoji:"✋",
    question:"Quando as unhas estão compridas, o que se acumula dentro?",
    choices:["As mãos ficam mais fortes","Sujeira preta e germes se juntam embaixo das unhas","A comida fica mais gostosa","Não muda nada"],
    answerIndex:1,
    explanation:"Quando as unhas crescem compridas, lama e sujeira pretas entram bem apertadas no espaço estreito entre a unha e a pele enquanto você brinca na terra, ajuda ou trabalha. A sujeira que entra nesse espaço não sai fácil só com uma lavagem normal de mãos, e vira o esconderijo perfeito para os germes. Com as unhas compridas, quando você come com as mãos ou toca o próprio rosto ou uma ferida, esses germes escondidos entram fácil no seu corpo. Manter as unhas sempre curtas é um jeito básico de prevenir doenças." },
  { id:11, topic:"Ao tossir", emoji:"🤧",
    question:"O que você deve fazer quando tosse ou espirra?",
    choices:["Fazer na direção do rosto de alguém","Cobrir a boca e o nariz com a mão ou a manga","Gritar alto","Não fazer nada"],
    answerIndex:1,
    explanation:"Quando você está resfriado ou com uma doença no pulmão, uma única tosse ou espirro lança gotinhas de água invisíveis da boca e do nariz, a vários metros e com força. Cada gotinha pode conter dezenas de milhares de germes de doença. Se você tossir na direção do rosto de alguém, transmite a doença direto, e se não cobrir nada, os germes se espalham pelo ar e todos na mesma sala podem ficar doentes. Quando você tosse, cobrir bem a boca e o nariz com a manga ou a mão evita que você espalhe a doença para a família e os amigos queridos ao seu redor." },
  { id:12, topic:"Limpeza", emoji:"🗑️",
    question:"O que acontece se você deixar lixo jogado perto de casa?",
    choices:["A casa fica limpa","Ratos e insetos nocivos se juntam e a doença se espalha","O lixo vira flores","Não tem problema nenhum"],
    answerIndex:1,
    explanation:"Se você jogar restos de comida e lixo bem ao lado de casa, o cheiro atrai muitos seres como ratos, moscas e baratas. Esses seres costumam andar por esgotos e lugares sujos, então carregam no corpo muitos germes que causam doenças assustadoras. Ao aumentar ao redor do lixo, eles acabam entrando em casa e sujam a comida e a água de beber que estão lá dentro. O lixo deve ser jogado num lugar certo, bem longe de casa, ou enterrado fundo num buraco na terra." },
  { id:13, topic:"Dentes saudáveis", emoji:"🪥",
    question:"Qual é o principal motivo de escovar os dentes?",
    choices:["Pintar os dentes de branco","Reduzir os germes da cárie na boca e proteger os dentes","Deixar o queixo mais forte","Encher o estômago"],
    answerIndex:1,
    explanation:"Depois de comer, sempre ficam pequenos restos de comida nos vãos e na superfície dos dentes. Os seres invisíveis chamados germes da cárie, que vivem na nossa boca, adoram esses restos. Se você deixá-los ali, os germes da cárie se alimentam deles e produzem um ácido forte que dissolve os dentes. Por causa desse ácido, aos poucos abrem-se buracos nos dentes, que deveriam ser a parte mais dura do corpo, e quando chega ao nervo dá uma dor tão forte que você não consegue dormir à noite. Escovar os dentes depois de comer é um trabalho totalmente necessário para tirar o alimento dos germes e proteger os seus dentes." },
  { id:14, topic:"Prevenir ferimentos", emoji:"👟",
    question:"Por que você usa calçados ao andar na rua?",
    choices:["Para os pés crescerem","Para impedir que vermes e germes da terra entrem pela pele dos pés","Para treinar corrida","Para não sujar a roupa"],
    answerIndex:1,
    explanation:"Quando você anda descalço na terra e na lama, seres minúsculos escondidos no chão, pequenos demais para ver (as larvas de parasitas), e germes podem atravessar a pele macia da sola dos pés e entrar sozinhos no seu corpo. Os vermes que entram se instalam na sua barriga (os intestinos) e roubam os nutrientes que você come, deixando você muito anêmico, parando o seu crescimento e tirando a sua energia. Usar calçados também protege você de ferimentos graves por pisar em cacos de vidro, pedras pontudas ou espinhos. Use sempre sapatos ou sandálias quando sair." },
  { id:15, topic:"Limpeza", emoji:"👕",
    question:"O que acontece se você continuar usando roupa suja?",
    choices:["A roupa fica mais resistente","A pele coça ou você fica doente","O corpo fica mais forte","Não muda nada"],
    answerIndex:1,
    explanation:"Se você continuar usando roupa encharcada de suor ou suja de lama por muitos dias, mofo e germes se alimentam do suor e da oleosidade da pele que ficam na roupa e se multiplicam muito dentro das fibras. Como essa roupa suja fica roçando na sua pele o tempo todo, a pele pode inchar e ficar vermelha, coçar muito, ou desenvolver uma doença com feridas que soltam pus. A roupa suja pode ficar livre de germes lavando bem com água e sabão e secando bem ao sol (os raios ultravioleta). Usar sempre roupa limpa é importante para proteger a barreira da sua pele." },
  { id:16, topic:"Limpeza", emoji:"🚿",
    question:"O que tem de bom em lavar o corpo?",
    choices:["A pele fica limpa e você previne doenças de pele","Você cresce","Seu cabelo cai","Você fica com fome"],
    answerIndex:0,
    explanation:"Todos os dias saem da pele humana oleosidade invisível (o sebo) e suor, e a poeira e a terra de fora se misturam, sujando o corpo todo. Se você deixar essa sujeira por muitos dias, os germes ruins se multiplicam na superfície da pele, e você pode ter furúnculos terríveis ou uma doença assustadora em que a pele fica em carne viva e apodrece. Lavando regularmente o corpo todo com cuidado, com água e sabão, e tirando a oleosidade e a sujeira velhas, a sua pele fica saudável e forte, formando uma barreira poderosa que impede a doença de entrar de fora." },
  { id:17, topic:"Água segura", emoji:"💧",
    question:"Quando só tem água barrenta, como bebê-la com segurança?",
    choices:["Beber do jeito que está","Filtrar a lama com pano ou areia e depois ferver no fogo","Só deixar no sol e beber","Beber só um pouco"],
    answerIndex:1,
    explanation:"Quando tudo o que você consegue é água barrenta, beber do jeito que está coloca no seu corpo uma enorme quantidade de germes junto com a lama e causa uma doença grave. Para deixá-la segura são precisos dois saberes. Primeiro, passe a água por um pano limpo e fino, ou por um recipiente cheio de areia e pedrinhas, para filtrar a lama e os pedaços grandes e deixar a água clara. Mas ficar clara não basta: os germes invisíveis continuam vivos. Depois, você precisa pôr no fogo e ferver bem até borbulhar, para que o calor elimine os germes e ela enfim vire água segura para beber. Com sabedoria, você pode fazer água que salva vidas até de água barrenta." },
  { id:18, topic:"Bebês", emoji:"🍼",
    question:"Qual é o melhor alimento para um bebê?",
    choices:["Leite de vaca (cru)","O leite da mãe (leite materno)","Água de rio","Água com açúcar"],
    answerIndex:1,
    explanation:"O corpo de um bebê recém-nascido é muito fraco e quase não tem força para vencer os germes das doenças. O leite da mãe (leite materno) não só contém o alimento perfeito para o bebê crescer, mas também grandes quantidades de um componente protetor especial chamado imunidade, que o defende das doenças. Além disso, o leite materno sai direto do corpo, então nunca toca água suja de fora nem germes de recipientes: é o mais limpo e seguro do mundo. O leite cru de outros animais, a água de rio ou a água com açúcar podem arruinar o estômago e o intestino delicados do bebê e tirar a vida dele, por isso você nunca deve dá-los." },
  { id:19, topic:"Prevenir doenças", emoji:"😷",
    question:"O que fazer perto de alguém com tosse forte?",
    choices:["Manter um pouco de distância e virar o rosto ao passar","Respirar fundo na frente da pessoa","Apertar a mão dela","Ficar bem na frente dela"],
    answerIndex:0,
    explanation:"Doenças respiratórias graves como a tuberculose ficam muito tempo no ar, levadas pelas gotinhas minúsculas e invisíveis que se espalham quando uma pessoa doente tosse. Se você respirar fundo por perto, ou ficar perto por muito tempo, leva esses germes para o fundo dos seus pulmões e pode pegar a mesma doença grave. Quando alguém tosse forte, não se trata de ser malvado nem de tratar a pessoa de forma diferente; para se proteger, mantenha vários metros de distância e, ao passar, vire o rosto e expire devagar: é assim que os dois se protegem." },
  { id:20, topic:"Ar fresco", emoji:"🪟",
    question:"Como manter o ar de um cômodo limpo?",
    choices:["Fechar bem todas as portas e janelas","Abrir janelas e portas para trocar o ar","Todos gritarem alto juntos","Não muda nada"],
    answerIndex:1,
    explanation:"Quando muita gente se junta num cômodo pequeno e fechado, os germes e vírus que alguém carrega vão se acumulando cada vez mais no ar, até o ar do cômodo ficar cheio de germes. Se você ficar muito tempo nesse cômodo, todos respiram o ar sujo e ficam doentes juntos (um contágio em grupo). Abrindo janelas e portas em dois ou mais lugares para trocar o ar fresco de fora pelo ar sujo do cômodo (ventilar), você consegue expulsar os germes do ar e proteger a saúde de todos que estão ali." },
  { id:21, topic:"Alavancas", emoji:"🪨",
    question:"Quando você quer mover uma pedra pesada enterrada no chão usando uma alavanca comprida, onde deve empurrar com mais força para movê-la com o menor esforço?",
    choices:["No ponto bem ao lado da pedra","No meio da alavanca","Na ponta mais distante da alavanca, longe da pedra","É igual onde quer que você empurre"],
    answerIndex:2,
    explanation:"Quando você move algo pesado com uma alavanca, existe uma regra chamada princípio da alavanca: quanto mais longe você estiver da pequena pedra que serve de apoio (o ponto de apoio), menos força precisa para empurrar. Se empurrar perto da pedra, a alavanca não se mexe, mas se segurar a ponta mais distante da alavanca e empurrar pondo o seu peso, consegue levantar uma pedra pesada com uma força surpreendentemente pequena. Conhecer como uma ferramenta funciona assim permite multiplicar muitas vezes a sua própria força e realizar trabalhos pesados com facilidade." },
  { id:22, topic:"Alavancas", emoji:"⚖️",
    question:"Quando você levanta uma carga pesada com uma alavanca comprida, onde deve colocar a pequena pedra (o ponto de apoio) que sustenta a alavanca para que ela levante mais facilmente?",
    choices:["Bem ao lado da carga pesada","Bem ao lado de onde você aplica a força","Exatamente no meio da alavanca","É melhor não colocar nenhuma pedra"],
    answerIndex:0,
    explanation:"Quando você levanta algo pesado com uma alavanca, a posição da pequena pedra de apoio (o ponto de apoio) é muito importante. Ao colocar esse apoio bem ao lado da carga pesada, a carga se move apenas uma curta distância, mas a força que você precisa para levantá-la fica muito menor. Ao contrário, se a pedra de apoio estiver perto de você, por mais que empurre não vai conseguir levantar a carga. Quando quiser mover algo pesado, lembre-se da sabedoria de colocar o apoio perto da coisa que quer mover." },
  { id:23, topic:"Rolar", emoji:"🪵",
    question:"Quando você move uma caixa de madeira pesada arrastando-a pelo chão, como pode movê-la mais facilmente com o menor esforço?",
    choices:["Pôr vários toros redondos e duros embaixo da caixa e fazê-la rolar","Puxar com toda a força do jeito que está","Jogar água em cima da caixa","Bater a caixa com força no chão"],
    answerIndex:0,
    explanation:"Quando você arrasta algo pesado direto pelo chão, age com força um freio chamado atrito, criado onde o objeto raspa contra o chão, então mover exige muitíssima força. Mas se você puser toros redondos e duros embaixo da caixa, o movimento deixa de ser arrastar e passa a ser os toros rolando. Rolar tem dezenas de vezes menos força de freio do que arrastar, então até uma só pessoa consegue mover uma carga pesada com facilidade. Quando a carga avança, você pega os toros que saíram atrás e os põe de novo na frente, uma sabedoria que a humanidade usa desde a Antiguidade." },
  { id:24, topic:"Rampas", emoji:"🛝",
    question:"Quando você quer pôr uma carga pesada sobre uma plataforma alta, da altura do peito de um adulto, qual é o jeito de movê-la que menos sobrecarrega o seu corpo?",
    choices:["Ficar na frente da plataforma e levantá-la reto para cima com toda a força","Apoiar uma tábua comprida inclinada contra a plataforma para fazer uma rampa e empurrá-la para cima","Arremessar a carga contra a plataforma de longe","Rebaixar a altura da plataforma para deixá-la mais baixa"],
    answerIndex:1,
    explanation:"Se você tenta levantar uma carga pesada reto para cima, enfrenta de frente a força que puxa as coisas para a terra (a gravidade), então tem de sustentar tudo só com os músculos, o que machuca as costas e os braços. Aqui, se você apoia uma tábua comprida inclinada contra a plataforma para fazer uma rampa (um plano inclinado), a tábua passa a sustentar a maior parte do peso da carga. Ao subir uma rampa, a distância que você caminha aumenta, mas a força necessária para empurrar a carga pode ser reduzida a menos da metade. Quando levar coisas para um lugar alto, procure sempre um jeito de fazer uma rampa." },
  { id:25, topic:"Roldanas", emoji:"🪣",
    question:"Quando você puxa com uma corda um balde pesado cheio de água de um poço fundo, o que fica mais fácil se você instalar na barra acima do poço uma roda redonda que gira (uma roldana) e passar a corda por ela?",
    choices:["O peso da água fica pela metade, mais leve","A quantidade de água aumenta sozinha","Você consegue erguer a água só puxando a corda para baixo","A corda nunca vai arrebentar"],
    answerIndex:2,
    explanation:"Quando você passa uma corda pela roda redonda acima do poço (uma roldana fixa), na verdade o peso da água não fica mais leve. Mas o que há de maravilhoso nessa ferramenta é que ela muda a direção em que você aplica a força. Se você tenta erguer a corda reto para cima, tem de levantá-la só com a força dos braços e das costas; mas se passa a corda pela roda redonda e puxa para baixo, consegue pôr todo o peso do seu corpo sobre a corda. Poder usar o próprio peso para puxar água pesada com facilidade e segurança é a sabedoria dessa roda redonda." },
  { id:26, topic:"Sarilho e eixo", emoji:"🔄",
    question:"Quando você quer girar um parafuso que não gira de jeito nenhum, ou o pesado sarilho de um poço, como pode girá-lo mais facilmente?",
    choices:["Girá-lo usando uma haste curta e fina","Tornar a parte da manivela grande e comprida, e girar essa","Girá-lo só com as pontas dos dedos, sem ferramenta","Bater com força no parafuso com um martelo"],
    answerIndex:1,
    explanation:"Quando você quer girar um eixo que está no centro, se instalar nele uma manivela redonda grande ou um cabo comprido, consegue criar uma grande força de giro com pouco esforço. Isso se chama princípio da roda e eixo. Você não consegue mexer a parte fina girando-a direto com os dedos, mas ao girar a manivela grande de fora, a distância que a sua mão percorre aumenta, enquanto a força sobre o eixo fica muitas vezes maior. A máquina que enrola a corda de um poço, a maçaneta de uma porta em casa, os parafusos das ferramentas; tudo o que gira ao seu redor usa essa sabedoria." },
  { id:27, topic:"Centro de gravidade", emoji:"🏺",
    question:"Há pessoas que andam com destreza carregando um pote de água pesado ou lenha sobre a cabeça. Por que conseguem andar longas distâncias sem machucar o pescoço nem as costas?",
    choices:["Porque andam dobrando muito o corpo para a frente ou para trás","Porque mantêm as costas perfeitamente retas e põem o centro da carga (o seu centro de gravidade) bem acima dos ossos","Porque ficam sacudindo a carga com força sobre a cabeça o tempo todo","Porque todos nascem com os ossos do pescoço mais grossos que os demais"],
    answerIndex:1,
    explanation:"Quando você carrega uma carga pesada nas mãos, o esforço recai só de um lado do corpo e os músculos cansam rápido. Mas se você endireita perfeitamente as costas e põe a carga bem acima da cabeça, o peso do centro da carga (o seu centro de gravidade) desce reto pelo pilar de ossos, da cabeça ao pescoço e à coluna, e sai para o chão. Como são os ossos firmes, e não os músculos, que sustentam o peso, você consegue carregá-la com segurança por longas distâncias sem gastar força muscular, desde que mantenha o equilíbrio. Manter as coisas perto do eixo central do corpo é uma sabedoria importante para não se machucar." },
  { id:28, topic:"Pressão", emoji:"🦶",
    question:"Quando você anda por uma estrada enlameada onde, depois da chuva, vira lama funda e os pés afundam, como pode andar com mais facilidade sem afundar?",
    choices:["Andar na ponta dos pés, deixando a sola dos pés a menor possível","Amarrar à sola dos pés uma tábua de madeira plana e grande, e andar","Simplesmente gritar alto e atravessar correndo","Carregar muita bagagem para ficar mais pesado"],
    answerIndex:1,
    explanation:"O peso que recai sobre o chão se concentra com mais força num ponto e afunda mais fundo, como uma agulha, quanto menor for a superfície que o toca. Isso se chama pressão. Ficar na ponta dos pés deixa a superfície menor, então você afunda ainda mais. Ao contrário, se amarrar à sola dos pés uma tábua de madeira plana e grande, o seu peso se espalha por uma superfície ampla, então a força que empurra o chão para baixo enfraquece e você consegue andar sobre a lama sem afundar. Fazer larga e plana a base de um prédio pesado é a mesma sabedoria para espalhar a pressão." },
  { id:29, topic:"Carroças", emoji:"🛒",
    question:"Quando você quer carregar muita bagagem pesada numa carroça de duas rodas e puxá-la, onde deve pôr as coisas pesadas para que fique o mais leve e fácil de puxar?",
    choices:["Bem ao lado das suas mãos, perto do cabo","Na ponta de trás da carroça","Bem acima do eixo das rodas","É igual onde quer que você carregue"],
    answerIndex:2,
    explanation:"Quando você puxa uma carroça, o peso sobre as suas mãos muda muitíssimo conforme onde você põe a carga. Se puser a bagagem pesada perto das mãos, acaba correndo enquanto levanta o peso da carga direto com os braços, e cansa rápido. Se estiver longe demais, atrás, a carroça tomba para trás, o que é perigoso. A resposta certa é bem acima do eixo das rodas. Se puser as coisas pesadas aqui, as rodas firmes e o chão sustentam todo o peso, então quase nenhum peso recai sobre as suas mãos. Como você só precisa da força de puxar para a frente, consegue transportar uma grande carga com muita facilidade." },
  { id:30, topic:"Gumes", emoji:"🔪",
    question:"Quando você afia o gume de um facão de rachar lenha, ou de uma faca de cozinha de cortar comida, esfregando-o numa pedra (uma pedra de amolar), por que ele corta melhor?",
    choices:["Porque a ponta do gume fica mais fina e delgada, e a força se concentra num só ponto","Porque o gume esquenta e derrete a comida","Porque o gume fica mais pesado","Porque o gume fica arredondado"],
    answerIndex:0,
    explanation:"Que algo seja cortado por um gume acontece porque a força que uma pessoa aplica se concentra no ponto extremamente estreito da ponta do gume e rompe o objeto. Quando um gume envelhece e arredonda, a força se espalha por uma superfície ampla, então por mais que você empurre não corta. Afiar um gume é o trabalho de desbastar a ponta arredondada para deixá-la o mais fina e delgada possível. Uma vez que a ponta fica fina, até uma força pequena cria uma pressão enorme nesse ponto, então você consegue cortar lenha dura ou comida com um toque leve. Cuidar das suas ferramentas é o básico para economizar as suas energias." },
  { id:31, topic:"Atrito", emoji:"👟",
    question:"Quando você anda numa ladeira ou sobre pedras molhadas, o que escorrega menos e é mais seguro: sapatos lisos e escorregadios, ou sapatos com sulcos fundos e cravados na sola?",
    choices:["Sapatos lisos e planos","Sapatos com sulcos fundos e cravados na sola","É igual qualquer um que você use","Escorrega menos sem sapato nenhum"],
    answerIndex:1,
    explanation:"Quando a sola de um sapato raspa contra o chão, age ali um freio chamado atrito que evita que você escorregue. Se a sola é lisa, nenhum freio age entre ela e o chão, e você escorrega e cai com facilidade, sobretudo onde há água ou lama. Se a sola tem sulcos fundos e cravados, esses sulcos se encaixam firmemente nas irregularidades do chão e criam um freio forte. Escorregar e cair pode levar a ferimentos graves, mas conhecendo como o atrito funciona, escolhendo sapatos com sulcos em chão escorregadio ou apoiando toda a sola firmemente no chão, você pode agir com segurança." },
  { id:32, topic:"Flutuar", emoji:"⛵",
    question:"Uma pedrinha afunda na água, e mesmo assim um navio de madeira milhares de vezes mais pesado e maior consegue flutuar na água. Por quê?",
    choices:["Porque o navio tem o formato de uma tigela e guarda muito ar e água dentro","Porque o navio recebe muito vento","Porque há pedras mágicas pintadas no fundo dele","Porque o navio é feito de um óleo mais leve que a água"],
    answerIndex:0,
    explanation:"Sobre um objeto dentro da água age uma força misteriosa chamada empuxo, que o empurra para cima na mesma medida da água que ele desloca. A pedrinha é maciça por dentro e pesada, então a pedra pesa mais que a água que desloca, e afunda. Mas um navio grande tem o formato de uma tigela, e dentro guarda muito ar. Visto no conjunto, fica muito leve para o seu tamanho, então a força da água que empurra de baixo fica mais forte, e até um navio grande consegue flutuar na água sem virar." },
  { id:33, topic:"Triângulos", emoji:"🔺",
    question:"Quando você constrói uma casa ou uma ponte de madeira ou de ferro, por que montar a estrutura em forma de triângulos faz um prédio muito firme e difícil de quebrar?",
    choices:["Porque precisa de mais material que um quadrado","Porque o triângulo tem a propriedade de que a sua forma nunca se deforma, mesmo quando uma força forte é aplicada por cima","Porque fazer triângulos deixa o vento passar mais facilmente","Porque é uma forma antiga usada como amuleto dos deuses"],
    answerIndex:1,
    explanation:"Um prédio feito de pilares montados só em quadrados desaba com facilidade, com as juntas dobrando moles, quando uma força forte ou o tremor de um terremoto é aplicado por cima ou pelo lado. Mas se você acrescenta uma haste inclinada dentro desse quadrado para fazer um triângulo (uma estrutura treliçada), então venha a força da direção que vier, as hastes se puxam e se empurram umas às outras e a forma não se deforma nada. Se você olhar as grandes pontes do mundo, ou a parte de baixo dos telhados dos prédios, esses triângulos sempre estão finamente combinados ali. É uma sabedoria magnífica da construção: mesmo com pouco material, só pensando bem na forma você consegue fazer algo muitas vezes mais firme." },
  { id:34, topic:"Inércia", emoji:"🐎",
    question:"Quando um cavalo ou uma carroça que vai correndo freia de repente e para de vez, o que acontece com a bagagem e as pessoas que estão em cima?",
    choices:["Tombam para trás do jeito que estão","São arremessadas para a frente com força","Pulam reto para cima no mesmo lugar","Nada acontece; param de vez também"],
    answerIndex:1,
    explanation:"No universo existe uma força misteriosa chamada inércia: uma coisa em movimento procura continuar se movendo na mesma velocidade. Mesmo que o cavalo ou a carroça pare de repente, as pessoas e a bagagem em cima ainda procuram continuar avançando. Por isso, se você não firmar bem os pés ou não amarrar a carga com corda, é arremessado para a frente com força e se machuca feio. Quando você para algo em movimento, ou quando anda num veículo veloz, deve ter em mente que essa força que procura lançar as coisas para a frente age sempre, e se preparar para a sua segurança." },
  { id:35, topic:"Tesoura", emoji:"✂️",
    question:"Quando você quer cortar um galho duro ou um tecido grosso com a tesoura, em que parte da lâmina deve prender para cortar mais facilmente com o menor esforço?",
    choices:["Bem na ponta da lâmina","Na base da lâmina (o mais perto do parafuso ou da articulação)","No meio da lâmina","A força necessária é a mesma onde quer que você corte"],
    answerIndex:1,
    explanation:"A tesoura também é uma ferramenta muito prática que usa o princípio da alavanca que viemos aprendendo. O parafuso onde as duas lâminas se cruzam e ficam fixas é o apoio (o ponto de apoio). Quanto mais perto desse parafuso de apoio você cortar, muitas vezes mais forte fica a força que a sua mão que aperta transmite à lâmina. Por isso, com algo duro que não corta, tentar cortar na ponta da tesoura só machuca a sua mão, mas se você prender bem na base da lâmina, consegue cortar de uma tesourada com uma força surpreendentemente pequena. Conheça as características das suas ferramentas e use o ponto mais eficiente." },
  { id:36, topic:"Gravidade", emoji:"🍎",
    question:"Por que, entre deixar cair uma pedrinha sobre o pé da altura do joelho e deixá-la cair do alto do telhado da casa, a que cai do telhado causa um ferimento mais grave?",
    choices:["Porque a pedra fica mais fria lá em cima no telhado","Porque a gravidade, a força que puxa as coisas para a terra, deixa a pedra cada vez mais rápida quanto mais longa a queda, então o impacto na batida é mais forte","Porque uma pedra num lugar alto fica maior de tamanho","Porque o ar empurra a pedra para baixo"],
    answerIndex:1,
    explanation:"Tudo o que está sobre a terra recebe o tempo todo uma força chamada gravidade, que o atrai para o chão. Para algo num lugar alto, quanto mais longa a queda, mais a gravidade continua puxando e mais ele acelera (fica cada vez mais rápido). Um objeto que acelerou cria um enorme poder destrutivo (energia) no instante em que bate no chão ou no seu corpo. Da altura do joelho só dói, mas algo que cai de um telhado alto ou de um penhasco, mesmo uma pedra pequena ou uma ferramenta, vira uma arma capaz de tirar a vida de uma pessoa. Quando trabalhar perto de um lugar alto, deve verificar se não há ninguém embaixo e ter o máximo cuidado para não deixar cair nada." },
  { id:37, topic:"Equilíbrio", emoji:"⚖️",
    question:"Quando você carrega no ombro uma vara comprida (uma vara de carga) com dois potes de água pesados pendurados na frente e atrás, como pode andar com facilidade sem machucar o ombro?",
    choices:["Deixar a carga da frente muito pesada e a de trás leve","Deixar as cargas da frente e de trás exatamente do mesmo peso, e pôr o centro exato da vara sobre o ombro","Não pôr a vara no ombro; carregá-la só com as mãos","Deixar cair as cargas no chão alternadamente enquanto corre"],
    answerIndex:1,
    explanation:"Quando você carrega cargas penduradas de cada lado de uma vara comprida, se os pesos da frente e de trás estão desiguais, a vara pende para um lado e você tem de lutar para segurá-la com as mãos. Isso cansa rápido não só o ombro, mas também os braços e as costas. A resposta certa é deixar as cargas da frente e de trás exatamente com o mesmo equilíbrio. Assim o peso recai por igual bem acima do ombro pela vara, e você consegue carregar cargas pesadas só andando, sem usar músculo a mais para lutar contra a inclinação. Se uma carga for inevitavelmente mais leve, ajuste o equilíbrio deslizando a corda do lado leve para a ponta da vara." },
  { id:38, topic:"Resistência do ar", emoji:"🪂",
    question:"Você tem duas folhas de papel do mesmo tamanho e do mesmo peso. Uma é deixada como folha plana, a outra é amassada com a mão numa bola firme. Quando você as solta ao mesmo tempo de um lugar alto, qual chega primeiro ao chão?",
    choices:["A folha plana do jeito que está","O papel amassado numa bola firme","As duas chegam exatamente ao mesmo tempo","Muda toda vez conforme o vento"],
    answerIndex:1,
    explanation:"Mesmo para coisas do mesmo peso, quando caem pelo ar age um freio chamado resistência do ar, com o ar atrapalhando. A folha de papel plana tem uma superfície ampla, então agarra muito ar embaixo e cai só devagar, feito um paraquedas. Mas o papel amassado numa bolinha toca o ar numa superfície bem estreita, então quase não recebe freio e cai rápido, puxado reto para baixo pela gravidade. Um cata-vento girar com o vento, ou um guarda-chuva quase voar num dia de vento forte, também têm a ver com essa força de freio do ar." },
  { id:39, topic:"Elasticidade", emoji:"🏹",
    question:"Quando você dobra com toda a força um bambu duro e resistente, ou um galho de árvore flexível, e depois solta de repente, ele volta com força à forma original. Para que você pode usar essa propriedade (a elasticidade) para fazer uma ferramenta útil na vida diária?",
    choices:["Uma geladeira para a comida não apodrecer","Um arco e flecha para lançar uma flecha numa presa distante, ou uma armadilha que dispara coisas pesadas","Um filtro para limpar a água","Uma ferramenta para tingir a roupa de branco"],
    answerIndex:1,
    explanation:"A borracha e as molas, e também o bambu e os galhos de árvore, têm uma propriedade misteriosa chamada elasticidade: quando você aplica força a forma deles dobra, e quando solta procuram voltar à forma original a grande velocidade. Enquanto você o segura dobrado com a mão, a força que a pessoa aplica fica guardada um instante dentro dessa ferramenta como energia. No instante em que você solta, essa força guardada é liberada de uma vez, então você consegue lançar uma flecha muitas vezes mais longe, ou acionar uma armadilha, do que arremessando só com o braço. Aproveitando essa força que as plantas da natureza têm, a humanidade fabrica ferramentas para a caça e a vida diária desde a Antiguidade." },
  { id:40, topic:"Lubrificar", emoji:"🛢️",
    question:"As rodas de uma carroça, ou a dobradiça de uma porta, começaram a fazer um barulho chato de rangido e a ficar pesadas toda vez que você as movia. Se você pinga aqui algumas gotas de óleo, por que voltam a se mover suavemente?",
    choices:["Porque o óleo derrete o ferro e o deixa mais leve","Porque o óleo endurece e vira cola","Porque o óleo entra na fresta entre metal e metal e reduz muitíssimo a força de freio do atrito","Porque o cheiro do óleo espanta os insetos"],
    answerIndex:2,
    explanation:"Quando uma máquina ou ferramenta se move, há lugares onde o metal raspa forte e direto contra o metal. Age ali um freio muito forte chamado atrito e, se for deixado assim, ele se desgasta e quebra, ou é preciso muitíssima força para movê-lo. Quando você aplica óleo, forma-se uma fina película de óleo na pequena fresta do metal e impede que raspem direto. Como a força de freio some de uma vez, a ferramenta se move com uma suavidade impressionante e pouca força. Só de aplicar um pouco de óleo de cozinha ou óleo vegetal numa ferramenta, ela dura mais e reduz muito o desgaste das forças da pessoa." }
];
