/*
 * Wise World - Dados do quiz (Português)
 * ⚠ Tradução por IA a partir do original em japonês. Recomenda-se a revisão
 *    por um falante nativo ou especialista em saúde antes de usar.
 * Mantenha id / answerIndex / emoji iguais em todos os idiomas.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).pt = [
  { id:1, topic:"Água segura", emoji:"💧",
    question:"Qual água é segura e não vai te dar dor de barriga?",
    choices:["Água de rio","Água de poço","Água bem fervida no fogo","Água da chuva"],
    answerIndex:2,
    explanation:"A água de rio, de poço e da chuva pode parecer perfeitamente clara e limpa, mas pode estar cheia de seres vivos minúsculos que nossos olhos não conseguem ver (germes e vírus). Se você beber essa água do jeito que está, ela pode causar uma forte dor de estômago ou uma doença grave que põe a vida em risco. Mas quando você põe a água no fogo e a ferve bem até borbulhar, o calor mata todos esses seres nocivos. Por isso, a água que foi bem fervida e depois deixada esfriar é a mais segura do mundo, e a que você pode beber com confiança." },
  { id:2, topic:"Lavar as mãos", emoji:"🧼",
    question:"O que você deve fazer antes de comer?",
    choices:["Lavar as mãos com água e sabão","Limpar as mãos na roupa","Não fazer nada","Tocar na terra"],
    answerIndex:0,
    explanation:"Nossas mãos tocam muitos objetos e o chão todos os dias, então sem perceber elas pegam muitos germes invisíveis. Se você tocar a comida com essas mãos, os germes passam para a comida e você os engole para dentro do corpo junto com ela. Limpar as mãos em roupa suja, ou só molhá-las com água, não tira os germes: eles ficam grudados. Só usando sabão e esfregando as palmas, o dorso das mãos e entre os dedos com bastante espuma, e depois enxaguando com água, é que você consegue de fato eliminar os germes." },
  { id:3, topic:"Lavar as mãos", emoji:"🚽",
    question:"O que você deve fazer depois de usar o banheiro?",
    choices:["Ir brincar na hora","Lavar as mãos com água e sabão","Esfregar as mãos na roupa","Secar as mãos na calça"],
    answerIndex:1,
    explanation:"Depois de usar o banheiro, germes muito fortes das fezes e da urina, que causam doenças, grudam facilmente nas suas mãos. Se você for brincar sem lavar, esses germes passam para as maçanetas e brinquedos que você toca, e transmitem a doença ao próximo amigo ou familiar que os tocar. E se você tocar a própria boca ou os olhos com essas mãos, também pode ficar doente. Por mais pressa que você tenha, lavar sempre bem as mãos com água e sabão depois do banheiro é uma regra que protege a sua vida e a de quem está ao seu redor." },
  { id:4, topic:"Saúde", emoji:"💧",
    question:"Quando você está de barriga ruim e as fezes ficam aguadas (diarreia), o que é mais importante?",
    choices:["Comer bastante","Não beber nada","Beber bastante água segura","Correr e brincar"],
    answerIndex:2,
    explanation:"Quando você está de barriga ruim e fezes aguadas (diarreia) saem várias vezes, o seu corpo perde água e nutrientes valiosos sem parar. Isso se chama desidratação. Quando falta água no corpo, as funções importantes que nos mantêm vivos começam a parar, e as crianças pequenas, principalmente, podem perder a vida de repente. Quando você está com diarreia, em vez de se forçar a comer alimentos sólidos, o melhor é primeiro repor a água que perdeu. Bebendo água segura, fervida e esfriada, aos poucos e muitas vezes, você consegue manter as forças e proteger a sua vida." },
  { id:5, topic:"Cuidar de ferimentos", emoji:"🩹",
    question:"Quando você cai e sangra, o que deve fazer primeiro?",
    choices:["Pôr terra","Lavar bem com água limpa","Deixar sem fazer nada","Esfregar com uma folha"],
    answerIndex:1,
    explanation:"Quando você cai e faz um ferimento que sangra, a ferida fica coberta de terra, lama e poeira do chão, junto com muitos germes. Se você acreditar em ditados antigos e passar terra, esfregar com uma folha suja ou deixar assim, os germes entram fundo na ferida e se multiplicam. Aí a ferida incha, fica vermelha e dói muito, e no pior caso um braço ou uma perna pode apodrecer e parar de se mexer. Quando você se machuca, o primeiro passo certo para a ferida não ficar grave é usar água limpa e segura para lavar com força a lama e a sujeira da ferida." },
  { id:6, topic:"Alimentos", emoji:"🦠",
    question:"O que acontece quando a comida estraga (apodrece)?",
    choices:["Fica gostosa","Apodrece e dá dor de barriga","Fica dura","Não muda nada"],
    answerIndex:1,
    explanation:"A comida contém naturalmente, desde o começo, uma pequena quantidade de micróbios invisíveis. Num lugar fresco os micróbios não conseguem agir, mas se você deixar a comida muito tempo num lugar quente, vira o ambiente perfeito para eles, e em poucas horas eles se multiplicam aos milhões, um número assustador. Quando os micróbios se multiplicam tanto e a forma e a natureza da comida mudam, dizemos que ela estragou. A comida estragada guarda o veneno forte que os micróbios produziram, então comê-la causa forte dor de estômago, diarreia e enjoo, e faz mal ao seu corpo." },
  { id:7, topic:"Alimentos", emoji:"👃",
    question:"Qual é um sinal de que a comida estragou?",
    choices:["Um cheiro ou gosto estranho","Uma cor vermelha","Algo frio","Algo bem cozido"],
    answerIndex:0,
    explanation:"Você pode usar o próprio nariz e a língua para checar se a comida estragou e não está mais segura. Se ela tiver um cheiro azedo estranho ou um cheiro forte e ruim, ou um gosto esquisito quando você prova um pouco, ou se estiver grudenta e fizer fios, isso é prova de que os germes se multiplicaram muito e que se formou veneno. Se você se forçar a comer porque seria desperdício, coloca a sua vida em risco por uma forte intoxicação. Se o cheiro ou o gosto estiverem, mesmo que um pouco, suspeitos, decida jogar fora e nunca engula." },
  { id:8, topic:"Alimentos", emoji:"🪰",
    question:"O que fazer com a comida em que uma mosca pousou?",
    choices:["Comer do jeito que está","Não comer a parte que a mosca tocou (jogar fora)","Criar a mosca","Ficar olhando"],
    answerIndex:1,
    explanation:"O inseto que chamamos de mosca gosta de andar por lugares muito sujos e cheios de germes, como fezes de animais, carcaças e lixões. Por isso, germes que causam doenças terríveis grudam nas suas patinhas finas e no corpo. Quando uma mosca dessas pousa na nossa comida, naquele instante os germes das patas passam para a comida. Se você comer o lugar que ela tocou, está colocando na boca, de forma indireta, germes de fezes e lixo, o que pode causar uma doença grave. Mesmo que pareça desperdício, é mais seguro cortar e jogar fora a parte onde a mosca pousou." },
  { id:9, topic:"Prevenir doenças", emoji:"🦟",
    question:"O que acontece se você deixar água parada por muito tempo?",
    choices:["A água fica limpa","Mosquitos nocivos se multiplicam","Seu dinheiro aumenta","Não acontece nada"],
    answerIndex:1,
    explanation:"A água velha que fica parada num só lugar sem correr vira o lugar perfeito para o inseto chamado mosquito pôr os ovos. Se você deixar baldes, pneus velhos ou latas vazias com água ao redor do quintal ou da casa, ali nascem centenas e milhares de mosquitos novos que voam por toda parte. Quando um mosquito chupa o sangue de uma pessoa, injeta no corpo os germes de doenças muito assustadoras e mortais, como a malária e a dengue. Acabar com as poças de água ao redor da casa é um plano importante para proteger a sua família dessas doenças terríveis." },
  { id:10, topic:"Limpeza", emoji:"✋",
    question:"Quando as unhas estão compridas, o que se acumula dentro?",
    choices:["As mãos ficam mais fortes","Sujeira preta e germes se juntam embaixo das unhas","A comida fica mais gostosa","Não muda nada"],
    answerIndex:1,
    explanation:"Quando as unhas crescem compridas, lama e sujeira pretas entram bem apertadas no espaço estreito entre a unha e a pele enquanto você brinca na terra, ajuda ou trabalha. A sujeira que entra nesse espaço não sai fácil só com uma lavagem normal de mãos, e vira o esconderijo perfeito para os germes. Com as unhas compridas, quando você come com as mãos ou toca o próprio rosto ou uma ferida, esses germes escondidos entram fácil no seu corpo. Manter as unhas sempre curtas é um jeito básico de prevenir doenças." },
  { id:11, topic:"Ao tossir", emoji:"🤧",
    question:"O que você deve fazer quando tosse ou espirra?",
    choices:["Fazer na direção do rosto de alguém","Cobrir a boca e o nariz com a mão ou a manga","Gritar alto","Não fazer nada"],
    answerIndex:1,
    explanation:"Quando você está resfriado ou com uma doença no pulmão, uma única tosse ou espirro lança gotinhas de água invisíveis da boca e do nariz, a vários metros e com força. Cada gotinha pode conter dezenas de milhares de germes de doença. Se você tossir na direção do rosto de alguém, transmite a doença direto, e se não cobrir nada, os germes se espalham pelo ar e todos na mesma sala podem ficar doentes. Quando você tosse, cobrir bem a boca e o nariz com a manga ou a mão evita que você espalhe a doença para a família e os amigos queridos ao seu redor." },
  { id:12, topic:"Limpeza", emoji:"🗑️",
    question:"O que acontece se você deixar lixo jogado perto de casa?",
    choices:["A casa fica limpa","Ratos e insetos nocivos se juntam e a doença se espalha","O lixo vira flores","Não tem problema nenhum"],
    answerIndex:1,
    explanation:"Se você jogar restos de comida e lixo bem ao lado de casa, o cheiro atrai muitos seres como ratos, moscas e baratas. Esses seres costumam andar por esgotos e lugares sujos, então carregam no corpo muitos germes que causam doenças assustadoras. Ao aumentar ao redor do lixo, eles acabam entrando em casa e sujam a comida e a água de beber que estão lá dentro. O lixo deve ser jogado num lugar certo, bem longe de casa, ou enterrado fundo num buraco na terra." },
  { id:13, topic:"Dentes saudáveis", emoji:"🪥",
    question:"Qual é o principal motivo de escovar os dentes?",
    choices:["Pintar os dentes de branco","Reduzir os germes da cárie na boca e proteger os dentes","Deixar o queixo mais forte","Encher o estômago"],
    answerIndex:1,
    explanation:"Depois de comer, sempre ficam pequenos restos de comida nos vãos e na superfície dos dentes. Os seres invisíveis chamados germes da cárie, que vivem na nossa boca, adoram esses restos. Se você deixá-los ali, os germes da cárie se alimentam deles e produzem um ácido forte que dissolve os dentes. Por causa desse ácido, aos poucos abrem-se buracos nos dentes, que deveriam ser a parte mais dura do corpo, e quando chega ao nervo dá uma dor tão forte que você não consegue dormir à noite. Escovar os dentes depois de comer é um trabalho totalmente necessário para tirar o alimento dos germes e proteger os seus dentes." },
  { id:14, topic:"Prevenir ferimentos", emoji:"👟",
    question:"Por que você usa calçados ao andar na rua?",
    choices:["Para os pés crescerem","Para impedir que vermes e germes da terra entrem pela pele dos pés","Para treinar corrida","Para não sujar a roupa"],
    answerIndex:1,
    explanation:"Quando você anda descalço na terra e na lama, seres minúsculos escondidos no chão, pequenos demais para ver (as larvas de parasitas), e germes podem atravessar a pele macia da sola dos pés e entrar sozinhos no seu corpo. Os vermes que entram se instalam na sua barriga (os intestinos) e roubam os nutrientes que você come, deixando você muito anêmico, parando o seu crescimento e tirando a sua energia. Usar calçados também protege você de ferimentos graves por pisar em cacos de vidro, pedras pontudas ou espinhos. Use sempre sapatos ou sandálias quando sair." },
  { id:15, topic:"Limpeza", emoji:"👕",
    question:"O que acontece se você continuar usando roupa suja?",
    choices:["A roupa fica mais resistente","A pele coça ou você fica doente","O corpo fica mais forte","Não muda nada"],
    answerIndex:1,
    explanation:"Se você continuar usando roupa encharcada de suor ou suja de lama por muitos dias, mofo e germes se alimentam do suor e da oleosidade da pele que ficam na roupa e se multiplicam muito dentro das fibras. Como essa roupa suja fica roçando na sua pele o tempo todo, a pele pode inchar e ficar vermelha, coçar muito, ou desenvolver uma doença com feridas que soltam pus. A roupa suja pode ficar livre de germes lavando bem com água e sabão e secando bem ao sol (os raios ultravioleta). Usar sempre roupa limpa é importante para proteger a barreira da sua pele." },
  { id:16, topic:"Limpeza", emoji:"🚿",
    question:"O que tem de bom em lavar o corpo?",
    choices:["A pele fica limpa e você previne doenças de pele","Você cresce","Seu cabelo cai","Você fica com fome"],
    answerIndex:0,
    explanation:"Todos os dias saem da pele humana oleosidade invisível (o sebo) e suor, e a poeira e a terra de fora se misturam, sujando o corpo todo. Se você deixar essa sujeira por muitos dias, os germes ruins se multiplicam na superfície da pele, e você pode ter furúnculos terríveis ou uma doença assustadora em que a pele fica em carne viva e apodrece. Lavando regularmente o corpo todo com cuidado, com água e sabão, e tirando a oleosidade e a sujeira velhas, a sua pele fica saudável e forte, formando uma barreira poderosa que impede a doença de entrar de fora." },
  { id:17, topic:"Água segura", emoji:"💧",
    question:"Quando só tem água barrenta, como bebê-la com segurança?",
    choices:["Beber do jeito que está","Filtrar a lama com pano ou areia e depois ferver no fogo","Só deixar no sol e beber","Beber só um pouco"],
    answerIndex:1,
    explanation:"Quando tudo o que você consegue é água barrenta, beber do jeito que está coloca no seu corpo uma enorme quantidade de germes junto com a lama e causa uma doença grave. Para deixá-la segura são precisos dois saberes. Primeiro, passe a água por um pano limpo e fino, ou por um recipiente cheio de areia e pedrinhas, para filtrar a lama e os pedaços grandes e deixar a água clara. Mas ficar clara não basta: os germes invisíveis continuam vivos. Depois, você precisa pôr no fogo e ferver bem até borbulhar, para que o calor elimine os germes e ela enfim vire água segura para beber. Com sabedoria, você pode fazer água que salva vidas até de água barrenta." },
  { id:18, topic:"Bebês", emoji:"🍼",
    question:"Qual é o melhor alimento para um bebê?",
    choices:["Leite de vaca (cru)","O leite da mãe (leite materno)","Água de rio","Água com açúcar"],
    answerIndex:1,
    explanation:"O corpo de um bebê recém-nascido é muito fraco e quase não tem força para vencer os germes das doenças. O leite da mãe (leite materno) não só contém o alimento perfeito para o bebê crescer, mas também grandes quantidades de um componente protetor especial chamado imunidade, que o defende das doenças. Além disso, o leite materno sai direto do corpo, então nunca toca água suja de fora nem germes de recipientes: é o mais limpo e seguro do mundo. O leite cru de outros animais, a água de rio ou a água com açúcar podem arruinar o estômago e o intestino delicados do bebê e tirar a vida dele, por isso você nunca deve dá-los." },
  { id:19, topic:"Prevenir doenças", emoji:"😷",
    question:"O que fazer perto de alguém com tosse forte?",
    choices:["Manter um pouco de distância e virar o rosto ao passar","Respirar fundo na frente da pessoa","Apertar a mão dela","Ficar bem na frente dela"],
    answerIndex:0,
    explanation:"Doenças respiratórias graves como a tuberculose ficam muito tempo no ar, levadas pelas gotinhas minúsculas e invisíveis que se espalham quando uma pessoa doente tosse. Se você respirar fundo por perto, ou ficar perto por muito tempo, leva esses germes para o fundo dos seus pulmões e pode pegar a mesma doença grave. Quando alguém tosse forte, não se trata de ser malvado nem de tratar a pessoa de forma diferente; para se proteger, mantenha vários metros de distância e, ao passar, vire o rosto e expire devagar: é assim que os dois se protegem." },
  { id:20, topic:"Ar fresco", emoji:"🪟",
    question:"Como manter o ar de um cômodo limpo?",
    choices:["Fechar bem todas as portas e janelas","Abrir janelas e portas para trocar o ar","Todos gritarem alto juntos","Não muda nada"],
    answerIndex:1,
    explanation:"Quando muita gente se junta num cômodo pequeno e fechado, os germes e vírus que alguém carrega vão se acumulando cada vez mais no ar, até o ar do cômodo ficar cheio de germes. Se você ficar muito tempo nesse cômodo, todos respiram o ar sujo e ficam doentes juntos (um contágio em grupo). Abrindo janelas e portas em dois ou mais lugares para trocar o ar fresco de fora pelo ar sujo do cômodo (ventilar), você consegue expulsar os germes do ar e proteger a saúde de todos que estão ali." }
];
