/*
 * Wise World - Datos del quiz (Español)
 * ⚠ Traducción por IA desde el original en japonés. Se recomienda la revisión
 *    de un hablante nativo o experto en salud antes de usarla.
 * Mantén id / answerIndex / emoji iguales en todos los idiomas.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).es = [
  { id:1, topic:"Agua segura", emoji:"💧",
    question:"¿Qué agua es segura y no te hará doler la barriga?",
    choices:["Agua de río","Agua de pozo","Agua hervida bien al fuego","Agua de lluvia"],
    answerIndex:2,
    explanation:"El agua de río, de pozo y de lluvia puede verse perfectamente clara y limpia, pero puede estar llena de seres vivos diminutos que nuestros ojos no pueden ver (gérmenes y virus). Si bebes esa agua tal cual, puede causar un fuerte dolor de estómago o una enfermedad grave que ponga en peligro la vida. Pero cuando pones el agua al fuego y la hierves fuerte hasta que burbujee, el calor mata todos esos seres dañinos. Por eso, el agua que se ha hervido bien y luego se ha dejado enfriar es la más segura del mundo, y la que puedes beber con confianza." },
  { id:2, topic:"Lavarse las manos", emoji:"🧼",
    question:"¿Qué debes hacer antes de comer?",
    choices:["Lavarte las manos con agua y jabón","Limpiarte las manos en la ropa","No hacer nada","Tocar la tierra"],
    answerIndex:0,
    explanation:"Nuestras manos tocan muchos objetos y el suelo cada día, así que sin darnos cuenta recogen muchos gérmenes invisibles. Si tocas la comida con esas manos, los gérmenes pasan a la comida y los tragas dentro de tu cuerpo junto con ella. Limpiarte las manos en ropa sucia, o solo mojarlas con agua, no quita los gérmenes: se quedan pegados. Solo usando jabón y frotando las palmas, el dorso de las manos y entre los dedos con buena espuma, y luego enjuagando con agua, puedes de verdad eliminar los gérmenes." },
  { id:3, topic:"Lavarse las manos", emoji:"🚽",
    question:"¿Qué debes hacer después de ir al baño?",
    choices:["Ir a jugar enseguida","Lavarte las manos con agua y jabón","Frotarte las manos en la ropa","Secarte las manos en el pantalón"],
    answerIndex:1,
    explanation:"Después de ir al baño, en tus manos se pegan con facilidad gérmenes muy fuertes de las heces y la orina que causan enfermedades. Si vas a jugar sin lavarte, esos gérmenes pasan a las manijas y juguetes que tocas, y contagian la enfermedad al siguiente amigo o familiar que los toque. Y si te tocas la boca o los ojos con esas manos, también puedes enfermarte tú. Por mucha prisa que tengas, lavarte siempre bien las manos con agua y jabón después del baño es una regla que protege tu vida y la de quienes te rodean." },
  { id:4, topic:"Salud", emoji:"💧",
    question:"Cuando tu barriga está mal y las heces se vuelven aguadas (diarrea), ¿qué es lo más importante?",
    choices:["Comer mucha comida","No beber nada","Beber bastante agua segura","Correr y jugar"],
    answerIndex:2,
    explanation:"Cuando tu barriga está mal y salen heces aguadas (diarrea) una y otra vez, tu cuerpo pierde agua y nutrientes valiosos sin parar. Esto se llama deshidratación. Cuando al cuerpo le falta agua, las funciones importantes que nos mantienen vivos empiezan a fallar, y los niños pequeños sobre todo pueden perder la vida de repente. Cuando tienes diarrea, en vez de forzarte a comer alimentos sólidos, lo mejor es primero reponer el agua que has perdido. Bebiendo agua segura, hervida y enfriada, poco a poco y muchas veces, puedes mantener tus fuerzas y proteger tu vida." },
  { id:5, topic:"Curar heridas", emoji:"🩹",
    question:"Cuando te caes y sangras, ¿qué debes hacer primero?",
    choices:["Ponerle tierra","Lavarla bien con agua limpia","Dejarla sin hacer nada","Frotarla con una hoja"],
    answerIndex:1,
    explanation:"Cuando te caes y te haces una herida que sangra, la herida queda cubierta de tierra, barro y polvo del suelo, junto con muchos gérmenes. Si crees en viejos dichos y le untas tierra, la frotas con una hoja sucia o la dejas así, los gérmenes entran profundo en la herida y se multiplican. Entonces la herida se hincha roja y duele mucho, y en el peor caso un brazo o una pierna puede pudrirse y dejar de moverse. Cuando te lastimas, el primer paso correcto para que la herida no se vuelva grave es usar agua limpia y segura para enjuagar con fuerza el barro y la suciedad de la herida." },
  { id:6, topic:"Alimentos", emoji:"🦠",
    question:"¿Qué pasa cuando la comida se pudre (se echa a perder)?",
    choices:["Se vuelve sabrosa","Se pudre y te da dolor de barriga","Se vuelve dura","No cambia nada"],
    answerIndex:1,
    explanation:"La comida contiene de forma natural una pequeña cantidad de microbios invisibles desde el principio. En un lugar fresco los microbios no pueden activarse, pero si dejas la comida mucho tiempo en un lugar cálido y caluroso, se vuelve el ambiente perfecto para ellos, y en pocas horas se multiplican hasta millones, una cantidad aterradora. Cuando los microbios se multiplican tanto y la forma y la naturaleza de la comida cambian, decimos que se ha podrido. La comida podrida guarda el fuerte veneno que han hecho los microbios, así que comerla provoca fuerte dolor de estómago, diarrea y náuseas, y daña tu cuerpo." },
  { id:7, topic:"Alimentos", emoji:"👃",
    question:"¿Cuál es una señal de que la comida se ha echado a perder?",
    choices:["Un olor o sabor raro","Un color rojo","Algo frío","Algo bien cocido"],
    answerIndex:0,
    explanation:"Puedes usar tu propia nariz y lengua para comprobar si la comida se ha echado a perder y ya no es segura. Si tiene un olor agrio raro o un olor fuerte y desagradable, o un sabor extraño cuando pruebas un poco, o si está pegajosa y hace hilos, eso es prueba de que los gérmenes se han multiplicado mucho y se ha formado veneno. Si te fuerzas a comerla porque sería un desperdicio, pones tu vida en peligro por una fuerte intoxicación. Si el olor o el sabor son aunque sea un poco sospechosos, decide tirarla y nunca la tragues." },
  { id:8, topic:"Alimentos", emoji:"🪰",
    question:"¿Qué debes hacer con la comida en la que se ha posado una mosca?",
    choices:["Comerla tal cual","No comer la parte que tocó la mosca (tirarla)","Criar la mosca","Quedarte mirándola"],
    answerIndex:1,
    explanation:"El insecto que llamamos mosca gusta de caminar por lugares muy sucios y llenos de gérmenes, como excrementos de animales, cadáveres y basureros. Por eso, en sus patitas finas y su cuerpo se pegan gérmenes que causan enfermedades terribles. Cuando una mosca así se posa en nuestra comida, en ese instante los gérmenes de sus patas pasan a la comida. Si comes el lugar que tocó, estás metiendo en tu boca, de forma indirecta, gérmenes de excrementos y basura, lo que puede causar una enfermedad grave. Aunque parezca un desperdicio, es más seguro cortar y tirar la parte de la comida donde se posó la mosca." },
  { id:9, topic:"Prevenir enfermedades", emoji:"🦟",
    question:"¿Qué pasa si dejas agua estancada mucho tiempo?",
    choices:["El agua se vuelve limpia","Se multiplican mosquitos dañinos","Crece tu dinero","No pasa nada"],
    answerIndex:1,
    explanation:"El agua vieja que se queda en un solo lugar sin correr se vuelve el sitio perfecto para que el insecto llamado mosquito ponga sus huevos. Si dejas baldes, llantas viejas o latas vacías con agua alrededor de tu patio o casa, allí nacen cientos y miles de mosquitos nuevos que vuelan por todas partes. Cuando un mosquito chupa la sangre de una persona, le inyecta en el cuerpo los gérmenes de enfermedades muy temibles y mortales como la malaria y el dengue. Quitar los charcos de agua alrededor de la casa es un plan importante para proteger a tu familia de estas terribles enfermedades." },
  { id:10, topic:"Limpieza", emoji:"✋",
    question:"Cuando tienes las uñas largas, ¿qué se acumula dentro?",
    choices:["Tus manos se hacen más fuertes","Suciedad negra y gérmenes se juntan bajo las uñas","La comida sabe mejor","No cambia nada"],
    answerIndex:1,
    explanation:"Cuando las uñas crecen largas, barro y suciedad negros se meten apretados en el hueco estrecho entre la uña y la piel mientras juegas en la tierra, ayudas o trabajas. La suciedad que entra en ese hueco no sale fácil con un lavado normal de manos, y se vuelve el escondite perfecto para los gérmenes. Con las uñas largas, cuando comes con las manos o te tocas la cara o una herida, esos gérmenes escondidos entran fácil en tu cuerpo. Mantener las uñas siempre cortas es una forma básica de prevenir enfermedades." },
  { id:11, topic:"Al toser", emoji:"🤧",
    question:"¿Qué debes hacer cuando toses o estornudas?",
    choices:["Hacerlo hacia la cara de alguien","Cubrirte la boca y la nariz con la mano o la manga","Gritar fuerte","No hacer nada"],
    answerIndex:1,
    explanation:"Cuando tienes un resfriado o una enfermedad del pulmón, una sola tos o estornudo lanza gotitas de agua invisibles desde tu boca y nariz, a varios metros con gran fuerza. Cada gotita puede contener decenas de miles de gérmenes de enfermedad. Si toses hacia la cara de alguien, le contagias directamente, y si no te cubres, los gérmenes se esparcen por el aire y todos en la misma sala pueden enfermarse. Cuando toses, cubrirte bien la boca y la nariz con la manga o la mano evita que contagies a la querida familia y amigos que te rodean." },
  { id:12, topic:"Limpieza", emoji:"🗑️",
    question:"¿Qué pasa si dejas basura tirada cerca de la casa?",
    choices:["La casa se pone limpia","Se juntan ratas e insectos dañinos y se propaga la enfermedad","La basura se vuelve flores","No pasa nada malo"],
    answerIndex:1,
    explanation:"Si tiras restos de comida y basura justo al lado de tu casa, el olor atrae a muchos seres como ratas, moscas y cucarachas. Estos seres suelen caminar por alcantarillas y lugares sucios, así que llevan en el cuerpo muchos gérmenes que causan enfermedades temibles. Al aumentar alrededor de la basura, terminan entrando en la casa y ensucian la comida y el agua de beber que hay dentro. La basura debe tirarse en un sitio fijo lo bastante lejos de la casa, o enterrarse hondo en un hoyo en la tierra." },
  { id:13, topic:"Dientes sanos", emoji:"🪥",
    question:"¿Cuál es la razón principal para cepillarte los dientes?",
    choices:["Pintar los dientes de blanco","Reducir los gérmenes de caries en la boca y proteger los dientes","Fortalecer la mandíbula","Llenar el estómago"],
    answerIndex:1,
    explanation:"Después de comer, siempre quedan pequeños restos de comida en los huecos y la superficie de los dientes. Los seres invisibles llamados gérmenes de caries que viven en nuestra boca adoran esos restos. Si los dejas ahí, los gérmenes de caries se alimentan de ellos y producen un ácido fuerte que disuelve los dientes. Por ese ácido, poco a poco se abren agujeros en los dientes, que deberían ser la parte más dura del cuerpo, y cuando llega al nervio provoca un dolor tan fuerte que no puedes dormir de noche. Cepillarte los dientes después de comer es un trabajo del todo necesario para quitar el alimento de los gérmenes y proteger tus dientes." },
  { id:14, topic:"Prevenir heridas", emoji:"👟",
    question:"¿Por qué usas zapatos cuando caminas afuera?",
    choices:["Para que tus pies crezcan más","Para impedir que gusanos y gérmenes de la tierra entren por la piel de tus pies","Para practicar correr","Para no ensuciar la ropa"],
    answerIndex:1,
    explanation:"Cuando caminas descalzo sobre tierra y barro, seres diminutos escondidos en el suelo que no se pueden ver (las larvas de parásitos) y gérmenes pueden atravesar la piel blanda de las plantas de tus pies y entrar solos en tu cuerpo. Los gusanos que entran se instalan en tu barriga (los intestinos) y roban los nutrientes que comes, dejándote muy anémico, deteniendo tu crecimiento y quitándote la energía. Usar zapatos también te protege de heridas graves por pisar vidrios rotos, piedras filosas o espinas de madera. Usa siempre zapatos o sandalias cuando salgas afuera." },
  { id:15, topic:"Limpieza", emoji:"👕",
    question:"¿Qué pasa si sigues usando ropa sucia?",
    choices:["La ropa se hace más fuerte","Te pica la piel o te enfermas","Tu cuerpo se hace más fuerte","No cambia nada"],
    answerIndex:1,
    explanation:"Si sigues usando ropa empapada de sudor o manchada de barro durante muchos días, el moho y los gérmenes se alimentan del sudor y la grasa de la piel que hay en la ropa y se multiplican muchísimo dentro de las fibras. Como esa ropa sucia roza tu piel todo el tiempo, la piel puede hincharse roja, picar mucho o desarrollar una enfermedad con llagas que supuran. La ropa sucia puede quedar libre de gérmenes lavándola bien con agua y jabón y secándola bien al sol (los rayos ultravioleta). Usar siempre ropa limpia es importante para proteger la barrera de tu piel." },
  { id:16, topic:"Limpieza", emoji:"🚿",
    question:"¿Qué tiene de bueno lavarte el cuerpo?",
    choices:["La piel se limpia y previenes enfermedades de la piel","Creces más alto","Se te cae el pelo","Te da hambre"],
    answerIndex:0,
    explanation:"Cada día salen de la piel humana grasa invisible (sebo) y sudor, y se les mezclan el polvo y la tierra de afuera, ensuciando todo el cuerpo. Si dejas esta suciedad muchos días, los gérmenes malos se multiplican en la superficie de la piel, y puedes tener terribles forúnculos o una enfermedad temible en la que la piel se llaga y se pudre. Lavando con regularidad todo el cuerpo con suavidad, con agua y jabón, y quitando la grasa y la suciedad viejas, tu piel se mantiene sana y fuerte, formando una barrera poderosa que impide que la enfermedad entre desde afuera." },
  { id:17, topic:"Agua segura", emoji:"💧",
    question:"Cuando solo tienes agua con barro, ¿cómo puedes beberla con seguridad?",
    choices:["Beberla tal cual","Filtrar el barro con tela o arena y luego hervirla al fuego","Solo dejarla al sol y beberla","Beber solo un poco"],
    answerIndex:1,
    explanation:"Cuando lo único que consigues es agua con barro, beberla tal cual mete en tu cuerpo una enorme cantidad de gérmenes junto con el barro y causa una enfermedad grave. Hacerla segura requiere dos saberes. Primero, pasa el agua por una tela limpia y fina, o por un recipiente lleno de arena y piedritas, para filtrar el barro y los trozos grandes y dejar el agua clara. Pero estar clara no basta: los gérmenes invisibles siguen vivos. Después, debes ponerla al fuego y hervirla fuerte hasta que burbujee, para que el calor elimine los gérmenes y por fin se vuelva agua segura para beber. Con sabiduría, puedes hacer agua que salva vidas incluso del agua con barro." },
  { id:18, topic:"Bebés", emoji:"🍼",
    question:"¿Cuál es el mejor alimento para un bebé?",
    choices:["Leche de vaca (cruda)","La leche de la madre (leche materna)","Agua de río","Agua con azúcar"],
    answerIndex:1,
    explanation:"El cuerpo de un bebé recién nacido es muy débil y casi no tiene fuerza para vencer a los gérmenes de las enfermedades. La leche de la madre (leche materna) no solo contiene el alimento perfecto para que el bebé crezca, sino también grandes cantidades de un componente protector especial llamado inmunidad que lo defiende de las enfermedades. Además, la leche materna sale directo del cuerpo, así que nunca toca agua sucia de afuera ni gérmenes de los recipientes: es la más limpia y segura del mundo. La leche cruda de otros animales, el agua de río o el agua con azúcar pueden arruinar el delicado estómago e intestino del bebé y quitarle la vida, así que nunca debes dárselos." },
  { id:19, topic:"Prevenir enfermedades", emoji:"😷",
    question:"¿Qué debes hacer cerca de alguien con una tos fuerte?",
    choices:["Mantener algo de distancia y girar la cara al pasar","Respirar hondo frente a esa persona","Darle la mano","Pararte justo frente a ella"],
    answerIndex:0,
    explanation:"Las enfermedades respiratorias graves como la tuberculosis flotan en el aire mucho tiempo, llevadas por las diminutas gotitas invisibles que se dispersan cuando una persona enferma tose. Si respiras hondo cerca, o te quedas cerca mucho tiempo, metes esos gérmenes en lo profundo de tus pulmones y puedes contraer la misma enfermedad grave. Cuando alguien tiene una tos fuerte, no se trata de ser cruel ni de tratarlo distinto; para protegerte, mantén varios metros de distancia, y al pasar gira la cara y exhala con suavidad: así es como ambos se cuidan." },
  { id:20, topic:"Aire fresco", emoji:"🪟",
    question:"¿Cómo mantienes limpio el aire de una habitación?",
    choices:["Cerrar bien todas las puertas y ventanas","Abrir ventanas y puertas para cambiar el aire","Que todos griten fuerte juntos","No cambia nada"],
    answerIndex:1,
    explanation:"Cuando mucha gente se junta en una habitación pequeña y cerrada, los gérmenes y virus que alguien lleva se acumulan cada vez más en el aire, hasta que el aire de la sala se llena de gérmenes. Si te quedas mucho tiempo en esa sala, todos respiran el aire sucio y se enferman juntos (un contagio en grupo). Abriendo ventanas y puertas en dos o más lugares para cambiar el aire fresco de afuera por el aire sucio de la sala (ventilar), puedes echar los gérmenes fuera del aire y proteger la salud de todos los que están en la habitación." }
];
