/*
 * Wise World - Data ya jaribio (Kiswahili / Swahili)
 * ℹ Imetafsiriwa kwa msaada wa AI kutoka asili ya Kijapani. Weka id / answerIndex / emoji sawa kwa lugha zote.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).sw = [
  { id:1, topic:"Maji salama", emoji:"💧",
    question:"Ni maji gani salama yasiyokuumiza tumbo?",
    choices:["Maji ya mto","Maji ya kisima","Maji yaliyochemshwa vizuri motoni","Maji ya mvua"],
    answerIndex:2,
    explanation:"Maji ya mto, ya kisima na ya mvua yanaweza kuonekana safi kabisa, lakini yanaweza kujaa viumbe vidogo sana ambavyo macho yetu hayawezi kuona (vijidudu na virusi). Ukinywa maji haya kama yalivyo, yanaweza kusababisha maumivu makali ya tumbo au ugonjwa hatari unaotishia maisha. Lakini unapoweka maji motoni na kuyachemsha sana hadi yatoe mapovu, joto huua viumbe vyote hivyo vyenye madhara. Ndiyo maana maji yaliyochemshwa vizuri kisha yakapozwa ndiyo salama zaidi duniani, na ni maji unayoweza kunywa kwa amani." },
  { id:2, topic:"Kunawa mikono", emoji:"🧼",
    question:"Ufanye nini kabla ya kula?",
    choices:["Kunawa mikono kwa maji na sabuni","Kufuta mikono kwenye nguo","Kutofanya chochote","Kugusa udongo"],
    answerIndex:0,
    explanation:"Mikono yetu hugusa vitu vingi na ardhi kila siku, hivyo bila kujua hubeba vijidudu vingi visivyoonekana. Ukigusa chakula kwa mikono hiyo, vijidudu huhamia kwenye chakula na unavimeza mwilini pamoja na chakula. Kufuta mikono kwenye nguo chafu, au kuilowanisha kwa maji tu, hakuondoi vijidudu; hubaki vimegandama. Ni kwa kutumia sabuni na kusugua vizuri kiganja, sehemu ya juu ya mkono na kati ya vidole kwa povu, kisha kusuuza kwa maji, ndipo kweli unaondoa vijidudu." },
  { id:3, topic:"Kunawa mikono", emoji:"🚽",
    question:"Ufanye nini baada ya kutoka chooni?",
    choices:["Kwenda kucheza mara moja","Kunawa mikono kwa maji na sabuni","Kusugua mikono kwenye nguo","Kufuta mikono kwenye suruali"],
    answerIndex:1,
    explanation:"Baada ya kutoka chooni, vijidudu hatari sana kutoka kinyesi na mkojo vinavyosababisha magonjwa hugandama kwa urahisi mikononi mwako. Ukienda kucheza bila kunawa, vijidudu hivyo huhamia kwenye vipini vya milango na vitu vya kuchezea unavyogusa, na kumwambukiza rafiki au mtu wa familia anayegusa baadaye. Na ukigusa mdomo au macho yako kwa mikono hiyo, unaweza kuugua wewe mwenyewe. Hata uwe na haraka kiasi gani, kunawa mikono vizuri kwa maji na sabuni baada ya choo ni sheria inayolinda maisha yako na ya watu wanaokuzunguka." },
  { id:4, topic:"Afya", emoji:"💧",
    question:"Tumbo likiharibika na kinyesi kuwa kama maji (kuhara), jambo muhimu zaidi ni lipi?",
    choices:["Kula chakula kingi","Kutokunywa chochote","Kunywa maji salama mengi","Kukimbia na kucheza"],
    answerIndex:2,
    explanation:"Tumbo likiharibika na kinyesi kama maji (kuhara) kikitoka mara kwa mara, mwili hupoteza maji na lishe muhimu bila kukoma. Hali hii huitwa upungufu wa maji mwilini (dehydration). Mwili ukikosa maji, kazi muhimu zinazotuweka hai huanza kusimama, na hasa watoto wadogo wanaweza kupoteza maisha ghafla. Wakati wa kuhara, badala ya kujilazimisha kula chakula kigumu, jambo bora ni kwanza kurejesha maji uliyopoteza. Kwa kunywa maji salama yaliyochemshwa na kupozwa, kidogo kidogo na mara nyingi, unaweza kudumisha nguvu na kulinda maisha yako." },
  { id:5, topic:"Kutibu vidonda", emoji:"🩹",
    question:"Ukianguka na kutoka damu, ufanye nini kwanza?",
    choices:["Kuweka udongo","Kuosha vizuri kwa maji safi","Kuacha bila kufanya chochote","Kusugua kwa jani"],
    answerIndex:1,
    explanation:"Ukianguka na kupata jeraha linalotoa damu, jeraha hufunikwa na udongo, matope na vumbi kutoka ardhini, pamoja na vijidudu vingi. Ukiamini maneno ya zamani na kupaka udongo, kusugua kwa jani chafu, au kuliacha tu, vijidudu huingia ndani zaidi ya jeraha na kuzaliana. Kisha jeraha huvimba jekundu na kuuma sana, na katika hali mbaya zaidi mkono au mguu unaweza kuoza na kushindwa kusogea. Ukijeruhiwa, hatua ya kwanza sahihi ili jeraha lisiwe baya ni kutumia maji safi na salama yaliyo karibu kuosha matope na uchafu kwenye jeraha kwa nguvu." },
  { id:6, topic:"Chakula", emoji:"🦠",
    question:"Chakula kinapooza (kuharibika) kinakuwaje?",
    choices:["Kinakuwa kitamu","Kinaoza na kuumiza tumbo","Kinakuwa kigumu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Chakula kina viumbe vidogo visivyoonekana (vijidudu) kwa idadi ndogo tangu mwanzo. Mahali penye baridi vijidudu haviwezi kufanya kazi, lakini ukiacha chakula kwa muda mrefu mahali pa joto, huwa mazingira bora kwao, na ndani ya saa chache huzaliana hadi mamilioni, idadi ya kutisha. Vijidudu vinapozaliana kiasi hicho na umbo na hali ya chakula kubadilika, tunasema kimeoza. Chakula kilichooza huhifadhi sumu kali iliyotengenezwa na vijidudu, hivyo kukila husababisha maumivu makali ya tumbo, kuhara na kichefuchefu, na kuharibu mwili wako." },
  { id:7, topic:"Chakula", emoji:"👃",
    question:"Dalili ya kuwa chakula kimeharibika ni ipi?",
    choices:["Harufu au ladha ya ajabu","Rangi nyekundu","Kitu cha baridi","Kitu kilichopikwa vizuri"],
    answerIndex:0,
    explanation:"Unaweza kutumia pua na ulimi wako kuchunguza kama chakula kimeharibika na hakiko salama tena. Kikiwa na harufu ya uchachu isiyo ya kawaida au harufu kali mbaya, au ladha ya ajabu ukiweka kidogo mdomoni, au kikiwa kinata na kuvuta nyuzi, hiyo ni ishara kwamba vijidudu vimezaliana sana na sumu imetokea. Ukijilazimisha kula kwa sababu si vyema kutupa, unahatarisha maisha yako kwa sumu kali ya chakula. Harufu au ladha ikiwa ya shaka hata kidogo, amua kukitupa na usimeze kamwe." },
  { id:8, topic:"Chakula", emoji:"🪰",
    question:"Ufanye nini na chakula ambacho nzi ametua juu yake?",
    choices:["Kula kama kilivyo","Usile sehemu aliyogusa nzi (itupe)","Kufuga nzi","Kukitazama tu"],
    answerIndex:1,
    explanation:"Mdudu tunayemwita nzi hupenda kutembea mahali pachafu sana penye vijidudu vingi, kama kinyesi cha wanyama, mizoga na madampo ya taka. Kwa hiyo vijidudu vinavyosababisha magonjwa ya kutisha hugandama kwenye miguu yake myembamba na mwili. Nzi kama huyo anapotua kwenye chakula chetu, papo hapo vijidudu vya miguuni mwake huhamia chakulani. Ukila sehemu aliyogusa, unaingiza mdomoni mwako bila kujua vijidudu vya kinyesi na taka, jambo linaloweza kusababisha ugonjwa mkubwa. Hata ionekane hasara, ni salama zaidi kukata na kutupa sehemu ya chakula nzi aliyotua." },
  { id:9, topic:"Kuzuia magonjwa", emoji:"🦟",
    question:"Ukiacha maji yamesimama kwa muda mrefu kunatokea nini?",
    choices:["Maji yanakuwa safi","Mbu hatari wanazaliana sana","Pesa zako zinaongezeka","Hakuna kinachotokea"],
    answerIndex:1,
    explanation:"Maji ya zamani yanayobaki mahali pamoja bila kutiririka huwa mahali bora kwa mdudu aitwaye mbu kutaga mayai yake. Ukiacha ndoo, matairi ya zamani au makopo matupu yenye maji karibu na uwanja au nyumba yako, huko huzaliwa mbu wapya mamia na maelfu wanaoruka kila mahali. Mbu anaponyonya damu ya mtu, huingiza mwilini vijidudu vya magonjwa hatari sana yanayoua kama malaria na dengue. Kuondoa madimbwi ya maji karibu na nyumba ni mpango muhimu wa kulinda familia dhidi ya magonjwa haya ya kutisha." },
  { id:10, topic:"Usafi", emoji:"✋",
    question:"Kucha zikiwa ndefu, ndani yake hujikusanya nini?",
    choices:["Mikono inakuwa na nguvu","Uchafu mweusi na vijidudu hujikusanya chini ya kucha","Chakula kinakuwa kitamu zaidi","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Kucha zinapokuwa ndefu, matope na uchafu mweusi hujaa kwenye nafasi nyembamba kati ya ukucha na ngozi unapocheza udongoni, unaposaidia au unapofanya kazi. Uchafu unaoingia nafasi hiyo hautoki kwa urahisi kwa kunawa mikono kwa kawaida, na huwa mahali bora pa kujificha kwa vijidudu. Kwa kucha ndefu, unapokula kwa mikono au unapogusa uso wako au jeraha, vijidudu hivyo vilivyojificha huingia mwilini kwa urahisi. Kukata kucha ziwe fupi kila wakati ni njia ya msingi ya kuzuia magonjwa." },
  { id:11, topic:"Adabu za kukohoa", emoji:"🤧",
    question:"Ufanye nini unapokohoa au kupiga chafya?",
    choices:["Kufanya kuelekea uso wa mtu","Kufunika mdomo na pua kwa mkono au mkono wa nguo","Kupiga kelele","Kutofanya chochote"],
    answerIndex:1,
    explanation:"Unapokuwa na mafua au ugonjwa wa mapafu, kukohoa au kupiga chafya mara moja tu hurusha matone madogo ya maji yasiyoonekana kutoka mdomoni na puani, mita kadhaa mbali kwa nguvu. Kila tone laweza kuwa na vijidudu vya magonjwa elfu kadhaa. Ukikohoa kuelekea uso wa mtu, unamwambukiza moja kwa moja, na usipofunika chochote, vijidudu husambaa hewani na kila mtu chumbani humo anaweza kuugua. Unapokohoa, kufunika vizuri mdomo na pua kwa mkono wa nguo au mkono hukuzuia kueneza ugonjwa kwa familia na marafiki wapendwa wanaokuzunguka." },
  { id:12, topic:"Usafi", emoji:"🗑️",
    question:"Ukiacha taka zimetupwa karibu na nyumba kunatokea nini?",
    choices:["Nyumba inakuwa safi","Panya na wadudu hatari hujikusanya na ugonjwa husambaa","Taka zinakuwa maua","Hakuna tatizo"],
    answerIndex:1,
    explanation:"Ukitupa mabaki ya chakula na taka karibu kabisa na nyumba yako, harufu huvutia viumbe vingi kama panya, nzi na mende. Viumbe hawa kwa kawaida hutembea kwenye mifereji ya maji machafu na sehemu chafu, hivyo hubeba vijidudu vingi vya magonjwa ya kutisha mwilini. Wanapoongezeka kuzunguka taka, hatimaye huingia ndani ya nyumba na kuchafua chakula na maji ya kunywa yaliyo ndani. Taka lazima zitupwe mahali maalum mbali vya kutosha na nyumba, au zifukiwe ndani ya shimo refu ardhini." },
  { id:13, topic:"Meno yenye afya", emoji:"🪥",
    question:"Sababu kuu ya kupiga mswaki ni ipi?",
    choices:["Kupaka meno rangi nyeupe","Kupunguza vijidudu vya kuoza meno mdomoni na kulinda meno","Kuimarisha taya","Kushibisha tumbo"],
    answerIndex:1,
    explanation:"Baada ya kula, mabaki madogo ya chakula hubaki daima kwenye nafasi na uso wa meno. Viumbe visivyoonekana viitwavyo vijidudu vya kuoza meno, vinavyoishi mdomoni mwetu, hupenda sana mabaki hayo. Ukiyaacha pale, vijidudu hivyo huyala na kutengeneza asidi kali inayoyeyusha meno. Kwa sababu ya asidi hiyo, mashimo hutokea polepole kwenye meno, ambayo yanapaswa kuwa sehemu ngumu zaidi ya mwili, na yanapofika kwenye neva huleta maumivu makali kiasi kwamba huwezi kulala usiku. Kupiga mswaki baada ya kula ni kazi ya lazima kabisa ili kuondoa chakula cha vijidudu na kulinda meno yako." },
  { id:14, topic:"Kuzuia majeraha", emoji:"👟",
    question:"Kwa nini uvae viatu unapotembea nje?",
    choices:["Ili miguu ikue","Ili kuzuia minyoo na vijidudu vya udongoni visiingie kupitia ngozi ya miguu","Ili kufanya mazoezi ya kukimbia","Ili nguo zisichafuke"],
    answerIndex:1,
    explanation:"Unapotembea bila viatu juu ya udongo na matope, viumbe vidogo sana vilivyojificha ardhini visivyoonekana (lava za minyoo ya vimelea) na vijidudu vinaweza kutoboa ngozi laini ya nyayo zako na kuingia mwilini vyenyewe. Minyoo inayoingia hujikita tumboni (matumbo) na kuiba lishe unayokula, ikikufanya uwe na upungufu mkubwa wa damu, kusimamisha ukuaji wako na kukunyima nguvu. Kuvaa viatu pia hukulinda dhidi ya majeraha makubwa ya kukanyaga vipande vya glasi, mawe makali au miiba. Vaa viatu au kandambili kila unapotoka nje." },
  { id:15, topic:"Usafi", emoji:"👕",
    question:"Ukiendelea kuvaa nguo chafu kunatokea nini?",
    choices:["Nguo zinakuwa imara","Ngozi inawasha au unaugua","Mwili unakuwa na nguvu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Ukiendelea kuvaa nguo zenye jasho au zilizochafuliwa na matope kwa siku nyingi, ukungu na vijidudu hula jasho la binadamu na mafuta ya ngozi yaliyo kwenye nguo na kuzaliana sana ndani ya nyuzi zake. Kwa kuwa nguo hizo chafu husuguana na ngozi yako wakati wote, ngozi inaweza kuvimba jekundu, kuwasha sana, au kupata ugonjwa wenye vidonda vinavyotoa usaha. Nguo chafu zinaweza kuondolewa vijidudu kabisa kwa kuzifua vizuri kwa maji na sabuni na kuzikausha vizuri juani (miale ya urujuanimno). Kuvaa nguo safi daima ni muhimu ili kulinda ngozi yako." },
  { id:16, topic:"Usafi", emoji:"🚿",
    question:"Kuoga mwili kuna faida gani?",
    choices:["Ngozi inakuwa safi na unazuia magonjwa ya ngozi","Unakuwa mrefu","Nywele zinapukutika","Unasikia njaa"],
    answerIndex:0,
    explanation:"Kila siku ngozi ya binadamu hutoa mafuta yasiyoonekana (sebamu) na jasho, na vumbi na udongo wa nje huchanganyika, ukichafua mwili mzima. Ukiacha uchafu huu kwa siku nyingi, vijidudu vibaya huzaliana juu ya ngozi, na unaweza kupata majipu mabaya au ugonjwa wa kutisha ambapo ngozi hupata vidonda na kuoza. Kwa kuoga mwili mzima kwa upole mara kwa mara, kwa maji na sabuni, na kuondoa mafuta na uchafu wa zamani, ngozi yako hubaki na afya na nguvu, ikitengeneza kinga imara inayozuia ugonjwa usiingie kutoka nje." },
  { id:17, topic:"Maji salama", emoji:"💧",
    question:"Ukiwa na maji yenye matope tu, unaweza kuyanywa salama vipi?",
    choices:["Kuyanywa kama yalivyo","Kuchuja matope kwa kitambaa au mchanga, kisha kuyachemsha motoni","Kuyaweka juani tu kisha kunywa","Kunywa kidogo tu"],
    answerIndex:1,
    explanation:"Unapoweza kupata maji yenye matope tu, kuyanywa kama yalivyo huingiza mwilini mwako vijidudu vingi sana pamoja na matope na husababisha ugonjwa mkubwa. Kuyafanya salama kunahitaji hekima mbili. Kwanza, pitisha maji kwenye kitambaa safi chenye matundu madogo, au chombo kilichojaa mchanga na kokoto ndogo, ili kuchuja matope na uchafu mkubwa na kufanya maji yawe safi. Lakini kuwa safi pekee hakutoshi; vijidudu visivyoonekana bado vi hai. Baada ya hapo, lazima uyaweke motoni na kuyachemsha sana hadi yatoe mapovu, ili joto liangamize vijidudu na hatimaye yawe maji salama ya kunywa. Kwa hekima, unaweza kutengeneza maji yanayookoa maisha hata kutoka maji yenye matope." },
  { id:18, topic:"Watoto wachanga", emoji:"🍼",
    question:"Lishe bora zaidi kwa mtoto mchanga ni ipi?",
    choices:["Maziwa ya ng'ombe (mabichi)","Maziwa ya mama (kunyonyesha)","Maji ya mto","Maji ya sukari"],
    answerIndex:1,
    explanation:"Mwili wa mtoto mchanga aliyezaliwa karibuni ni dhaifu sana na hauna karibu nguvu yoyote ya kushinda vijidudu vya magonjwa. Maziwa ya mama (kunyonyesha) hayana tu lishe kamili kwa mtoto kukua, bali pia kiasi kikubwa cha kiungo maalum cha kinga kiitwacho kinga ya mwili (immunity), kinachomlinda dhidi ya magonjwa. Pia, maziwa ya mama hutoka moja kwa moja mwilini, hivyo hayagusi kamwe maji machafu ya nje wala vijidudu vya vyombo; ni safi na salama zaidi duniani. Maziwa mabichi ya wanyama wengine, maji ya mto au maji ya sukari yanaweza kuharibu tumbo na matumbo dhaifu ya mtoto na kuchukua maisha yake, hivyo usiwahi kumpa." },
  { id:19, topic:"Kuzuia magonjwa", emoji:"😷",
    question:"Karibu na mtu anayekohoa sana ufanye nini?",
    choices:["Kuwa mbali kidogo, na kugeuza uso unapopita","Kuvuta pumzi kwa nguvu mbele yake","Kupeana mkono naye","Kusimama mbele yake kabisa"],
    answerIndex:0,
    explanation:"Magonjwa hatari ya kupumua kama kifua kikuu (TB) huelea hewani kwa muda mrefu, yakibebwa na matone madogo yasiyoonekana yanayotawanyika mtu mgonjwa anapokohoa. Ukivuta pumzi kwa nguvu karibu, au ukikaa karibu kwa muda mrefu, unavuta vijidudu hivyo ndani zaidi ya mapafu yako na unaweza kupata ugonjwa huo huo hatari. Mtu anapokohoa sana, si suala la ukatili wala kumtenga; bali ili kujilinda, kaa umbali wa mita kadhaa, na unapopita geuza uso na utoe pumzi taratibu; hivyo ndivyo nyote wawili mnavyojilinda." },
  { id:20, topic:"Hewa safi", emoji:"🪟",
    question:"Unawezaje kuweka hewa ya chumba safi?",
    choices:["Kufunga milango na madirisha yote vizuri","Kufungua madirisha na milango ili kubadilisha hewa","Kila mtu apige kelele pamoja","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Watu wengi wanapokusanyika katika chumba kidogo kilichofungwa, vijidudu na virusi vya magonjwa anavyobeba mtu fulani hujikusanya zaidi na zaidi hewani, hadi hewa ya chumba ijae vijidudu. Ukikaa muda mrefu katika chumba hicho, kila mtu huvuta hewa chafu na kuugua pamoja (maambukizi ya kikundi). Kwa kufungua madirisha na milango sehemu mbili au zaidi ili kubadilisha hewa safi ya nje na hewa chafu ya chumbani (kupitisha hewa), unaweza kufukuza vijidudu kutoka hewani na kulinda afya ya kila mtu chumbani." },
  { id:21, topic:"Nguzo", emoji:"🪨",
    question:"Unapotaka kusogeza jiwe zito lililozikwa ardhini kwa kutumia fimbo ndefu, ni wapi unapaswa kukandamiza kwa nguvu zaidi ili kulisogeza kwa nguvu ndogo kabisa?",
    choices:["Mahali palipo karibu kabisa na jiwe","Katikati ya fimbo","Mwisho wa fimbo ulio mbali zaidi na jiwe","Ni sawa popote ukandamizapo"],
    answerIndex:2,
    explanation:"Unaposogeza kitu kizito kwa fimbo, kuna kanuni iitwayo «kanuni ya nguzo»: kadiri unavyokuwa mbali na jiwe dogo linalofanya kazi ya egemeo (kitovu cha egemeo), ndivyo unavyohitaji nguvu ndogo zaidi kukandamiza. Ukikandamiza karibu na jiwe, fimbo haiyumbi, lakini ukishika mwisho wa fimbo ulio mbali zaidi na kukandamiza huku ukiegemeza uzito wa mwili wako, unaweza kuinua jiwe zito kwa nguvu ndogo ya kushangaza. Kujua jinsi chombo kinavyofanya kazi hivi kunakuwezesha kuongeza nguvu yako mara nyingi na kufanya kazi nzito kwa urahisi." },
  { id:22, topic:"Nguzo", emoji:"⚖️",
    question:"Unapoinua mzigo mzito kwa fimbo ndefu, ni wapi unapaswa kuweka jiwe dogo (kitovu cha egemeo) linalotegemeza fimbo ili uinuke kwa urahisi zaidi?",
    choices:["Karibu kabisa na mzigo mzito","Karibu kabisa na mahali unapotia nguvu yako","Katikati kabisa ya fimbo","Ni bora usiweke jiwe kabisa"],
    answerIndex:0,
    explanation:"Unapoinua kitu kizito kwa fimbo, nafasi ya jiwe dogo la egemeo (kitovu cha egemeo) ni muhimu sana. Kwa kuweka egemeo hili karibu kabisa na mzigo mzito, mzigo husogea umbali mfupi tu, lakini nguvu unayohitaji kuuinua hupungua sana. Kinyume chake, kama jiwe la egemeo liko karibu nawe, hata ukikandamiza kiasi gani hutaweza kuinua mzigo. Unapotaka kusogeza kitu kizito, kumbuka hekima ya kuweka egemeo karibu na kitu unachotaka kukisogeza." },
  { id:23, topic:"Kuviringika", emoji:"🪵",
    question:"Unaposogeza sanduku zito la mbao kwa kulikokota ardhini, unawezaje kulisogeza kwa urahisi zaidi na nguvu ndogo kabisa?",
    choices:["Weka magogo kadhaa ya mviringo na magumu chini ya sanduku na ulivingirishe","Livute kwa nguvu zako zote kama lilivyo","Mwaga maji juu ya sanduku","Lipige sanduku kwa nguvu chini"],
    answerIndex:0,
    explanation:"Unapokokota kitu kizito moja kwa moja ardhini, hufanya kazi kwa nguvu kani ya kuzuia iitwayo msuguano, inayotokea mahali kitu kinapokwaruzana na ardhi, hivyo kusogeza huhitaji nguvu kubwa mno. Lakini ukiweka magogo ya mviringo na magumu chini ya sanduku, mwendo hubadilika kutoka kukokota hadi magogo kuviringika. Kuviringika kuna kani ya kuzuia ndogo mara makumi kuliko kukokota, hivyo hata mtu mmoja anaweza kusogeza mzigo mzito kwa wepesi. Mzigo unaposonga mbele, unachukua magogo yaliyotoka nyuma na kuyaweka tena mbele — hekima ambayo binadamu ametumia tangu zamani za kale." },
  { id:24, topic:"Mteremko", emoji:"🛝",
    question:"Unapotaka kupandisha mzigo mzito juu ya jukwaa refu lenye kimo cha kifua cha mtu mzima, ni njia ipi ya kuusogeza inayolemea mwili wako kidogo zaidi?",
    choices:["Simama mbele ya jukwaa na uinue mzigo moja kwa moja juu kwa nguvu zako zote","Egemeza ubao mrefu kwa mshazari kwenye jukwaa kutengeneza mteremko, na uusukume juu","Rusha mzigo kwenye jukwaa kutoka mbali","Punguza kimo cha jukwaa ili kiwe kifupi"],
    answerIndex:1,
    explanation:"Ukijaribu kuinua mzigo mzito moja kwa moja juu, unakabiliana ana kwa ana na kani inayovuta vitu kuelekea ardhini (graviti), hivyo lazima ubebe uzito wote kwa misuli yako pekee, jambo linaloumiza mgongo na mikono. Hapa, ukiegemeza ubao mrefu kwa mshazari kwenye jukwaa kutengeneza «mteremko» (sakafu iliyoinama), ubao huja kubeba sehemu kubwa ya uzito wa mzigo. Kwenye mteremko, umbali unaotembea huongezeka, lakini nguvu inayohitajika kusukuma mzigo inaweza kupunguzwa hadi chini ya nusu. Unapobeba vitu mahali pa juu, daima tafuta njia ya kutengeneza mteremko." },
  { id:25, topic:"Kapi", emoji:"🪣",
    question:"Unapovuta ndoo nzito iliyojaa maji kutoka kisima kirefu kwa kamba, ni nini hurahisika ukiweka gurudumu la mviringo linalozunguka (kapi) kwenye mti ulio juu ya kisima na kupitisha kamba juu yake?",
    choices:["Uzito wa maji huwa mwepesi nusu","Kiasi cha maji huongezeka chenyewe","Unaweza kupandisha maji kwa kuvuta kamba chini tu","Kamba haitakatika kamwe"],
    answerIndex:2,
    explanation:"Unapopitisha kamba kwenye gurudumu la mviringo lililo juu ya kisima (kapi tuli), kwa kweli uzito wa maji wenyewe hauwi mwepesi. Lakini jambo zuri la chombo hiki ni kwamba hubadilisha mwelekeo unaotia nguvu. Ukijaribu kupandisha kamba moja kwa moja juu, lazima uiinue kwa nguvu ya mikono na mgongo wako pekee; lakini ukipitisha kamba kwenye gurudumu la mviringo na kuvuta chini, unaweza kuegemeza uzito wote wa mwili wako kwenye kamba. Kuweza kutumia uzito wa mwili wako kuvuta maji mazito kwa urahisi na usalama, ndiyo hekima ya gurudumu hili la mviringo." },
  { id:26, topic:"Gurudumu na ekseli", emoji:"🔄",
    question:"Unapotaka kuzungusha skrubu isiyozunguka kabisa, au mtambo mzito wa kuviringisha wa kisima, unawezaje kuuzungusha kwa urahisi zaidi?",
    choices:["Kuuzungusha kwa fimbo fupi na nyembamba","Kufanya sehemu ya mpini kuwa kubwa na ndefu, na kuzungusha hiyo","Kuuzungusha kwa ncha za vidole tu, bila chombo","Kupiga skrubu kwa nyundo kwa nguvu"],
    answerIndex:1,
    explanation:"Unapotaka kuzungusha ekseli iliyo katikati, ukiweka «mpini mkubwa wa mviringo» au «mpini mrefu» kwenye ekseli hiyo, unaweza kuzalisha kani kubwa ya kuzungusha kwa juhudi ndogo. Hii huitwa kanuni ya «gurudumu na ekseli». Huwezi kusogeza sehemu nyembamba kwa kuizungusha moja kwa moja kwa vidole, lakini unapozungusha mpini mkubwa wa nje, umbali unaopita mkono wako huongezeka, huku kani kwenye ekseli ikiwa kubwa mara nyingi. Mtambo unaoviringisha kamba ya kisima, kitasa cha mlango nyumbani, skrubu za vyombo; kila kitu kinachozunguka karibu nawe hutumia hekima hii." },
  { id:27, topic:"Kitovu cha uzito", emoji:"🏺",
    question:"Kuna watu wanaotembea kwa ustadi huku wakibeba mtungi mzito wa maji au kuni «juu ya kichwa». Kwa nini wanaweza kutembea umbali mrefu bila kuumiza shingo au mgongo?",
    choices:["Kwa sababu wanatembea huku wakikunja mwili mbele au nyuma sana","Kwa sababu wananyoosha mgongo sawasawa kabisa na kuweka kitovu cha mzigo (kitovu chake cha uzito) juu kabisa ya mifupa yao","Kwa sababu wanatikisa mzigo kwa nguvu juu ya kichwa muda wote","Kwa sababu kila mtu huzaliwa na mifupa ya shingo minene kuliko wengine"],
    answerIndex:1,
    explanation:"Unapobeba mzigo mzito mikononi, mzigo huelemea upande mmoja tu wa mwili na misuli huchoka haraka. Lakini ukinyoosha mgongo sawasawa kabisa na kuweka mzigo juu kabisa ya kichwa, uzito wa kitovu cha mzigo (kitovu chake cha uzito) hushuka moja kwa moja kupitia nguzo ya mifupa, kutoka kichwani hadi shingoni kisha uti wa mgongo, na kutokea ardhini. Kwa kuwa mifupa imara, si misuli, ndiyo inayobeba uzito, unaweza kuubeba kwa usalama umbali mrefu bila kupoteza nguvu za misuli, mradi tu udumishe uwiano. Kuweka vitu karibu na «mhimili wa katikati wa mwili wako» ni hekima muhimu ili usijiumize." },
  { id:28, topic:"Shinikizo", emoji:"🦶",
    question:"Unapotembea kwenye «njia ya matope» ambayo baada ya mvua hugeuka matope mazito na miguu huzama, unawezaje kutembea kwa urahisi bila kuzama?",
    choices:["Tembea kwa ncha za vidole, ukifanya nyayo za miguu kuwa ndogo kadiri iwezekanavyo","Funga ubao wa mbao bapa na mkubwa chini ya nyayo za miguu na utembee","Piga kelele kwa sauti kubwa tu na uvuke mbio","Beba mizigo mingi ili uzito wako uongezeke"],
    answerIndex:1,
    explanation:"Uzito unaobonyeza ardhi hujikusanya kwa nguvu zaidi sehemu moja na kuzama ndani zaidi, kama sindano, kadiri eneo linaloligusa linavyokuwa dogo. Hii huitwa «shinikizo». Kusimama kwa ncha za vidole hufanya eneo kuwa dogo, hivyo unazama ndani zaidi. Kinyume chake, ukifunga ubao bapa na mkubwa chini ya nyayo za miguu, uzito wa mwili wako husambaa kwenye eneo pana, hivyo kani inayobonyeza ardhi chini hudhoofika na unaweza kutembea juu ya matope bila kuzama. Kufanya msingi wa jengo zito kuwa mpana na bapa pia ni hekima ileile ya kusambaza shinikizo." },
  { id:29, topic:"Mikokoteni", emoji:"🛒",
    question:"Unapotaka kupakia mzigo mwingi mzito kwenye mkokoteni wa magurudumu mawili na kuuvuta, ni wapi uweke vitu vizito ili uwe mwepesi na rahisi kuvuta zaidi?",
    choices:["Karibu kabisa na mikono yako, kando ya mpini","Mwisho kabisa wa nyuma wa mkokoteni","Juu kabisa ya ekseli ya magurudumu","Ni sawa popote upakiapo"],
    answerIndex:2,
    explanation:"Unapovuta mkokoteni, uzito ulio mikononi mwako hubadilika sana kulingana na mahali unapoweka mzigo. Ukipakia mzigo mzito karibu na mikono yako, unaishia kukimbia huku ukiinua uzito wa mzigo moja kwa moja kwa mikono, na unachoka haraka. Ukiweka mbali sana nyuma, mkokoteni hupinduka nyuma, jambo hatari. Jibu sahihi ni juu kabisa ya ekseli ya magurudumu. Ukiweka vitu vizito hapa, magurudumu imara na ardhi hubeba uzito wote, hivyo karibu hakuna uzito unaoangukia mikononi mwako. Kwa kuwa unahitaji tu nguvu ya kuvuta mbele, unaweza kubeba mzigo mkubwa kwa urahisi sana." },
  { id:30, topic:"Makali", emoji:"🔪",
    question:"Unapononoa makali ya shoka la kupasua kuni, au kisu cha jikoni cha kukata chakula, kwa kuyasugua kwenye jiwe (jiwe la kunoa), kwa nini hukata vizuri zaidi?",
    choices:["Kwa sababu ncha ya makali huwa nyembamba na laini zaidi, na nguvu hujikusanya sehemu moja","Kwa sababu makali huwa moto na kuyeyusha chakula","Kwa sababu makali huwa mazito zaidi","Kwa sababu makali huwa ya mviringo"],
    answerIndex:0,
    explanation:"Kitu kukatwa na makali hutokea kwa sababu nguvu anayotia mtu hujikusanya kwenye sehemu nyembamba sana ya ncha ya makali na kupasua kitu. Makali yanapozeeka na kuwa ya mviringo, nguvu husambaa kwenye eneo pana, hivyo hata ukikandamiza kiasi gani hayakati. Kunoa makali ni kazi ya kusugua ncha iliyoviringika ili iwe nyembamba na laini kadiri iwezekanavyo. Ncha ikishakuwa nyembamba, hata nguvu ndogo huzalisha «shinikizo» kubwa mno sehemu hiyo, hivyo unaweza kukata kuni ngumu au chakula kwa mguso mwepesi. Kutunza vyombo vyako ni msingi wa kuokoa nguvu zako." },
  { id:31, topic:"Msuguano", emoji:"👟",
    question:"Unapotembea kwenye mteremko au juu ya miamba yenye unyevu, ni kipi kinacholeza kidogo na ni salama zaidi: viatu laini vinavyolezesha, au viatu vyenye mifereji yenye meno na kina kwenye sehemu ya chini?",
    choices:["Viatu laini bapa","Viatu vyenye mifereji yenye meno na kina chini","Ni sawa vyovyote uvaavyo","Unalezesha kidogo bila viatu kabisa"],
    answerIndex:1,
    explanation:"Sehemu ya chini ya kiatu inapokwaruzana na ardhi, hapo hufanya kazi kani ya kuzuia iitwayo msuguano inayokuzuia usilezeze. Kama sehemu ya chini ni laini, hakuna kuzuia kunakofanya kazi kati yake na ardhi, na unalezesha na kuanguka kwa urahisi, hasa palipo na maji au matope. Kama sehemu ya chini ina mifereji yenye meno na kina, mifereji hiyo hung'ang'ania kwa nguvu matuta ya ardhi na kuzalisha kuzuia kwenye nguvu. Kulezesha na kuanguka kunaweza kusababisha jeraha kubwa, lakini kwa kujua jinsi msuguano unavyofanya kazi — kwa kuchagua viatu vyenye mifereji mahali penye kulezesha au kwa kuweka nyayo nzima ardhini kwa imara — unaweza kutenda kwa usalama." },
  { id:32, topic:"Kuelea", emoji:"⛵",
    question:"Kijiwe kidogo huzama majini, na bado meli ya mbao iliyo nzito na kubwa maelfu ya mara zaidi inaweza kuelea juu ya maji. Kwa nini?",
    choices:["Kwa sababu meli ina umbo la «bakuli» na hushikilia hewa na maji mengi ndani yake","Kwa sababu meli hupigwa na upepo mwingi","Kwa sababu kuna mawe ya kichawi yaliyopakwa chini yake","Kwa sababu meli imetengenezwa kwa mafuta mepesi kuliko maji"],
    answerIndex:0,
    explanation:"Kwenye kitu kilicho ndani ya maji hufanya kazi kani ya ajabu iitwayo «kani ya kuelea», inayokisukuma juu kiasi sawa na maji kinachoyasukuma kando. Kijiwe ni kigumu ndani na kizito, hivyo kijiwe ni kizito kuliko maji kinayoyasukuma kando, na huzama. Lakini meli kubwa ina umbo la «bakuli», na ndani yake ina hewa nyingi. Ikitazamwa kwa ujumla, huwa nyepesi sana kulingana na ukubwa wake, hivyo kani ya maji inayosukuma kutoka chini huwa na nguvu zaidi, na hata meli kubwa inaweza kuelea juu ya maji bila kupinduka." },
  { id:33, topic:"Pembetatu", emoji:"🔺",
    question:"Unapojenga nyumba au daraja kwa mbao au chuma, kwa nini kuunganisha fremu kwa umbo la «pembetatu» hufanya jengo imara sana na gumu kuvunjika?",
    choices:["Kwa sababu huhitaji vifaa vingi kuliko mraba","Kwa sababu pembetatu ina sifa kwamba umbo lake halipotoki kamwe, hata nguvu kubwa ikitumika kutoka juu","Kwa sababu kutengeneza pembetatu hufanya upepo kupita kwa urahisi zaidi","Kwa sababu ni umbo la kale linalotumika kama hirizi kutoka kwa miungu"],
    answerIndex:1,
    explanation:"Jengo lililotengenezwa kwa nguzo zilizounganishwa kwa «mraba» tu huporomoka kwa urahisi, viungio vyake vikiinama vilegevu, nguvu kubwa au mtikisiko wa tetemeko la ardhi unapotumika kutoka juu au kando. Lakini ukiongeza ufito mmoja wa mshazari ndani ya mraba huo kutengeneza «pembetatu» (muundo wa trasi), basi nguvu itoke mwelekeo wowote, fito huvutana na kusukumana na umbo halipotoki kamwe. Ukitazama madaraja makubwa duniani, au upande wa chini wa paa za majengo, pembetatu hizi daima zimeunganishwa kwa ufundi. Ni hekima nzuri ya ujenzi: hata kwa vifaa vichache, kwa kufikiria tu umbo unaweza kutengeneza kitu imara mara nyingi zaidi." },
  { id:34, topic:"Mwendo", emoji:"🐎",
    question:"Farasi au mkokoteni unaokimbia ukikanyaga breki ghafla na kusimama kabisa, kinatokea nini kwa mzigo na watu waliopanda juu?",
    choices:["Hupinduka nyuma kama walivyo","Hurushwa mbele kwa nguvu","Huruka moja kwa moja juu palepale","Hakuna kinachotokea; nao husimama kabisa"],
    answerIndex:1,
    explanation:"Katika ulimwengu kuna kani ya ajabu iitwayo «hali ya kusonga» (inertia): kitu kinachosonga hujaribu kuendelea kusonga kwa kasi ileile. Hata farasi au gari likisimama ghafla, watu na mizigo iliyo juu bado hujaribu kuendelea mbele. Kwa hiyo, usipoweka miguu yako kwa imara au kufunga mzigo kwa kamba, unarushwa mbele kwa nguvu na kuumia vibaya. Unaposimamisha kitu kinachosonga, au unapopanda chombo cha kasi, lazima ukumbuke kwamba kani hii inayojaribu kurusha vitu mbele hufanya kazi daima, na ujiandae kwa ajili ya usalama wako." },
  { id:35, topic:"Mkasi", emoji:"✂️",
    question:"Unapotaka kukata tawi gumu au kitambaa kinene kwa mkasi, ni sehemu ipi ya ubapa unapaswa kubana ili kukata kwa urahisi zaidi na nguvu ndogo kabisa?",
    choices:["Kwenye ncha kabisa ya ubapa","Kwenye shina la ubapa (karibu zaidi na skrubu au bawaba)","Katikati ya ubapa","Nguvu inayohitajika ni sawa popote ukatapo"],
    answerIndex:1,
    explanation:"Mkasi pia ni chombo chenye manufaa sana kinachotumia «kanuni ya nguzo» tuliyojifunza. Skrubu ambapo bapa mbili huvukana na kufungwa huwa egemeo (kitovu cha egemeo). Kadiri unavyokata karibu na skrubu hii ya egemeo, ndivyo nguvu ambayo mkono wako unaobana huipeleka kwenye ubapa inavyokuwa kubwa mara nyingi. Kwa hiyo, kwa kitu kigumu kisichokatika, kujaribu kukata kwa ncha ya mkasi huumiza mkono tu, lakini ukikibana kwa kina kwenye shina la ubapa, unaweza kukikata kwa nguvu ndogo ya kushangaza. Jua sifa za vyombo vyako na utumie sehemu yenye ufanisi zaidi." },
  { id:36, topic:"Graviti", emoji:"🍎",
    question:"Kwa nini, kati ya kuangusha kijiwe kidogo kwenye mguu kutoka kimo cha goti na kukiangusha kutoka juu ya paa la nyumba, kile kinachoanguka kutoka paani husababisha jeraha kubwa zaidi?",
    choices:["Kwa sababu jiwe huwa baridi zaidi juu ya paa","Kwa sababu graviti, kani inayovuta vitu kuelekea ardhini, hufanya jiwe liende kasi zaidi na zaidi kadiri kuanguka kunavyozidi kuwa kwa mbali, hivyo mshtuko wa kugonga huwa mkali zaidi","Kwa sababu jiwe lililoko mahali pa juu huwa kubwa zaidi kwa ukubwa","Kwa sababu hewa husukuma jiwe chini"],
    answerIndex:1,
    explanation:"Kila kitu kilicho juu ya dunia huvutwa daima na kani iitwayo «graviti», ikikielekeza ardhini. Kwa kitu kilichoko mahali pa juu, kadiri kuanguka kunavyozidi kuwa kwa mbali, ndivyo graviti inavyozidi kukivuta na kasi yake huzidi kuongezeka (huongeza mwendokasi). Kitu kilichoongeza kasi huzalisha nguvu kubwa ya uharibifu (nishati) wakati kinapogonga ardhi au mwili wako. Kutoka kimo cha goti huuma tu, lakini kinachoanguka kutoka paa refu au genge, hata kiwe kijiwe kidogo au chombo, huwa silaha inayoweza kuondoa uhai wa mtu. Unapofanya kazi karibu na mahali pa juu, lazima uhakikishe hakuna mtu chini na uwe makini sana usiangushe chochote." },
  { id:37, topic:"Uwiano", emoji:"⚖️",
    question:"Unapobeba begani fimbo ndefu (mpiko) ukiwa umetundika mitungi miwili mizito ya maji mbele na nyuma, unawezaje kutembea kwa urahisi bila bega kuumia?",
    choices:["Kufanya mzigo wa mbele kuwa mzito sana na mzigo wa nyuma kuwa mwepesi","Kufanya mizigo ya mbele na nyuma kuwa na uzito «sawa kabisa», na kuweka katikati kabisa ya fimbo begani","Kutoweka fimbo begani; kuibeba kwa mikono tu","Kuangusha mizigo chini kwa zamu huku ukikimbia"],
    answerIndex:1,
    explanation:"Unapobeba mizigo iliyotundikwa pande zote mbili za fimbo ndefu, kama uzito wa mbele na nyuma haulingani, fimbo huinama upande mmoja na lazima upambane kuishikilia kwa mikono. Hii huchosha haraka si bega tu, bali mikono na mgongo pia. Jibu sahihi ni kufanya mizigo ya mbele na nyuma kuwa na uwiano sawa kabisa. Hivyo uzito hubonyeza sawasawa juu kabisa ya bega kupitia mpiko, na unaweza kubeba mizigo mizito kwa kutembea tu, bila kutumia misuli ya ziada kupambana na kuinama. Kama mzigo mmoja ni mwepesi bila kuepukika, rekebisha uwiano kwa kuteleza kamba ya upande mwepesi kuelekea ncha ya fimbo." },
  { id:38, topic:"Kizuizi cha hewa", emoji:"🪂",
    question:"Una karatasi mbili zenye ukubwa sawa na uzito sawa. Moja imeachwa karatasi bapa, nyingine imefinywa kwa mkono kuwa mpira mgumu. Unapoziangusha kwa pamoja kutoka mahali pa juu, ni ipi hufika ardhini kwanza?",
    choices:["Karatasi bapa kama ilivyo","Karatasi iliyofinywa kuwa mpira mgumu","Zote hufika kwa wakati mmoja kabisa","Hubadilika kila mara kulingana na upepo"],
    answerIndex:1,
    explanation:"Hata kwa vitu vyenye uzito sawa, vinapoanguka kupitia hewa hufanya kazi kani ya kuzuia iitwayo «kizuizi cha hewa», hewa ikizuia. Karatasi bapa ina eneo pana, hivyo hunasa hewa nyingi chini yake na huanguka polepole tu, kama parachuti. Lakini karatasi iliyofinywa kuwa mpira mdogo hugusa hewa kwenye eneo dogo sana, hivyo karibu haipati kuzuia na huanguka kwa kasi, ikivutwa moja kwa moja chini na graviti. Kinu cha upepo kuzunguka kwa upepo, au mwavuli kukaribia kupeperushwa siku ya upepo mkali, pia kunahusiana na kani hii ya kuzuia ya hewa." },
  { id:39, topic:"Mnyumbuko", emoji:"🏹",
    question:"Unapopinda kwa nguvu zako zote mwanzi mgumu na imara, au tawi laini la mti, kisha ukauachilia ghafla, hurudi kwa nguvu kwenye umbo lake la awali. Unaweza kutumia sifa hii (mnyumbuko) kwa nini ili kutengeneza chombo chenye manufaa maishani?",
    choices:["Friji ili chakula kisioze","«Upinde na mshale» wa kurusha mshale kwa mawindo ya mbali, au «mtego» unaorusha vitu vizito","Kichujio cha kusafisha maji","Chombo cha kupaka rangi nguo kuwa nyeupe"],
    answerIndex:1,
    explanation:"Mpira na spring, na pia mwanzi na matawi ya miti, vina sifa ya ajabu iitwayo «mnyumbuko»: ukitia nguvu umbo lake hupinda, na ukiachilia hujaribu kurudi kwenye umbo lake la awali kwa kasi kubwa. Wakati unaushikilia umepindwa kwa mkono, nguvu anayotia mtu huhifadhiwa kwa muda ndani ya chombo hicho kama «nishati». Wakati unaachilia, nguvu hiyo iliyohifadhiwa huachiliwa kwa pamoja, hivyo unaweza kurusha mshale mbali mara nyingi zaidi, au kuendesha mtego, kuliko kurusha kwa mkono pekee. Kwa kutumia nguvu hii waliyo nayo mimea ya asili, binadamu ametengeneza vyombo vya uwindaji na maisha tangu zamani za kale." },
  { id:40, topic:"Kulainisha", emoji:"🛢️",
    question:"Magurudumu ya mkokoteni, au bawaba ya mlango, yameanza kutoa mlio wa kukerakera kila unapoyasogeza na kuwa mazito. Ukidondosha matone machache ya «mafuta» hapa, kwa nini yanasogea kwa wepesi tena?",
    choices:["Kwa sababu mafuta huyeyusha chuma na kukifanya chepesi","Kwa sababu mafuta hugandamana na kuwa gundi","Kwa sababu mafuta huingia kwenye nafasi kati ya chuma na chuma na kupunguza sana kani ya kuzuia ya kukwaruzana (msuguano)","Kwa sababu harufu ya mafuta hufukuza wadudu"],
    answerIndex:2,
    explanation:"Mashine au chombo kinaposogea, kuna sehemu ambapo chuma hukwaruzana na chuma moja kwa moja na kwa nguvu. Hapo hufanya kazi kani ya kuzuia yenye nguvu sana iitwayo msuguano, na ikiachwa hivyo hujikwarua na kuharibika, au huhitaji nguvu kubwa mno kuisogeza. Unapopaka mafuta, utando mwembamba wa mafuta hutengenezwa kwenye nafasi ndogo ya chuma na kuzuia visikwaruzane moja kwa moja. Kwa sababu kani ya kuzuia hutoweka kwa pamoja, chombo husogea kwa wepesi wa kushangaza na nguvu ndogo. Kwa kupaka tu mafuta kidogo ya kupikia au mafuta ya mimea kwenye chombo, chombo hudumu zaidi na hupunguza sana matumizi ya nguvu za mtu." }
];
