/*
 * Wise World - Data kuis (Bahasa Indonesia)
 * ⚠ Terjemahan AI dari naskah asli bahasa Jepang. Disarankan ditinjau oleh
 *    penutur asli atau ahli kesehatan sebelum digunakan.
 * Jaga id / answerIndex / emoji tetap sama untuk semua bahasa.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).id = [
  { id:1, topic:"Air aman", emoji:"💧",
    question:"Air mana yang aman dan tidak membuat perutmu sakit?",
    choices:["Air sungai","Air sumur","Air yang direbus mendidih di atas api","Air hujan"],
    answerIndex:2,
    explanation:"Air sungai, air sumur, dan air hujan bisa terlihat sangat jernih dan bersih, tetapi bisa penuh dengan makhluk hidup sangat kecil yang tidak bisa dilihat mata kita (kuman dan virus). Jika kamu minum air itu begitu saja, bisa menyebabkan sakit perut yang hebat atau penyakit serius yang mengancam nyawa. Namun, ketika kamu menaruh air di atas api dan merebusnya kuat sampai menggelegak, panas itu membunuh semua makhluk berbahaya tersebut. Itulah sebabnya air yang sudah direbus dengan baik lalu didinginkan adalah air paling aman di dunia, dan air yang bisa kamu minum dengan tenang." },
  { id:2, topic:"Mencuci tangan", emoji:"🧼",
    question:"Apa yang harus kamu lakukan sebelum makan?",
    choices:["Mencuci tangan dengan air dan sabun","Mengelap tangan ke baju","Tidak melakukan apa-apa","Menyentuh tanah"],
    answerIndex:0,
    explanation:"Tangan kita menyentuh banyak benda dan tanah setiap hari, jadi tanpa sadar tangan kita membawa banyak kuman yang tidak terlihat. Jika kamu menyentuh makanan dengan tangan itu, kuman berpindah ke makanan dan kamu menelannya ke dalam tubuh bersama makanan. Mengelap tangan ke baju kotor, atau hanya membasahinya dengan air, tidak menghilangkan kuman: kuman tetap menempel. Hanya dengan memakai sabun dan menggosok telapak tangan, punggung tangan, dan sela-sela jari dengan busa yang banyak, lalu membilasnya dengan air, kamu benar-benar bisa menghilangkan kuman." },
  { id:3, topic:"Mencuci tangan", emoji:"🚽",
    question:"Apa yang harus kamu lakukan setelah dari toilet?",
    choices:["Langsung pergi bermain","Mencuci tangan dengan air dan sabun","Menggosok tangan ke baju","Mengeringkan tangan di celana"],
    answerIndex:1,
    explanation:"Setelah dari toilet, kuman yang sangat kuat dari tinja dan air seni, yang menyebabkan penyakit, mudah menempel di tanganmu. Jika kamu langsung bermain tanpa mencuci tangan, kuman itu berpindah ke gagang pintu dan mainan yang kamu sentuh, lalu menularkan penyakit kepada teman atau keluarga berikutnya yang menyentuhnya. Dan jika kamu menyentuh mulut atau matamu sendiri dengan tangan itu, kamu juga bisa jatuh sakit. Seberapa pun terburu-burunya kamu, selalu mencuci tangan dengan baik memakai air dan sabun setelah dari toilet adalah aturan yang melindungi nyawamu dan nyawa orang di sekitarmu." },
  { id:4, topic:"Kesehatan", emoji:"💧",
    question:"Saat perutmu sakit dan tinja menjadi cair (diare), apa yang paling penting?",
    choices:["Makan banyak","Tidak minum apa-apa","Minum banyak air yang aman","Berlari dan bermain"],
    answerIndex:2,
    explanation:"Saat perutmu sakit dan tinja cair (diare) keluar berulang kali, tubuhmu terus-menerus kehilangan air dan zat gizi yang berharga. Ini disebut dehidrasi. Saat tubuh kekurangan air, fungsi-fungsi penting yang menjaga kita tetap hidup mulai berhenti, dan anak kecil terutama bisa tiba-tiba kehilangan nyawa. Saat diare, daripada memaksakan diri makan makanan padat, yang terbaik adalah lebih dulu mengganti air yang hilang. Dengan minum air yang aman, yang sudah direbus dan didinginkan, sedikit demi sedikit dan berkali-kali, kamu bisa menjaga tenaga dan melindungi nyawamu." },
  { id:5, topic:"Merawat luka", emoji:"🩹",
    question:"Saat kamu jatuh dan berdarah, apa yang harus dilakukan lebih dulu?",
    choices:["Menaruh tanah di atasnya","Mencucinya bersih dengan air bersih","Membiarkannya tanpa berbuat apa-apa","Menggosoknya dengan daun"],
    answerIndex:1,
    explanation:"Saat kamu jatuh dan mendapat luka yang berdarah, luka itu tertutup tanah, lumpur, dan debu dari tanah, beserta banyak kuman. Jika kamu percaya pada perkataan lama dan mengoleskan tanah, menggosoknya dengan daun kotor, atau membiarkannya begitu saja, kuman masuk jauh ke dalam luka dan berkembang biak. Lalu luka membengkak merah dan sangat sakit, dan dalam kasus terburuk lengan atau kaki bisa membusuk dan tidak bisa digerakkan. Saat kamu terluka, langkah pertama yang benar agar luka tidak menjadi parah adalah memakai air bersih dan aman untuk membilas lumpur dan kotoran dari luka dengan kuat." },
  { id:6, topic:"Makanan", emoji:"🦠",
    question:"Apa yang terjadi saat makanan membusuk (rusak)?",
    choices:["Menjadi enak","Membusuk dan membuat sakit perut","Menjadi keras","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Makanan secara alami sudah mengandung sedikit mikroba tak terlihat sejak awal. Di tempat sejuk mikroba tidak bisa aktif, tetapi jika kamu membiarkan makanan lama di tempat yang hangat dan panas, itu menjadi lingkungan yang sempurna bagi mereka, dan dalam beberapa jam mereka berkembang biak hingga jutaan, jumlah yang menakutkan. Saat mikroba berkembang biak sebanyak itu dan bentuk serta sifat makanan berubah, kita katakan makanan itu membusuk. Makanan busuk menyimpan racun kuat yang dibuat mikroba, sehingga memakannya menyebabkan sakit perut hebat, diare, dan mual, serta merusak tubuhmu." },
  { id:7, topic:"Makanan", emoji:"👃",
    question:"Apa tanda bahwa makanan sudah rusak?",
    choices:["Bau atau rasa yang aneh","Warna merah","Sesuatu yang dingin","Sesuatu yang matang dengan baik"],
    answerIndex:0,
    explanation:"Kamu bisa memakai hidung dan lidahmu sendiri untuk memeriksa apakah makanan sudah rusak dan tidak lagi aman. Jika baunya asam tidak biasa atau berbau tajam dan tidak enak, atau rasanya aneh saat kamu mencicipi sedikit, atau jika lengket dan berlendir, itu bukti bahwa kuman sudah berkembang biak banyak dan racun sudah terbentuk. Jika kamu memaksakan diri memakannya karena sayang dibuang, kamu membahayakan nyawamu karena keracunan yang berat. Jika bau atau rasanya sedikit saja mencurigakan, putuskan untuk membuangnya dan jangan pernah menelannya." },
  { id:8, topic:"Makanan", emoji:"🪰",
    question:"Apa yang harus dilakukan pada makanan yang dihinggapi lalat?",
    choices:["Memakannya begitu saja","Tidak memakan bagian yang dihinggapi lalat (membuangnya)","Memelihara lalatnya","Memandanginya saja"],
    answerIndex:1,
    explanation:"Serangga yang kita sebut lalat suka berjalan-jalan di tempat yang sangat kotor dan penuh kuman, seperti kotoran hewan, bangkai, dan tempat sampah. Karena itu, kuman penyebab penyakit yang mengerikan menempel di kaki-kaki halus dan tubuhnya. Saat lalat seperti itu hinggap di makanan kita, pada saat itu juga kuman di kakinya berpindah ke makanan. Jika kamu memakan bagian yang dihinggapinya, secara tidak langsung kamu memasukkan kuman dari kotoran dan sampah ke mulutmu, yang bisa menyebabkan penyakit berat. Walau terasa sayang, lebih aman memotong dan membuang bagian makanan yang dihinggapi lalat." },
  { id:9, topic:"Mencegah penyakit", emoji:"🦟",
    question:"Apa yang terjadi jika kamu membiarkan air tergenang lama?",
    choices:["Airnya menjadi bersih","Nyamuk berbahaya berkembang biak","Uangmu bertambah","Tidak terjadi apa-apa"],
    answerIndex:1,
    explanation:"Air lama yang menggenang di satu tempat tanpa mengalir menjadi tempat yang sempurna bagi serangga bernama nyamuk untuk bertelur. Jika kamu membiarkan ember, ban bekas, atau kaleng kosong berisi air di sekitar halaman atau rumah, dari situ lahir ratusan dan ribuan nyamuk baru yang terbang ke mana-mana. Saat nyamuk mengisap darah seseorang, ia menyuntikkan ke dalam tubuh kuman penyakit yang sangat menakutkan dan mematikan seperti malaria dan demam berdarah. Menghilangkan genangan air di sekitar rumah adalah rencana penting untuk melindungi keluargamu dari penyakit-penyakit yang mengerikan itu." },
  { id:10, topic:"Kebersihan", emoji:"✋",
    question:"Saat kuku panjang, apa yang menumpuk di dalamnya?",
    choices:["Tangan menjadi lebih kuat","Kotoran hitam dan kuman menumpuk di bawah kuku","Makanan menjadi lebih enak","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Saat kuku tumbuh panjang, lumpur dan kotoran hitam masuk berdesakan ke celah sempit antara kuku dan kulit ketika kamu bermain di tanah, membantu, atau bekerja. Kotoran yang masuk ke celah ini tidak mudah hilang hanya dengan cuci tangan biasa, dan menjadi tempat persembunyian yang sempurna bagi kuman. Dengan kuku panjang, saat kamu makan dengan tangan atau menyentuh wajah atau luka, kuman yang tersembunyi itu mudah masuk ke tubuhmu. Menjaga kuku selalu pendek adalah cara dasar untuk mencegah penyakit." },
  { id:11, topic:"Saat batuk", emoji:"🤧",
    question:"Apa yang harus kamu lakukan saat batuk atau bersin?",
    choices:["Melakukannya ke arah wajah orang","Menutup mulut dan hidung dengan tangan atau lengan baju","Berteriak keras","Tidak melakukan apa-apa"],
    answerIndex:1,
    explanation:"Saat kamu pilek atau sakit paru-paru, sekali batuk atau bersin saja melontarkan percikan air sangat kecil yang tak terlihat dari mulut dan hidungmu, sejauh beberapa meter dengan kuat. Setiap percikan bisa mengandung puluhan ribu kuman penyakit. Jika kamu batuk ke arah wajah orang, kamu menularkan penyakit secara langsung, dan jika tidak menutupinya, kuman menyebar ke udara dan semua orang di ruangan yang sama bisa jatuh sakit. Saat batuk, menutup rapat mulut dan hidung dengan lengan baju atau tangan mencegahmu menularkan penyakit kepada keluarga dan teman tersayang di sekitarmu." },
  { id:12, topic:"Kebersihan", emoji:"🗑️",
    question:"Apa yang terjadi jika kamu membiarkan sampah berserakan dekat rumah?",
    choices:["Rumah menjadi bersih","Tikus dan serangga berbahaya berkumpul dan penyakit menyebar","Sampah berubah menjadi bunga","Tidak ada masalah"],
    answerIndex:1,
    explanation:"Jika kamu membuang sisa makanan dan sampah tepat di samping rumah, baunya menarik banyak makhluk seperti tikus, lalat, dan kecoa. Makhluk-makhluk ini biasa berjalan di selokan dan tempat kotor, jadi mereka membawa banyak kuman penyebab penyakit yang menakutkan di tubuhnya. Saat mereka bertambah banyak di sekitar sampah, akhirnya mereka masuk ke dalam rumah dan mengotori makanan dan air minum yang ada di dalam. Sampah harus dibuang di tempat tertentu yang cukup jauh dari rumah, atau dikubur dalam-dalam di lubang di tanah." },
  { id:13, topic:"Gigi sehat", emoji:"🪥",
    question:"Apa alasan utama menyikat gigi?",
    choices:["Mengecat gigi menjadi putih","Mengurangi kuman gigi berlubang di mulut dan melindungi gigi","Menguatkan rahang","Mengenyangkan perut"],
    answerIndex:1,
    explanation:"Setelah makan, selalu ada sisa makanan kecil yang tertinggal di sela dan permukaan gigi. Makhluk tak terlihat yang disebut kuman gigi berlubang, yang hidup di mulut kita, sangat menyukai sisa makanan itu. Jika kamu membiarkannya, kuman gigi berlubang memakannya dan menghasilkan asam kuat yang melarutkan gigi. Karena asam ini, sedikit demi sedikit lubang terbuka di gigi, yang seharusnya bagian paling keras di tubuh, dan saat mencapai saraf menimbulkan rasa sakit yang begitu hebat sampai kamu tidak bisa tidur di malam hari. Menyikat gigi setelah makan adalah pekerjaan yang benar-benar perlu untuk menghilangkan makanan kuman dan melindungi gigimu." },
  { id:14, topic:"Mencegah luka", emoji:"👟",
    question:"Mengapa kamu memakai alas kaki saat berjalan di luar?",
    choices:["Agar kaki menjadi besar","Untuk mencegah cacing dan kuman dari tanah masuk lewat kulit kaki","Untuk latihan berlari","Agar baju tidak kotor"],
    answerIndex:1,
    explanation:"Saat kamu berjalan tanpa alas kaki di atas tanah dan lumpur, makhluk sangat kecil yang bersembunyi di tanah yang terlalu kecil untuk dilihat (larva cacing parasit) dan kuman bisa menembus kulit lembut telapak kakimu dan masuk sendiri ke dalam tubuhmu. Cacing yang masuk menetap di perutmu (usus) dan mencuri zat gizi yang kamu makan, membuatmu sangat kekurangan darah, menghentikan pertumbuhanmu, dan menguras tenagamu. Memakai alas kaki juga melindungimu dari luka parah karena menginjak pecahan kaca, batu tajam, atau duri kayu. Selalu pakai sepatu atau sandal saat keluar." },
  { id:15, topic:"Kebersihan", emoji:"👕",
    question:"Apa yang terjadi jika kamu terus memakai baju kotor?",
    choices:["Baju menjadi lebih kuat","Kulit gatal atau kamu jatuh sakit","Tubuh menjadi lebih kuat","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Jika kamu terus memakai baju yang basah oleh keringat atau kotor oleh lumpur selama berhari-hari, jamur dan kuman memakan keringat dan minyak kulit yang ada di baju dan berkembang biak luar biasa banyak di dalam seratnya. Karena baju kotor itu terus bergesekan dengan kulitmu, kulit bisa membengkak merah, sangat gatal, atau terkena penyakit dengan luka yang bernanah. Baju kotor bisa dibebaskan dari kuman dengan mencucinya bersih memakai air dan sabun lalu menjemurnya sampai kering di bawah sinar matahari (sinar ultraviolet). Selalu memakai baju bersih penting untuk melindungi pelindung kulitmu." },
  { id:16, topic:"Kebersihan", emoji:"🚿",
    question:"Apa untungnya membersihkan badan?",
    choices:["Kulit menjadi bersih dan kamu mencegah penyakit kulit","Kamu bertambah tinggi","Rambutmu rontok","Kamu menjadi lapar"],
    answerIndex:0,
    explanation:"Setiap hari, minyak tak terlihat (sebum) dan keringat keluar dari kulit manusia, dan debu serta tanah dari luar bercampur, mengotori seluruh tubuh. Jika kamu membiarkan kotoran ini berhari-hari, kuman jahat berkembang biak di permukaan kulit, dan kamu bisa terkena bisul yang parah atau penyakit menakutkan di mana kulit luka dan membusuk. Dengan rutin membersihkan seluruh tubuh secara lembut, memakai air dan sabun, dan menghilangkan minyak dan kotoran lama, kulitmu tetap sehat dan kuat, membentuk pelindung yang kuat yang mencegah penyakit masuk dari luar." },
  { id:17, topic:"Air aman", emoji:"💧",
    question:"Saat hanya ada air berlumpur, bagaimana cara meminumnya dengan aman?",
    choices:["Meminumnya begitu saja","Menyaring lumpur dengan kain atau pasir, lalu merebusnya di atas api","Hanya menjemurnya di bawah matahari lalu meminumnya","Meminumnya sedikit saja"],
    answerIndex:1,
    explanation:"Saat yang bisa kamu dapatkan hanyalah air berlumpur, meminumnya begitu saja memasukkan kuman dalam jumlah sangat banyak ke tubuhmu bersama lumpur dan menyebabkan penyakit berat. Membuatnya aman memerlukan dua kebijaksanaan. Pertama, alirkan air melewati kain bersih yang halus, atau wadah yang diisi pasir dan kerikil, untuk menyaring lumpur dan kotoran besar agar air menjadi bening. Namun, menjadi bening saja belum cukup: kuman tak terlihat masih hidup. Setelah itu, kamu harus menaruhnya di atas api dan merebusnya kuat sampai menggelegak, agar panas memusnahkan kuman dan akhirnya menjadi air minum yang aman. Dengan kebijaksanaan, kamu bisa membuat air yang menyelamatkan nyawa bahkan dari air berlumpur." },
  { id:18, topic:"Bayi", emoji:"🍼",
    question:"Apa makanan terbaik untuk bayi?",
    choices:["Susu sapi (mentah)","Susu ibu (ASI)","Air sungai","Air gula"],
    answerIndex:1,
    explanation:"Tubuh bayi yang baru lahir sangat lemah dan hampir tidak punya tenaga untuk mengalahkan kuman penyakit. Susu ibu (ASI) tidak hanya mengandung gizi yang sempurna agar bayi tumbuh, tetapi juga sejumlah besar zat pelindung khusus bernama kekebalan, yang melindunginya dari penyakit. Selain itu, ASI keluar langsung dari tubuh, jadi tidak pernah tersentuh air kotor dari luar atau kuman dari wadah: ASI adalah yang paling bersih dan paling aman di dunia. Susu mentah hewan lain, air sungai, atau air gula bisa merusak lambung dan usus bayi yang lembut dan merenggut nyawanya, jadi kamu tidak boleh memberikannya." },
  { id:19, topic:"Mencegah penyakit", emoji:"😷",
    question:"Apa yang harus dilakukan di dekat orang yang batuk parah?",
    choices:["Menjaga sedikit jarak dan memalingkan wajah saat berpapasan","Menarik napas dalam-dalam di depan orang itu","Berjabat tangan dengannya","Berdiri tepat di depannya"],
    answerIndex:0,
    explanation:"Penyakit pernapasan berat seperti TBC mengapung di udara dalam waktu lama, terbawa oleh percikan sangat kecil dan tak terlihat yang berhamburan saat orang yang sakit batuk. Jika kamu menarik napas dalam-dalam di dekatnya, atau berada dekat lama-lama, kamu menghirup kuman itu jauh ke dalam paru-parumu dan bisa tertular penyakit berat yang sama. Saat ada orang yang batuk parah, ini bukan soal bersikap jahat atau memperlakukannya berbeda; untuk melindungi diri, jagalah jarak beberapa meter, dan saat berpapasan, palingkan wajah dan embuskan napas perlahan: begitulah cara kalian berdua saling menjaga." },
  { id:20, topic:"Udara segar", emoji:"🪟",
    question:"Bagaimana menjaga udara di dalam ruangan tetap bersih?",
    choices:["Menutup rapat semua pintu dan jendela","Membuka jendela dan pintu untuk mengganti udara","Semua orang berteriak keras bersama","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Saat banyak orang berkumpul di ruangan kecil yang tertutup, kuman dan virus yang dibawa seseorang makin lama makin menumpuk di udara, sampai udara di ruangan penuh kuman. Jika kamu berada lama di ruangan itu, semua orang menghirup udara kotor dan jatuh sakit bersama-sama (penularan beramai-ramai). Dengan membuka jendela dan pintu di dua tempat atau lebih untuk mengganti udara segar dari luar dengan udara kotor di ruangan (ventilasi), kamu bisa mengusir kuman dari udara dan melindungi kesehatan semua orang yang ada di ruangan." }
];
