/*
 * Wise World - Data ya jaribio (Kiswahili / Swahili)
 * ℹ Imetafsiriwa kwa msaada wa AI kutoka asili ya Kijapani. Weka id / answerIndex / emoji sawa kwa lugha zote.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).sw = [
  { id:1, topic:"Maji salama", emoji:"💧",
    question:"Ni maji gani salama yasiyokuumiza tumbo?",
    choices:["Maji ya mto","Maji ya kisima","Maji yaliyochemshwa vizuri motoni","Maji ya mvua"],
    answerIndex:2,
    explanation:"Maji ya mto, ya kisima na ya mvua yanaweza kuonekana safi kabisa, lakini yanaweza kujaa viumbe vidogo sana ambavyo macho yetu hayawezi kuona (vijidudu na virusi). Ukinywa maji haya kama yalivyo, yanaweza kusababisha maumivu makali ya tumbo au ugonjwa hatari unaotishia maisha. Lakini unapoweka maji motoni na kuyachemsha sana hadi yatoe mapovu, joto huua viumbe vyote hivyo vyenye madhara. Ndiyo maana maji yaliyochemshwa vizuri kisha yakapozwa ndiyo salama zaidi duniani, na ni maji unayoweza kunywa kwa amani." },
  { id:2, topic:"Kunawa mikono", emoji:"🧼",
    question:"Ufanye nini kabla ya kula?",
    choices:["Kunawa mikono kwa maji na sabuni","Kufuta mikono kwenye nguo","Kutofanya chochote","Kugusa udongo"],
    answerIndex:0,
    explanation:"Mikono yetu hugusa vitu vingi na ardhi kila siku, hivyo bila kujua hubeba vijidudu vingi visivyoonekana. Ukigusa chakula kwa mikono hiyo, vijidudu huhamia kwenye chakula na unavimeza mwilini pamoja na chakula. Kufuta mikono kwenye nguo chafu, au kuilowanisha kwa maji tu, hakuondoi vijidudu; hubaki vimegandama. Ni kwa kutumia sabuni na kusugua vizuri kiganja, sehemu ya juu ya mkono na kati ya vidole kwa povu, kisha kusuuza kwa maji, ndipo kweli unaondoa vijidudu." },
  { id:3, topic:"Kunawa mikono", emoji:"🚽",
    question:"Ufanye nini baada ya kutoka chooni?",
    choices:["Kwenda kucheza mara moja","Kunawa mikono kwa maji na sabuni","Kusugua mikono kwenye nguo","Kufuta mikono kwenye suruali"],
    answerIndex:1,
    explanation:"Baada ya kutoka chooni, vijidudu hatari sana kutoka kinyesi na mkojo vinavyosababisha magonjwa hugandama kwa urahisi mikononi mwako. Ukienda kucheza bila kunawa, vijidudu hivyo huhamia kwenye vipini vya milango na vitu vya kuchezea unavyogusa, na kumwambukiza rafiki au mtu wa familia anayegusa baadaye. Na ukigusa mdomo au macho yako kwa mikono hiyo, unaweza kuugua wewe mwenyewe. Hata uwe na haraka kiasi gani, kunawa mikono vizuri kwa maji na sabuni baada ya choo ni sheria inayolinda maisha yako na ya watu wanaokuzunguka." },
  { id:4, topic:"Afya", emoji:"💧",
    question:"Tumbo likiharibika na kinyesi kuwa kama maji (kuhara), jambo muhimu zaidi ni lipi?",
    choices:["Kula chakula kingi","Kutokunywa chochote","Kunywa maji salama mengi","Kukimbia na kucheza"],
    answerIndex:2,
    explanation:"Tumbo likiharibika na kinyesi kama maji (kuhara) kikitoka mara kwa mara, mwili hupoteza maji na lishe muhimu bila kukoma. Hali hii huitwa upungufu wa maji mwilini (dehydration). Mwili ukikosa maji, kazi muhimu zinazotuweka hai huanza kusimama, na hasa watoto wadogo wanaweza kupoteza maisha ghafla. Wakati wa kuhara, badala ya kujilazimisha kula chakula kigumu, jambo bora ni kwanza kurejesha maji uliyopoteza. Kwa kunywa maji salama yaliyochemshwa na kupozwa, kidogo kidogo na mara nyingi, unaweza kudumisha nguvu na kulinda maisha yako." },
  { id:5, topic:"Kutibu vidonda", emoji:"🩹",
    question:"Ukianguka na kutoka damu, ufanye nini kwanza?",
    choices:["Kuweka udongo","Kuosha vizuri kwa maji safi","Kuacha bila kufanya chochote","Kusugua kwa jani"],
    answerIndex:1,
    explanation:"Ukianguka na kupata jeraha linalotoa damu, jeraha hufunikwa na udongo, matope na vumbi kutoka ardhini, pamoja na vijidudu vingi. Ukiamini maneno ya zamani na kupaka udongo, kusugua kwa jani chafu, au kuliacha tu, vijidudu huingia ndani zaidi ya jeraha na kuzaliana. Kisha jeraha huvimba jekundu na kuuma sana, na katika hali mbaya zaidi mkono au mguu unaweza kuoza na kushindwa kusogea. Ukijeruhiwa, hatua ya kwanza sahihi ili jeraha lisiwe baya ni kutumia maji safi na salama yaliyo karibu kuosha matope na uchafu kwenye jeraha kwa nguvu." },
  { id:6, topic:"Chakula", emoji:"🦠",
    question:"Chakula kinapooza (kuharibika) kinakuwaje?",
    choices:["Kinakuwa kitamu","Kinaoza na kuumiza tumbo","Kinakuwa kigumu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Chakula kina viumbe vidogo visivyoonekana (vijidudu) kwa idadi ndogo tangu mwanzo. Mahali penye baridi vijidudu haviwezi kufanya kazi, lakini ukiacha chakula kwa muda mrefu mahali pa joto, huwa mazingira bora kwao, na ndani ya saa chache huzaliana hadi mamilioni, idadi ya kutisha. Vijidudu vinapozaliana kiasi hicho na umbo na hali ya chakula kubadilika, tunasema kimeoza. Chakula kilichooza huhifadhi sumu kali iliyotengenezwa na vijidudu, hivyo kukila husababisha maumivu makali ya tumbo, kuhara na kichefuchefu, na kuharibu mwili wako." },
  { id:7, topic:"Chakula", emoji:"👃",
    question:"Dalili ya kuwa chakula kimeharibika ni ipi?",
    choices:["Harufu au ladha ya ajabu","Rangi nyekundu","Kitu cha baridi","Kitu kilichopikwa vizuri"],
    answerIndex:0,
    explanation:"Unaweza kutumia pua na ulimi wako kuchunguza kama chakula kimeharibika na hakiko salama tena. Kikiwa na harufu ya uchachu isiyo ya kawaida au harufu kali mbaya, au ladha ya ajabu ukiweka kidogo mdomoni, au kikiwa kinata na kuvuta nyuzi, hiyo ni ishara kwamba vijidudu vimezaliana sana na sumu imetokea. Ukijilazimisha kula kwa sababu si vyema kutupa, unahatarisha maisha yako kwa sumu kali ya chakula. Harufu au ladha ikiwa ya shaka hata kidogo, amua kukitupa na usimeze kamwe." },
  { id:8, topic:"Chakula", emoji:"🪰",
    question:"Ufanye nini na chakula ambacho nzi ametua juu yake?",
    choices:["Kula kama kilivyo","Usile sehemu aliyogusa nzi (itupe)","Kufuga nzi","Kukitazama tu"],
    answerIndex:1,
    explanation:"Mdudu tunayemwita nzi hupenda kutembea mahali pachafu sana penye vijidudu vingi, kama kinyesi cha wanyama, mizoga na madampo ya taka. Kwa hiyo vijidudu vinavyosababisha magonjwa ya kutisha hugandama kwenye miguu yake myembamba na mwili. Nzi kama huyo anapotua kwenye chakula chetu, papo hapo vijidudu vya miguuni mwake huhamia chakulani. Ukila sehemu aliyogusa, unaingiza mdomoni mwako bila kujua vijidudu vya kinyesi na taka, jambo linaloweza kusababisha ugonjwa mkubwa. Hata ionekane hasara, ni salama zaidi kukata na kutupa sehemu ya chakula nzi aliyotua." },
  { id:9, topic:"Kuzuia magonjwa", emoji:"🦟",
    question:"Ukiacha maji yamesimama kwa muda mrefu kunatokea nini?",
    choices:["Maji yanakuwa safi","Mbu hatari wanazaliana sana","Pesa zako zinaongezeka","Hakuna kinachotokea"],
    answerIndex:1,
    explanation:"Maji ya zamani yanayobaki mahali pamoja bila kutiririka huwa mahali bora kwa mdudu aitwaye mbu kutaga mayai yake. Ukiacha ndoo, matairi ya zamani au makopo matupu yenye maji karibu na uwanja au nyumba yako, huko huzaliwa mbu wapya mamia na maelfu wanaoruka kila mahali. Mbu anaponyonya damu ya mtu, huingiza mwilini vijidudu vya magonjwa hatari sana yanayoua kama malaria na dengue. Kuondoa madimbwi ya maji karibu na nyumba ni mpango muhimu wa kulinda familia dhidi ya magonjwa haya ya kutisha." },
  { id:10, topic:"Usafi", emoji:"✋",
    question:"Kucha zikiwa ndefu, ndani yake hujikusanya nini?",
    choices:["Mikono inakuwa na nguvu","Uchafu mweusi na vijidudu hujikusanya chini ya kucha","Chakula kinakuwa kitamu zaidi","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Kucha zinapokuwa ndefu, matope na uchafu mweusi hujaa kwenye nafasi nyembamba kati ya ukucha na ngozi unapocheza udongoni, unaposaidia au unapofanya kazi. Uchafu unaoingia nafasi hiyo hautoki kwa urahisi kwa kunawa mikono kwa kawaida, na huwa mahali bora pa kujificha kwa vijidudu. Kwa kucha ndefu, unapokula kwa mikono au unapogusa uso wako au jeraha, vijidudu hivyo vilivyojificha huingia mwilini kwa urahisi. Kukata kucha ziwe fupi kila wakati ni njia ya msingi ya kuzuia magonjwa." },
  { id:11, topic:"Adabu za kukohoa", emoji:"🤧",
    question:"Ufanye nini unapokohoa au kupiga chafya?",
    choices:["Kufanya kuelekea uso wa mtu","Kufunika mdomo na pua kwa mkono au mkono wa nguo","Kupiga kelele","Kutofanya chochote"],
    answerIndex:1,
    explanation:"Unapokuwa na mafua au ugonjwa wa mapafu, kukohoa au kupiga chafya mara moja tu hurusha matone madogo ya maji yasiyoonekana kutoka mdomoni na puani, mita kadhaa mbali kwa nguvu. Kila tone laweza kuwa na vijidudu vya magonjwa elfu kadhaa. Ukikohoa kuelekea uso wa mtu, unamwambukiza moja kwa moja, na usipofunika chochote, vijidudu husambaa hewani na kila mtu chumbani humo anaweza kuugua. Unapokohoa, kufunika vizuri mdomo na pua kwa mkono wa nguo au mkono hukuzuia kueneza ugonjwa kwa familia na marafiki wapendwa wanaokuzunguka." },
  { id:12, topic:"Usafi", emoji:"🗑️",
    question:"Ukiacha taka zimetupwa karibu na nyumba kunatokea nini?",
    choices:["Nyumba inakuwa safi","Panya na wadudu hatari hujikusanya na ugonjwa husambaa","Taka zinakuwa maua","Hakuna tatizo"],
    answerIndex:1,
    explanation:"Ukitupa mabaki ya chakula na taka karibu kabisa na nyumba yako, harufu huvutia viumbe vingi kama panya, nzi na mende. Viumbe hawa kwa kawaida hutembea kwenye mifereji ya maji machafu na sehemu chafu, hivyo hubeba vijidudu vingi vya magonjwa ya kutisha mwilini. Wanapoongezeka kuzunguka taka, hatimaye huingia ndani ya nyumba na kuchafua chakula na maji ya kunywa yaliyo ndani. Taka lazima zitupwe mahali maalum mbali vya kutosha na nyumba, au zifukiwe ndani ya shimo refu ardhini." },
  { id:13, topic:"Meno yenye afya", emoji:"🪥",
    question:"Sababu kuu ya kupiga mswaki ni ipi?",
    choices:["Kupaka meno rangi nyeupe","Kupunguza vijidudu vya kuoza meno mdomoni na kulinda meno","Kuimarisha taya","Kushibisha tumbo"],
    answerIndex:1,
    explanation:"Baada ya kula, mabaki madogo ya chakula hubaki daima kwenye nafasi na uso wa meno. Viumbe visivyoonekana viitwavyo vijidudu vya kuoza meno, vinavyoishi mdomoni mwetu, hupenda sana mabaki hayo. Ukiyaacha pale, vijidudu hivyo huyala na kutengeneza asidi kali inayoyeyusha meno. Kwa sababu ya asidi hiyo, mashimo hutokea polepole kwenye meno, ambayo yanapaswa kuwa sehemu ngumu zaidi ya mwili, na yanapofika kwenye neva huleta maumivu makali kiasi kwamba huwezi kulala usiku. Kupiga mswaki baada ya kula ni kazi ya lazima kabisa ili kuondoa chakula cha vijidudu na kulinda meno yako." },
  { id:14, topic:"Kuzuia majeraha", emoji:"👟",
    question:"Kwa nini uvae viatu unapotembea nje?",
    choices:["Ili miguu ikue","Ili kuzuia minyoo na vijidudu vya udongoni visiingie kupitia ngozi ya miguu","Ili kufanya mazoezi ya kukimbia","Ili nguo zisichafuke"],
    answerIndex:1,
    explanation:"Unapotembea bila viatu juu ya udongo na matope, viumbe vidogo sana vilivyojificha ardhini visivyoonekana (lava za minyoo ya vimelea) na vijidudu vinaweza kutoboa ngozi laini ya nyayo zako na kuingia mwilini vyenyewe. Minyoo inayoingia hujikita tumboni (matumbo) na kuiba lishe unayokula, ikikufanya uwe na upungufu mkubwa wa damu, kusimamisha ukuaji wako na kukunyima nguvu. Kuvaa viatu pia hukulinda dhidi ya majeraha makubwa ya kukanyaga vipande vya glasi, mawe makali au miiba. Vaa viatu au kandambili kila unapotoka nje." },
  { id:15, topic:"Usafi", emoji:"👕",
    question:"Ukiendelea kuvaa nguo chafu kunatokea nini?",
    choices:["Nguo zinakuwa imara","Ngozi inawasha au unaugua","Mwili unakuwa na nguvu","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Ukiendelea kuvaa nguo zenye jasho au zilizochafuliwa na matope kwa siku nyingi, ukungu na vijidudu hula jasho la binadamu na mafuta ya ngozi yaliyo kwenye nguo na kuzaliana sana ndani ya nyuzi zake. Kwa kuwa nguo hizo chafu husuguana na ngozi yako wakati wote, ngozi inaweza kuvimba jekundu, kuwasha sana, au kupata ugonjwa wenye vidonda vinavyotoa usaha. Nguo chafu zinaweza kuondolewa vijidudu kabisa kwa kuzifua vizuri kwa maji na sabuni na kuzikausha vizuri juani (miale ya urujuanimno). Kuvaa nguo safi daima ni muhimu ili kulinda ngozi yako." },
  { id:16, topic:"Usafi", emoji:"🚿",
    question:"Kuoga mwili kuna faida gani?",
    choices:["Ngozi inakuwa safi na unazuia magonjwa ya ngozi","Unakuwa mrefu","Nywele zinapukutika","Unasikia njaa"],
    answerIndex:0,
    explanation:"Kila siku ngozi ya binadamu hutoa mafuta yasiyoonekana (sebamu) na jasho, na vumbi na udongo wa nje huchanganyika, ukichafua mwili mzima. Ukiacha uchafu huu kwa siku nyingi, vijidudu vibaya huzaliana juu ya ngozi, na unaweza kupata majipu mabaya au ugonjwa wa kutisha ambapo ngozi hupata vidonda na kuoza. Kwa kuoga mwili mzima kwa upole mara kwa mara, kwa maji na sabuni, na kuondoa mafuta na uchafu wa zamani, ngozi yako hubaki na afya na nguvu, ikitengeneza kinga imara inayozuia ugonjwa usiingie kutoka nje." },
  { id:17, topic:"Maji salama", emoji:"💧",
    question:"Ukiwa na maji yenye matope tu, unaweza kuyanywa salama vipi?",
    choices:["Kuyanywa kama yalivyo","Kuchuja matope kwa kitambaa au mchanga, kisha kuyachemsha motoni","Kuyaweka juani tu kisha kunywa","Kunywa kidogo tu"],
    answerIndex:1,
    explanation:"Unapoweza kupata maji yenye matope tu, kuyanywa kama yalivyo huingiza mwilini mwako vijidudu vingi sana pamoja na matope na husababisha ugonjwa mkubwa. Kuyafanya salama kunahitaji hekima mbili. Kwanza, pitisha maji kwenye kitambaa safi chenye matundu madogo, au chombo kilichojaa mchanga na kokoto ndogo, ili kuchuja matope na uchafu mkubwa na kufanya maji yawe safi. Lakini kuwa safi pekee hakutoshi; vijidudu visivyoonekana bado vi hai. Baada ya hapo, lazima uyaweke motoni na kuyachemsha sana hadi yatoe mapovu, ili joto liangamize vijidudu na hatimaye yawe maji salama ya kunywa. Kwa hekima, unaweza kutengeneza maji yanayookoa maisha hata kutoka maji yenye matope." },
  { id:18, topic:"Watoto wachanga", emoji:"🍼",
    question:"Lishe bora zaidi kwa mtoto mchanga ni ipi?",
    choices:["Maziwa ya ng'ombe (mabichi)","Maziwa ya mama (kunyonyesha)","Maji ya mto","Maji ya sukari"],
    answerIndex:1,
    explanation:"Mwili wa mtoto mchanga aliyezaliwa karibuni ni dhaifu sana na hauna karibu nguvu yoyote ya kushinda vijidudu vya magonjwa. Maziwa ya mama (kunyonyesha) hayana tu lishe kamili kwa mtoto kukua, bali pia kiasi kikubwa cha kiungo maalum cha kinga kiitwacho kinga ya mwili (immunity), kinachomlinda dhidi ya magonjwa. Pia, maziwa ya mama hutoka moja kwa moja mwilini, hivyo hayagusi kamwe maji machafu ya nje wala vijidudu vya vyombo; ni safi na salama zaidi duniani. Maziwa mabichi ya wanyama wengine, maji ya mto au maji ya sukari yanaweza kuharibu tumbo na matumbo dhaifu ya mtoto na kuchukua maisha yake, hivyo usiwahi kumpa." },
  { id:19, topic:"Kuzuia magonjwa", emoji:"😷",
    question:"Karibu na mtu anayekohoa sana ufanye nini?",
    choices:["Kuwa mbali kidogo, na kugeuza uso unapopita","Kuvuta pumzi kwa nguvu mbele yake","Kupeana mkono naye","Kusimama mbele yake kabisa"],
    answerIndex:0,
    explanation:"Magonjwa hatari ya kupumua kama kifua kikuu (TB) huelea hewani kwa muda mrefu, yakibebwa na matone madogo yasiyoonekana yanayotawanyika mtu mgonjwa anapokohoa. Ukivuta pumzi kwa nguvu karibu, au ukikaa karibu kwa muda mrefu, unavuta vijidudu hivyo ndani zaidi ya mapafu yako na unaweza kupata ugonjwa huo huo hatari. Mtu anapokohoa sana, si suala la ukatili wala kumtenga; bali ili kujilinda, kaa umbali wa mita kadhaa, na unapopita geuza uso na utoe pumzi taratibu; hivyo ndivyo nyote wawili mnavyojilinda." },
  { id:20, topic:"Hewa safi", emoji:"🪟",
    question:"Unawezaje kuweka hewa ya chumba safi?",
    choices:["Kufunga milango na madirisha yote vizuri","Kufungua madirisha na milango ili kubadilisha hewa","Kila mtu apige kelele pamoja","Hakuna kinachobadilika"],
    answerIndex:1,
    explanation:"Watu wengi wanapokusanyika katika chumba kidogo kilichofungwa, vijidudu na virusi vya magonjwa anavyobeba mtu fulani hujikusanya zaidi na zaidi hewani, hadi hewa ya chumba ijae vijidudu. Ukikaa muda mrefu katika chumba hicho, kila mtu huvuta hewa chafu na kuugua pamoja (maambukizi ya kikundi). Kwa kufungua madirisha na milango sehemu mbili au zaidi ili kubadilisha hewa safi ya nje na hewa chafu ya chumbani (kupitisha hewa), unaweza kufukuza vijidudu kutoka hewani na kulinda afya ya kila mtu chumbani." }
];
