/*
 * Wise World - Datos del quiz (Español)
 * ⚠ Traducción por IA desde el original en japonés. Se recomienda la revisión
 *    de un hablante nativo o experto en salud antes de usarla.
 * Mantén id / answerIndex / emoji iguales en todos los idiomas.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).es = [
  { id:1, topic:"Agua segura", emoji:"💧",
    question:"¿Qué agua es segura y no te hará doler la barriga?",
    choices:["Agua de río","Agua de pozo","Agua hervida bien al fuego","Agua de lluvia"],
    answerIndex:2,
    explanation:"El agua de río, de pozo y de lluvia puede verse perfectamente clara y limpia, pero puede estar llena de seres vivos diminutos que nuestros ojos no pueden ver (gérmenes y virus). Si bebes esa agua tal cual, puede causar un fuerte dolor de estómago o una enfermedad grave que ponga en peligro la vida. Pero cuando pones el agua al fuego y la hierves fuerte hasta que burbujee, el calor mata todos esos seres dañinos. Por eso, el agua que se ha hervido bien y luego se ha dejado enfriar es la más segura del mundo, y la que puedes beber con confianza." },
  { id:2, topic:"Lavarse las manos", emoji:"🧼",
    question:"¿Qué debes hacer antes de comer?",
    choices:["Lavarte las manos con agua y jabón","Limpiarte las manos en la ropa","No hacer nada","Tocar la tierra"],
    answerIndex:0,
    explanation:"Nuestras manos tocan muchos objetos y el suelo cada día, así que sin darnos cuenta recogen muchos gérmenes invisibles. Si tocas la comida con esas manos, los gérmenes pasan a la comida y los tragas dentro de tu cuerpo junto con ella. Limpiarte las manos en ropa sucia, o solo mojarlas con agua, no quita los gérmenes: se quedan pegados. Solo usando jabón y frotando las palmas, el dorso de las manos y entre los dedos con buena espuma, y luego enjuagando con agua, puedes de verdad eliminar los gérmenes." },
  { id:3, topic:"Lavarse las manos", emoji:"🚽",
    question:"¿Qué debes hacer después de ir al baño?",
    choices:["Ir a jugar enseguida","Lavarte las manos con agua y jabón","Frotarte las manos en la ropa","Secarte las manos en el pantalón"],
    answerIndex:1,
    explanation:"Después de ir al baño, en tus manos se pegan con facilidad gérmenes muy fuertes de las heces y la orina que causan enfermedades. Si vas a jugar sin lavarte, esos gérmenes pasan a las manijas y juguetes que tocas, y contagian la enfermedad al siguiente amigo o familiar que los toque. Y si te tocas la boca o los ojos con esas manos, también puedes enfermarte tú. Por mucha prisa que tengas, lavarte siempre bien las manos con agua y jabón después del baño es una regla que protege tu vida y la de quienes te rodean." },
  { id:4, topic:"Salud", emoji:"💧",
    question:"Cuando tu barriga está mal y las heces se vuelven aguadas (diarrea), ¿qué es lo más importante?",
    choices:["Comer mucha comida","No beber nada","Beber bastante agua segura","Correr y jugar"],
    answerIndex:2,
    explanation:"Cuando tu barriga está mal y salen heces aguadas (diarrea) una y otra vez, tu cuerpo pierde agua y nutrientes valiosos sin parar. Esto se llama deshidratación. Cuando al cuerpo le falta agua, las funciones importantes que nos mantienen vivos empiezan a fallar, y los niños pequeños sobre todo pueden perder la vida de repente. Cuando tienes diarrea, en vez de forzarte a comer alimentos sólidos, lo mejor es primero reponer el agua que has perdido. Bebiendo agua segura, hervida y enfriada, poco a poco y muchas veces, puedes mantener tus fuerzas y proteger tu vida." },
  { id:5, topic:"Curar heridas", emoji:"🩹",
    question:"Cuando te caes y sangras, ¿qué debes hacer primero?",
    choices:["Ponerle tierra","Lavarla bien con agua limpia","Dejarla sin hacer nada","Frotarla con una hoja"],
    answerIndex:1,
    explanation:"Cuando te caes y te haces una herida que sangra, la herida queda cubierta de tierra, barro y polvo del suelo, junto con muchos gérmenes. Si crees en viejos dichos y le untas tierra, la frotas con una hoja sucia o la dejas así, los gérmenes entran profundo en la herida y se multiplican. Entonces la herida se hincha roja y duele mucho, y en el peor caso un brazo o una pierna puede pudrirse y dejar de moverse. Cuando te lastimas, el primer paso correcto para que la herida no se vuelva grave es usar agua limpia y segura para enjuagar con fuerza el barro y la suciedad de la herida." },
  { id:6, topic:"Alimentos", emoji:"🦠",
    question:"¿Qué pasa cuando la comida se pudre (se echa a perder)?",
    choices:["Se vuelve sabrosa","Se pudre y te da dolor de barriga","Se vuelve dura","No cambia nada"],
    answerIndex:1,
    explanation:"La comida contiene de forma natural una pequeña cantidad de microbios invisibles desde el principio. En un lugar fresco los microbios no pueden activarse, pero si dejas la comida mucho tiempo en un lugar cálido y caluroso, se vuelve el ambiente perfecto para ellos, y en pocas horas se multiplican hasta millones, una cantidad aterradora. Cuando los microbios se multiplican tanto y la forma y la naturaleza de la comida cambian, decimos que se ha podrido. La comida podrida guarda el fuerte veneno que han hecho los microbios, así que comerla provoca fuerte dolor de estómago, diarrea y náuseas, y daña tu cuerpo." },
  { id:7, topic:"Alimentos", emoji:"👃",
    question:"¿Cuál es una señal de que la comida se ha echado a perder?",
    choices:["Un olor o sabor raro","Un color rojo","Algo frío","Algo bien cocido"],
    answerIndex:0,
    explanation:"Puedes usar tu propia nariz y lengua para comprobar si la comida se ha echado a perder y ya no es segura. Si tiene un olor agrio raro o un olor fuerte y desagradable, o un sabor extraño cuando pruebas un poco, o si está pegajosa y hace hilos, eso es prueba de que los gérmenes se han multiplicado mucho y se ha formado veneno. Si te fuerzas a comerla porque sería un desperdicio, pones tu vida en peligro por una fuerte intoxicación. Si el olor o el sabor son aunque sea un poco sospechosos, decide tirarla y nunca la tragues." },
  { id:8, topic:"Alimentos", emoji:"🪰",
    question:"¿Qué debes hacer con la comida en la que se ha posado una mosca?",
    choices:["Comerla tal cual","No comer la parte que tocó la mosca (tirarla)","Criar la mosca","Quedarte mirándola"],
    answerIndex:1,
    explanation:"El insecto que llamamos mosca gusta de caminar por lugares muy sucios y llenos de gérmenes, como excrementos de animales, cadáveres y basureros. Por eso, en sus patitas finas y su cuerpo se pegan gérmenes que causan enfermedades terribles. Cuando una mosca así se posa en nuestra comida, en ese instante los gérmenes de sus patas pasan a la comida. Si comes el lugar que tocó, estás metiendo en tu boca, de forma indirecta, gérmenes de excrementos y basura, lo que puede causar una enfermedad grave. Aunque parezca un desperdicio, es más seguro cortar y tirar la parte de la comida donde se posó la mosca." },
  { id:9, topic:"Prevenir enfermedades", emoji:"🦟",
    question:"¿Qué pasa si dejas agua estancada mucho tiempo?",
    choices:["El agua se vuelve limpia","Se multiplican mosquitos dañinos","Crece tu dinero","No pasa nada"],
    answerIndex:1,
    explanation:"El agua vieja que se queda en un solo lugar sin correr se vuelve el sitio perfecto para que el insecto llamado mosquito ponga sus huevos. Si dejas baldes, llantas viejas o latas vacías con agua alrededor de tu patio o casa, allí nacen cientos y miles de mosquitos nuevos que vuelan por todas partes. Cuando un mosquito chupa la sangre de una persona, le inyecta en el cuerpo los gérmenes de enfermedades muy temibles y mortales como la malaria y el dengue. Quitar los charcos de agua alrededor de la casa es un plan importante para proteger a tu familia de estas terribles enfermedades." },
  { id:10, topic:"Limpieza", emoji:"✋",
    question:"Cuando tienes las uñas largas, ¿qué se acumula dentro?",
    choices:["Tus manos se hacen más fuertes","Suciedad negra y gérmenes se juntan bajo las uñas","La comida sabe mejor","No cambia nada"],
    answerIndex:1,
    explanation:"Cuando las uñas crecen largas, barro y suciedad negros se meten apretados en el hueco estrecho entre la uña y la piel mientras juegas en la tierra, ayudas o trabajas. La suciedad que entra en ese hueco no sale fácil con un lavado normal de manos, y se vuelve el escondite perfecto para los gérmenes. Con las uñas largas, cuando comes con las manos o te tocas la cara o una herida, esos gérmenes escondidos entran fácil en tu cuerpo. Mantener las uñas siempre cortas es una forma básica de prevenir enfermedades." },
  { id:11, topic:"Al toser", emoji:"🤧",
    question:"¿Qué debes hacer cuando toses o estornudas?",
    choices:["Hacerlo hacia la cara de alguien","Cubrirte la boca y la nariz con la mano o la manga","Gritar fuerte","No hacer nada"],
    answerIndex:1,
    explanation:"Cuando tienes un resfriado o una enfermedad del pulmón, una sola tos o estornudo lanza gotitas de agua invisibles desde tu boca y nariz, a varios metros con gran fuerza. Cada gotita puede contener decenas de miles de gérmenes de enfermedad. Si toses hacia la cara de alguien, le contagias directamente, y si no te cubres, los gérmenes se esparcen por el aire y todos en la misma sala pueden enfermarse. Cuando toses, cubrirte bien la boca y la nariz con la manga o la mano evita que contagies a la querida familia y amigos que te rodean." },
  { id:12, topic:"Limpieza", emoji:"🗑️",
    question:"¿Qué pasa si dejas basura tirada cerca de la casa?",
    choices:["La casa se pone limpia","Se juntan ratas e insectos dañinos y se propaga la enfermedad","La basura se vuelve flores","No pasa nada malo"],
    answerIndex:1,
    explanation:"Si tiras restos de comida y basura justo al lado de tu casa, el olor atrae a muchos seres como ratas, moscas y cucarachas. Estos seres suelen caminar por alcantarillas y lugares sucios, así que llevan en el cuerpo muchos gérmenes que causan enfermedades temibles. Al aumentar alrededor de la basura, terminan entrando en la casa y ensucian la comida y el agua de beber que hay dentro. La basura debe tirarse en un sitio fijo lo bastante lejos de la casa, o enterrarse hondo en un hoyo en la tierra." },
  { id:13, topic:"Dientes sanos", emoji:"🪥",
    question:"¿Cuál es la razón principal para cepillarte los dientes?",
    choices:["Pintar los dientes de blanco","Reducir los gérmenes de caries en la boca y proteger los dientes","Fortalecer la mandíbula","Llenar el estómago"],
    answerIndex:1,
    explanation:"Después de comer, siempre quedan pequeños restos de comida en los huecos y la superficie de los dientes. Los seres invisibles llamados gérmenes de caries que viven en nuestra boca adoran esos restos. Si los dejas ahí, los gérmenes de caries se alimentan de ellos y producen un ácido fuerte que disuelve los dientes. Por ese ácido, poco a poco se abren agujeros en los dientes, que deberían ser la parte más dura del cuerpo, y cuando llega al nervio provoca un dolor tan fuerte que no puedes dormir de noche. Cepillarte los dientes después de comer es un trabajo del todo necesario para quitar el alimento de los gérmenes y proteger tus dientes." },
  { id:14, topic:"Prevenir heridas", emoji:"👟",
    question:"¿Por qué usas zapatos cuando caminas afuera?",
    choices:["Para que tus pies crezcan más","Para impedir que gusanos y gérmenes de la tierra entren por la piel de tus pies","Para practicar correr","Para no ensuciar la ropa"],
    answerIndex:1,
    explanation:"Cuando caminas descalzo sobre tierra y barro, seres diminutos escondidos en el suelo que no se pueden ver (las larvas de parásitos) y gérmenes pueden atravesar la piel blanda de las plantas de tus pies y entrar solos en tu cuerpo. Los gusanos que entran se instalan en tu barriga (los intestinos) y roban los nutrientes que comes, dejándote muy anémico, deteniendo tu crecimiento y quitándote la energía. Usar zapatos también te protege de heridas graves por pisar vidrios rotos, piedras filosas o espinas de madera. Usa siempre zapatos o sandalias cuando salgas afuera." },
  { id:15, topic:"Limpieza", emoji:"👕",
    question:"¿Qué pasa si sigues usando ropa sucia?",
    choices:["La ropa se hace más fuerte","Te pica la piel o te enfermas","Tu cuerpo se hace más fuerte","No cambia nada"],
    answerIndex:1,
    explanation:"Si sigues usando ropa empapada de sudor o manchada de barro durante muchos días, el moho y los gérmenes se alimentan del sudor y la grasa de la piel que hay en la ropa y se multiplican muchísimo dentro de las fibras. Como esa ropa sucia roza tu piel todo el tiempo, la piel puede hincharse roja, picar mucho o desarrollar una enfermedad con llagas que supuran. La ropa sucia puede quedar libre de gérmenes lavándola bien con agua y jabón y secándola bien al sol (los rayos ultravioleta). Usar siempre ropa limpia es importante para proteger la barrera de tu piel." },
  { id:16, topic:"Limpieza", emoji:"🚿",
    question:"¿Qué tiene de bueno lavarte el cuerpo?",
    choices:["La piel se limpia y previenes enfermedades de la piel","Creces más alto","Se te cae el pelo","Te da hambre"],
    answerIndex:0,
    explanation:"Cada día salen de la piel humana grasa invisible (sebo) y sudor, y se les mezclan el polvo y la tierra de afuera, ensuciando todo el cuerpo. Si dejas esta suciedad muchos días, los gérmenes malos se multiplican en la superficie de la piel, y puedes tener terribles forúnculos o una enfermedad temible en la que la piel se llaga y se pudre. Lavando con regularidad todo el cuerpo con suavidad, con agua y jabón, y quitando la grasa y la suciedad viejas, tu piel se mantiene sana y fuerte, formando una barrera poderosa que impide que la enfermedad entre desde afuera." },
  { id:17, topic:"Agua segura", emoji:"💧",
    question:"Cuando solo tienes agua con barro, ¿cómo puedes beberla con seguridad?",
    choices:["Beberla tal cual","Filtrar el barro con tela o arena y luego hervirla al fuego","Solo dejarla al sol y beberla","Beber solo un poco"],
    answerIndex:1,
    explanation:"Cuando lo único que consigues es agua con barro, beberla tal cual mete en tu cuerpo una enorme cantidad de gérmenes junto con el barro y causa una enfermedad grave. Hacerla segura requiere dos saberes. Primero, pasa el agua por una tela limpia y fina, o por un recipiente lleno de arena y piedritas, para filtrar el barro y los trozos grandes y dejar el agua clara. Pero estar clara no basta: los gérmenes invisibles siguen vivos. Después, debes ponerla al fuego y hervirla fuerte hasta que burbujee, para que el calor elimine los gérmenes y por fin se vuelva agua segura para beber. Con sabiduría, puedes hacer agua que salva vidas incluso del agua con barro." },
  { id:18, topic:"Bebés", emoji:"🍼",
    question:"¿Cuál es el mejor alimento para un bebé?",
    choices:["Leche de vaca (cruda)","La leche de la madre (leche materna)","Agua de río","Agua con azúcar"],
    answerIndex:1,
    explanation:"El cuerpo de un bebé recién nacido es muy débil y casi no tiene fuerza para vencer a los gérmenes de las enfermedades. La leche de la madre (leche materna) no solo contiene el alimento perfecto para que el bebé crezca, sino también grandes cantidades de un componente protector especial llamado inmunidad que lo defiende de las enfermedades. Además, la leche materna sale directo del cuerpo, así que nunca toca agua sucia de afuera ni gérmenes de los recipientes: es la más limpia y segura del mundo. La leche cruda de otros animales, el agua de río o el agua con azúcar pueden arruinar el delicado estómago e intestino del bebé y quitarle la vida, así que nunca debes dárselos." },
  { id:19, topic:"Prevenir enfermedades", emoji:"😷",
    question:"¿Qué debes hacer cerca de alguien con una tos fuerte?",
    choices:["Mantener algo de distancia y girar la cara al pasar","Respirar hondo frente a esa persona","Darle la mano","Pararte justo frente a ella"],
    answerIndex:0,
    explanation:"Las enfermedades respiratorias graves como la tuberculosis flotan en el aire mucho tiempo, llevadas por las diminutas gotitas invisibles que se dispersan cuando una persona enferma tose. Si respiras hondo cerca, o te quedas cerca mucho tiempo, metes esos gérmenes en lo profundo de tus pulmones y puedes contraer la misma enfermedad grave. Cuando alguien tiene una tos fuerte, no se trata de ser cruel ni de tratarlo distinto; para protegerte, mantén varios metros de distancia, y al pasar gira la cara y exhala con suavidad: así es como ambos se cuidan." },
  { id:20, topic:"Aire fresco", emoji:"🪟",
    question:"¿Cómo mantienes limpio el aire de una habitación?",
    choices:["Cerrar bien todas las puertas y ventanas","Abrir ventanas y puertas para cambiar el aire","Que todos griten fuerte juntos","No cambia nada"],
    answerIndex:1,
    explanation:"Cuando mucha gente se junta en una habitación pequeña y cerrada, los gérmenes y virus que alguien lleva se acumulan cada vez más en el aire, hasta que el aire de la sala se llena de gérmenes. Si te quedas mucho tiempo en esa sala, todos respiran el aire sucio y se enferman juntos (un contagio en grupo). Abriendo ventanas y puertas en dos o más lugares para cambiar el aire fresco de afuera por el aire sucio de la sala (ventilar), puedes echar los gérmenes fuera del aire y proteger la salud de todos los que están en la habitación." },
  { id:21, topic:"Palancas", emoji:"🪨",
    question:"Cuando quieres mover una piedra pesada enterrada en el suelo con una palanca larga, ¿dónde debes empujar con más fuerza para moverla con el menor esfuerzo?",
    choices:["En el punto justo al lado de la piedra","En el medio de la palanca","En el extremo más lejano de la palanca, lejos de la piedra","Es igual donde sea que empujes"],
    answerIndex:2,
    explanation:"Cuando mueves algo pesado con una palanca, existe una regla llamada principio de la palanca: cuanto más lejos estés de la pequeña piedra que sirve de apoyo (el punto de apoyo), menos fuerza necesitas. Si empujas cerca de la piedra, la palanca no se mueve, pero si agarras el extremo más lejano de la palanca y empujas cargando tu peso, puedes levantar una piedra pesada con una fuerza sorprendentemente pequeña. Conocer cómo funciona una herramienta así te permite multiplicar muchas veces tu propia fuerza y realizar trabajos pesados con facilidad." },
  { id:22, topic:"Palancas", emoji:"⚖️",
    question:"Cuando levantas una carga pesada con una palanca larga, ¿dónde debes colocar la pequeña piedra (el punto de apoyo) que sostiene la palanca para que se levante más fácilmente?",
    choices:["Justo al lado de la carga pesada","Justo al lado de donde tú aplicas la fuerza","Exactamente en el medio de la palanca","Es mejor no colocar ninguna piedra"],
    answerIndex:0,
    explanation:"Cuando levantas algo pesado con una palanca, la posición de la pequeña piedra de apoyo (el punto de apoyo) es muy importante. Al colocar este apoyo justo al lado de la carga pesada, la carga se mueve solo una corta distancia, pero la fuerza que necesitas para levantarla se vuelve muchísimo menor. Al revés, si la piedra de apoyo está cerca de ti, por mucho que empujes no podrás levantar la carga. Cuando quieras mover algo pesado, recuerda la sabiduría de colocar el apoyo cerca de la cosa que quieres mover." },
  { id:23, topic:"Rodar", emoji:"🪵",
    question:"Cuando mueves una caja de madera pesada arrastrándola por el suelo, ¿cómo puedes moverla más fácilmente con el menor esfuerzo?",
    choices:["Poner varios troncos redondos y duros debajo de la caja y hacerla rodar","Tirar de ella con todas tus fuerzas tal cual","Echar agua encima de la caja","Golpear la caja con fuerza contra el suelo"],
    answerIndex:0,
    explanation:"Cuando arrastras algo pesado directamente por el suelo, actúa con fuerza un freno llamado fricción, que se produce donde el objeto roza contra el suelo, así que mover la caja requiere muchísima fuerza. Pero si pones troncos redondos y duros debajo de la caja, el movimiento deja de ser arrastrar y pasa a ser que los troncos ruedan. Rodar tiene decenas de veces menos fuerza de freno que arrastrar, así que hasta una sola persona puede mover una carga pesada con suavidad. Cuando la carga avanza, tomas los troncos que quedan atrás y los vuelves a poner delante, una sabiduría que la humanidad usa desde tiempos antiguos." },
  { id:24, topic:"Rampas", emoji:"🛝",
    question:"Cuando quieres subir una carga pesada a una plataforma alta, de la altura del pecho de un adulto, ¿cuál es la forma de moverla que menos esfuerza tu cuerpo?",
    choices:["Ponerte frente a la plataforma y levantarla recto hacia arriba con todas tus fuerzas","Apoyar una tabla larga inclinada contra la plataforma para hacer una rampa y empujarla hacia arriba","Lanzar la carga contra la plataforma desde lejos","Rebajar la altura de la plataforma para hacerla más baja"],
    answerIndex:1,
    explanation:"Si intentas levantar una carga pesada recto hacia arriba, te enfrentas de lleno a la fuerza que tira de las cosas hacia la tierra (la gravedad), así que debes sostenerlo todo solo con tus músculos, lo que daña tu espalda y tus brazos. Aquí, si apoyas una tabla larga inclinada contra la plataforma para hacer una rampa (un plano inclinado), la tabla pasa a sostener la mayor parte del peso de la carga. Al subir una rampa, la distancia que caminas se hace más larga, pero la fuerza necesaria para empujar la carga puede reducirse a menos de la mitad. Cuando lleves cosas a un lugar alto, busca siempre la manera de hacer una rampa." },
  { id:25, topic:"Poleas", emoji:"🪣",
    question:"Cuando subes con una cuerda un cubo pesado lleno de agua desde un pozo profundo, ¿qué se vuelve más fácil si colocas en la barra de arriba del pozo una rueda redonda que gira (una polea) y pasas la cuerda por ella?",
    choices:["El peso del agua se vuelve la mitad de ligero","La cantidad de agua aumenta por sí sola","Puedes subir el agua solo tirando de la cuerda hacia abajo","La cuerda nunca se romperá"],
    answerIndex:2,
    explanation:"Cuando pasas una cuerda por la rueda redonda de arriba del pozo (una polea fija), en realidad el peso del agua no se vuelve más ligero. Pero lo maravilloso de esta herramienta es que cambia la dirección en la que aplicas la fuerza. Si intentas subir la cuerda recta hacia arriba, debes levantarla solo con la fuerza de tus brazos y tu espalda; pero si pasas la cuerda por la rueda redonda y tiras hacia abajo, puedes poner todo el peso de tu cuerpo sobre la cuerda. Poder usar tu propio peso para subir agua pesada con facilidad y seguridad es la sabiduría de esta rueda redonda." },
  { id:26, topic:"Torno y eje", emoji:"🔄",
    question:"Cuando quieres girar un tornillo que no hay manera de que gire, o el pesado torno de un pozo, ¿cómo puedes girarlo más fácilmente?",
    choices:["Girarlo usando una barra corta y delgada","Hacer grande y largo el mango y girar ese","Girarlo solo con las puntas de los dedos, sin herramienta","Golpear el tornillo con fuerza con un martillo"],
    answerIndex:1,
    explanation:"Cuando quieres girar un eje que está en el centro, si le colocas un mango redondo grande o una empuñadura larga, puedes crear una gran fuerza de giro con poco esfuerzo. Esto se llama el principio del torno y eje. No puedes mover la parte delgada girándola directamente con los dedos, pero al girar el mango grande de fuera, la distancia que recorre tu mano se hace más larga mientras que la fuerza sobre el eje se vuelve muchas veces mayor. La máquina que enrolla la cuerda de un pozo, el pomo de una puerta en casa, los tornillos de las herramientas; todas las cosas que giran a tu alrededor usan esta sabiduría." },
  { id:27, topic:"Centro de gravedad", emoji:"🏺",
    question:"Hay personas que caminan con destreza llevando una vasija de agua pesada o leña sobre la cabeza. ¿Por qué pueden caminar largas distancias sin lastimarse el cuello ni la espalda?",
    choices:["Porque caminan doblando mucho el cuerpo hacia delante o hacia atrás","Porque mantienen la espalda perfectamente recta y colocan el centro de la carga (su centro de gravedad) justo encima de sus huesos","Porque agitan la carga con fuerza sobre la cabeza todo el tiempo","Porque todos nacen con los huesos del cuello más gruesos que los demás"],
    answerIndex:1,
    explanation:"Cuando llevas una carga pesada en las manos, el esfuerzo recae solo en un lado del cuerpo y tus músculos se cansan rápido. Pero si enderezas la espalda perfectamente y colocas la carga justo encima de la cabeza, el peso del centro de la carga (su centro de gravedad) pasa recto hacia abajo por la columna de huesos, de la cabeza al cuello y a la columna vertebral, y sale hacia el suelo. Como son los huesos firmes, y no los músculos, los que sostienen el peso, puedes llevarla con seguridad largas distancias sin gastar fuerza muscular, siempre que mantengas el equilibrio. Mantener las cosas cerca del eje central de tu cuerpo es una sabiduría importante para no lastimarte." },
  { id:28, topic:"Presión", emoji:"🦶",
    question:"Cuando caminas por un camino embarrado donde, tras la lluvia, se vuelve barro profundo y los pies se hunden, ¿cómo puedes caminar más fácil sin hundirte?",
    choices:["Caminar de puntillas, haciendo las plantas de los pies lo más pequeñas posible","Atar a las plantas de los pies una tabla de madera plana y grande, y caminar","Simplemente gritar fuerte y cruzar corriendo","Cargar mucho equipaje para hacerte más pesado"],
    answerIndex:1,
    explanation:"El peso que recae sobre el suelo se concentra con más fuerza en un punto y se hunde más profundo, como una aguja, cuanto más pequeña es la superficie que lo toca. Esto se llama presión. Ponerte de puntillas hace la superficie más pequeña, así que te hundes aún más. Al revés, si atas a las plantas de los pies una tabla de madera plana y grande, tu peso se reparte sobre una superficie amplia, así que la fuerza que empuja el suelo hacia abajo se debilita y puedes caminar sobre el barro sin hundirte. Hacer ancha y plana la base de un edificio pesado es la misma sabiduría para repartir la presión." },
  { id:29, topic:"Carros", emoji:"🛒",
    question:"Cuando quieres cargar mucho equipaje pesado en un carro de dos ruedas y tirar de él, ¿dónde debes poner las cosas pesadas para que sea lo más ligero y fácil de tirar?",
    choices:["Justo al lado de tus manos, cerca del mango","En el extremo más trasero del carro","Justo encima del eje de las ruedas","Es igual donde sea que lo cargues"],
    answerIndex:2,
    explanation:"Cuando tiras de un carro, el peso sobre tus manos cambia muchísimo según dónde coloques la carga. Si pones el equipaje pesado cerca de tus manos, acabas corriendo mientras levantas el peso de la carga directamente con los brazos, y te cansas rápido. Si está demasiado atrás, el carro se vuelca hacia atrás, lo cual es peligroso. La respuesta correcta es justo encima del eje de las ruedas. Si pones ahí las cosas pesadas, las ruedas firmes y el suelo sostienen todo el peso, así que casi nada de peso recae sobre tus manos. Como solo necesitas la fuerza para tirar hacia delante, puedes transportar una gran carga con mucha facilidad." },
  { id:30, topic:"Filos", emoji:"🔪",
    question:"Cuando afilas el filo de un machete para partir leña, o de un cuchillo de cocina para cortar comida, frotándolo en una piedra (una piedra de afilar), ¿por qué corta mejor?",
    choices:["Porque la punta del filo se vuelve más delgada y fina, y la fuerza se concentra en un solo punto","Porque el filo se calienta y derrite la comida","Porque el filo se vuelve más pesado","Porque el filo se vuelve redondeado"],
    answerIndex:0,
    explanation:"Que algo se corte con un filo ocurre porque la fuerza que aplica una persona se concentra en el punto extremadamente estrecho de la punta del filo y rompe el objeto. Cuando un filo se desgasta y se redondea, la fuerza se reparte sobre una superficie amplia, así que por mucho que empujes no corta. Afilar un filo es el trabajo de desbastar la punta redondeada para hacerla lo más fina y delgada posible. Una vez que la punta es fina, hasta una fuerza pequeña crea una presión enorme en ese punto, así que puedes cortar leña dura o comida con un toque ligero. Cuidar tus herramientas es básico para ahorrar tus energías." },
  { id:31, topic:"Fricción", emoji:"👟",
    question:"Cuando caminas por una cuesta o sobre rocas mojadas, ¿qué resbala menos y es más seguro: unos zapatos lisos y resbaladizos, o unos zapatos con surcos profundos y con púas en la suela?",
    choices:["Zapatos lisos y planos","Zapatos con surcos profundos y con púas en la suela","Es igual cualquiera que uses","Resbalas menos sin zapatos"],
    answerIndex:1,
    explanation:"Cuando la suela de un zapato roza contra el suelo, ahí actúa un freno llamado fricción que evita que resbales. Si la suela es lisa, no actúa ningún freno entre ella y el suelo, y resbalas y te caes con facilidad, sobre todo donde hay agua o barro. Si la suela tiene surcos profundos y con púas, esos surcos se encajan firmemente en las irregularidades del suelo y crean un fuerte freno. Resbalar y caer puede provocar lesiones graves, pero conociendo cómo funciona la fricción, eligiendo zapatos con surcos en suelo resbaladizo o apoyando toda la planta firmemente en el suelo, puedes actuar con seguridad." },
  { id:32, topic:"Flotar", emoji:"⛵",
    question:"Una piedrecita se hunde en el agua, y sin embargo un barco de madera miles de veces más pesado y grande puede flotar sobre el agua. ¿Por qué?",
    choices:["Porque el barco tiene forma de cuenco y guarda mucho aire y agua dentro","Porque al barco le da mucho viento","Porque tiene piedras mágicas pintadas en el fondo","Porque el barco está hecho de un aceite más ligero que el agua"],
    answerIndex:0,
    explanation:"Sobre un objeto dentro del agua actúa una fuerza misteriosa llamada flotabilidad, que lo empuja hacia arriba tanto como el agua que desplaza. La piedrecita está maciza por dentro y es pesada, así que la piedra pesa más que el agua que desplaza, y se hunde. Pero un barco grande tiene forma de cuenco, y dentro guarda mucho aire. Visto en conjunto, se vuelve muy ligero para su tamaño, así que la fuerza del agua que empuja desde abajo se vuelve más fuerte, y hasta un barco grande puede flotar sobre el agua sin volcarse." },
  { id:33, topic:"Triángulos", emoji:"🔺",
    question:"Cuando construyes una casa o un puente de madera o de hierro, ¿por qué armar el esqueleto en forma de triángulos hace un edificio muy resistente y difícil de romper?",
    choices:["Porque necesita más material que un cuadrado","Porque el triángulo tiene la propiedad de que su forma nunca se deforma, aunque se aplique una fuerza fuerte desde arriba","Porque hacer triángulos deja pasar el viento más fácilmente","Porque es una forma antigua usada como amuleto de los dioses"],
    answerIndex:1,
    explanation:"Un edificio hecho de pilares armados solo en cuadrados se derrumba con facilidad, doblándose flojas las uniones, cuando se aplica una fuerza fuerte o el temblor de un terremoto desde arriba o de lado. Pero si añades una barra inclinada dentro de ese cuadrado para hacer un triángulo (una estructura de celosía), entonces venga la fuerza de la dirección que venga, las barras tiran y empujan entre sí y la forma no se deforma en absoluto. Si miras los grandes puentes del mundo, o la parte de abajo de los techos de los edificios, siempre están finamente combinados estos triángulos. Es una sabiduría magnífica de la construcción: aun con poco material, solo ideando la forma puedes hacer algo muchas veces más resistente." },
  { id:34, topic:"Inercia", emoji:"🐎",
    question:"Cuando un caballo o un carro que va corriendo frena de golpe y se para en seco, ¿qué les pasa al equipaje y a las personas que van encima?",
    choices:["Se vuelcan hacia atrás tal cual","Salen disparados hacia delante con fuerza","Saltan recto hacia arriba en el sitio","No pasa nada; se paran en seco también"],
    answerIndex:1,
    explanation:"En el universo existe una fuerza misteriosa llamada inercia: una cosa en movimiento trata de seguir moviéndose a la misma velocidad. Aunque el caballo o el carro se paren de repente, las personas y el equipaje que van encima todavía tratan de seguir avanzando. Por eso, si no afirmas bien los pies o no atas la carga con cuerda, sales disparado hacia delante con fuerza y te haces mucho daño. Cuando pares algo que se mueve, o cuando vayas en un vehículo veloz, debes tener presente que esta fuerza que trata de lanzar las cosas hacia delante actúa siempre, y prepararte para tu seguridad." },
  { id:35, topic:"Tijeras", emoji:"✂️",
    question:"Cuando quieres cortar una rama dura o una tela gruesa con tijeras, ¿en qué parte del filo debes sujetarla para cortar más fácil con el menor esfuerzo?",
    choices:["En la punta misma del filo","En la base del filo (lo más cerca del tornillo o la articulación)","En el medio del filo","La fuerza necesaria es la misma donde sea que cortes"],
    answerIndex:1,
    explanation:"Las tijeras también son una herramienta muy útil que usa el principio de la palanca que hemos ido aprendiendo. El tornillo donde se cruzan y se fijan las dos hojas es el apoyo (el punto de apoyo). Cuanto más cerca de este tornillo de apoyo cortes, muchas veces más fuerte se vuelve la fuerza que tu mano transmite al filo. Por eso, con algo duro que no corta, intentar cortarlo en la punta de las tijeras solo te hace daño en la mano, pero si lo sujetas bien en la base del filo, puedes cortarlo de un tijeretazo con una fuerza sorprendentemente pequeña. Conoce las características de tus herramientas y usa el punto más eficiente." },
  { id:36, topic:"Gravedad", emoji:"🍎",
    question:"¿Por qué dejar caer una piedrecita sobre el pie desde la altura de la rodilla, frente a dejarla caer desde lo alto del techo de tu casa, la que cae del techo causa una herida más grave?",
    choices:["Porque la piedra se enfría más allá arriba en el techo","Porque la gravedad, la fuerza que tira de las cosas hacia la tierra, hace que la piedra vaya cada vez más rápido cuanto más larga es la caída, así que el golpe al chocar es más fuerte","Porque una piedra en un lugar alto se hace más grande de tamaño","Porque el aire empuja la piedra hacia abajo"],
    answerIndex:1,
    explanation:"Todo lo que hay sobre la tierra recibe siempre una fuerza llamada gravedad, que lo atrae hacia el suelo. Para algo que está en un lugar alto, cuanto más larga es la caída, más sigue tirando de ello la gravedad y más se acelera (va cada vez más rápido). Un objeto que ha acelerado crea un enorme poder destructor (energía) en el instante en que choca contra el suelo o contra tu cuerpo. Desde la altura de la rodilla solo duele, pero algo que cae de un techo alto o un acantilado, aunque sea una piedra pequeña o una herramienta, se convierte en un arma capaz de quitarle la vida a una persona. Cuando trabajes cerca de un lugar alto, debes comprobar que no haya nadie debajo y tener el máximo cuidado de no dejar caer nada." },
  { id:37, topic:"Equilibrio", emoji:"⚖️",
    question:"Cuando llevas al hombro una pértiga larga (una pértiga de carga) con dos vasijas de agua pesadas colgadas delante y detrás, ¿cómo puedes caminar con facilidad sin que te duela el hombro?",
    choices:["Hacer la carga de delante muy pesada y la de detrás ligera","Hacer las cargas de delante y detrás exactamente del mismo peso, y poner el centro justo de la pértiga sobre el hombro","No poner la pértiga al hombro; llevarla solo con las manos","Dejar caer las cargas al suelo alternándolas mientras corres"],
    answerIndex:1,
    explanation:"Cuando llevas cargas colgadas a cada lado de una pértiga larga, si los pesos de delante y detrás están desiguales, la pértiga se inclina hacia un lado y tienes que luchar por sujetarla con las manos. Esto cansa rápido no solo el hombro, sino también los brazos y la espalda. La respuesta correcta es hacer las cargas de delante y detrás exactamente con el mismo equilibrio. Así el peso recae por igual justo encima del hombro a través de la pértiga, y puedes llevar cargas pesadas solo con caminar, sin usar músculo de más para luchar contra la inclinación. Si una carga es inevitablemente más ligera, ajusta el equilibrio deslizando la cuerda del lado ligero hacia el extremo de la pértiga." },
  { id:38, topic:"Resistencia del aire", emoji:"🪂",
    question:"Tienes dos hojas de papel del mismo tamaño y el mismo peso. Una se deja como hoja plana, la otra se aprieta con la mano hasta hacer una bola compacta. Cuando las sueltas a la vez desde un lugar alto, ¿cuál llega antes al suelo?",
    choices:["La hoja plana tal cual","El papel apretado en una bola compacta","Las dos llegan exactamente a la vez","Cambia cada vez según el viento"],
    answerIndex:1,
    explanation:"Aunque sean cosas del mismo peso, cuando caen por el aire actúa un freno llamado resistencia del aire, con el aire estorbando. La hoja de papel plana tiene una superficie amplia, así que atrapa mucho aire por debajo y cae solo despacio, como un paracaídas. Pero el papel apretado en una bolita toca el aire sobre una superficie muy estrecha, así que casi no recibe freno y cae rápido, atraído recto hacia abajo por la gravedad. Que un molino de viento gire con el viento, o que un paraguas casi salga volando en un día de viento fuerte, también tienen que ver con esta fuerza de freno del aire." },
  { id:39, topic:"Elasticidad", emoji:"🏹",
    question:"Cuando doblas con todas tus fuerzas un bambú duro y resistente, o una rama de árbol flexible, y luego sueltas de golpe, vuelve con fuerza a su forma original. ¿En qué puedes usar esta propiedad (la elasticidad) para hacer una herramienta útil en la vida diaria?",
    choices:["Un refrigerador para que la comida no se pudra","Un arco y flecha para lanzar una flecha a una presa lejana, o una trampa que dispara cosas pesadas","Un filtro para limpiar el agua","Una herramienta para teñir la ropa de blanco"],
    answerIndex:1,
    explanation:"El caucho y los resortes, y también el bambú y las ramas de árbol, tienen una propiedad misteriosa llamada elasticidad: cuando aplicas fuerza su forma se dobla, y cuando sueltas tratan de volver a su forma original a gran velocidad. Mientras la sostienes doblada con la mano, la fuerza que aplica la persona se acumula un momento dentro de esa herramienta como energía. En el instante en que sueltas, esa fuerza acumulada se libera de golpe, así que puedes lanzar una flecha muchas veces más lejos, o accionar una trampa, que tirando solo con el brazo. Aprovechando esta fuerza que tienen las plantas de la naturaleza, la humanidad ha fabricado herramientas para la caza y la vida diaria desde tiempos antiguos." },
  { id:40, topic:"Lubricar", emoji:"🛢️",
    question:"Las ruedas de un carro, o el gozne de una puerta, empezaron a hacer un molesto chirrido y a ponerse pesados cada vez que los movías. Si echas aquí unas gotas de aceite, ¿por qué vuelven a moverse con suavidad?",
    choices:["Porque el aceite derrite el hierro y lo hace más ligero","Porque el aceite se endurece y se vuelve pegamento","Porque el aceite entra en el hueco entre metal y metal y reduce muchísimo la fuerza de freno del roce (la fricción)","Porque el olor del aceite ahuyenta a los insectos"],
    answerIndex:2,
    explanation:"Cuando una máquina o una herramienta se mueve, hay lugares donde el metal roza fuerte y directamente contra el metal. Ahí actúa un freno muy fuerte llamado fricción y, si se deja así, se desgasta y se rompe, o hace falta muchísima fuerza para moverlo. Cuando aplicas aceite, se forma una fina película de aceite en el pequeño hueco del metal y evita que rocen directamente. Como la fuerza de freno desaparece de golpe, la herramienta se mueve con una suavidad asombrosa y poca fuerza. Solo con aplicar un poco de aceite de cocina o aceite vegetal a una herramienta, esta dura más y reduce mucho el desgaste de las fuerzas de la persona." }
];
