/*
 * Wise World - Dados do quiz (Português)
 * ⚠ Tradução por IA a partir do original em japonês. Recomenda-se a revisão
 *    por um falante nativo ou especialista em saúde antes de usar.
 * Mantenha id / answerIndex / emoji iguais em todos os idiomas.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).pt = [
  { id:1, topic:"Água segura", emoji:"💧",
    question:"Qual água é segura e não vai te dar dor de barriga?",
    choices:["Água de rio","Água de poço","Água bem fervida no fogo","Água da chuva"],
    answerIndex:2,
    explanation:"A água de rio, de poço e da chuva pode parecer perfeitamente clara e limpa, mas pode estar cheia de seres vivos minúsculos que nossos olhos não conseguem ver (germes e vírus). Se você beber essa água do jeito que está, ela pode causar uma forte dor de estômago ou uma doença grave que põe a vida em risco. Mas quando você põe a água no fogo e a ferve bem até borbulhar, o calor mata todos esses seres nocivos. Por isso, a água que foi bem fervida e depois deixada esfriar é a mais segura do mundo, e a que você pode beber com confiança." },
  { id:2, topic:"Lavar as mãos", emoji:"🧼",
    question:"O que você deve fazer antes de comer?",
    choices:["Lavar as mãos com água e sabão","Limpar as mãos na roupa","Não fazer nada","Tocar na terra"],
    answerIndex:0,
    explanation:"Nossas mãos tocam muitos objetos e o chão todos os dias, então sem perceber elas pegam muitos germes invisíveis. Se você tocar a comida com essas mãos, os germes passam para a comida e você os engole para dentro do corpo junto com ela. Limpar as mãos em roupa suja, ou só molhá-las com água, não tira os germes: eles ficam grudados. Só usando sabão e esfregando as palmas, o dorso das mãos e entre os dedos com bastante espuma, e depois enxaguando com água, é que você consegue de fato eliminar os germes." },
  { id:3, topic:"Lavar as mãos", emoji:"🚽",
    question:"O que você deve fazer depois de usar o banheiro?",
    choices:["Ir brincar na hora","Lavar as mãos com água e sabão","Esfregar as mãos na roupa","Secar as mãos na calça"],
    answerIndex:1,
    explanation:"Depois de usar o banheiro, germes muito fortes das fezes e da urina, que causam doenças, grudam facilmente nas suas mãos. Se você for brincar sem lavar, esses germes passam para as maçanetas e brinquedos que você toca, e transmitem a doença ao próximo amigo ou familiar que os tocar. E se você tocar a própria boca ou os olhos com essas mãos, também pode ficar doente. Por mais pressa que você tenha, lavar sempre bem as mãos com água e sabão depois do banheiro é uma regra que protege a sua vida e a de quem está ao seu redor." },
  { id:4, topic:"Saúde", emoji:"💧",
    question:"Quando você está de barriga ruim e as fezes ficam aguadas (diarreia), o que é mais importante?",
    choices:["Comer bastante","Não beber nada","Beber bastante água segura","Correr e brincar"],
    answerIndex:2,
    explanation:"Quando você está de barriga ruim e fezes aguadas (diarreia) saem várias vezes, o seu corpo perde água e nutrientes valiosos sem parar. Isso se chama desidratação. Quando falta água no corpo, as funções importantes que nos mantêm vivos começam a parar, e as crianças pequenas, principalmente, podem perder a vida de repente. Quando você está com diarreia, em vez de se forçar a comer alimentos sólidos, o melhor é primeiro repor a água que perdeu. Bebendo água segura, fervida e esfriada, aos poucos e muitas vezes, você consegue manter as forças e proteger a sua vida." },
  { id:5, topic:"Cuidar de ferimentos", emoji:"🩹",
    question:"Quando você cai e sangra, o que deve fazer primeiro?",
    choices:["Pôr terra","Lavar bem com água limpa","Deixar sem fazer nada","Esfregar com uma folha"],
    answerIndex:1,
    explanation:"Quando você cai e faz um ferimento que sangra, a ferida fica coberta de terra, lama e poeira do chão, junto com muitos germes. Se você acreditar em ditados antigos e passar terra, esfregar com uma folha suja ou deixar assim, os germes entram fundo na ferida e se multiplicam. Aí a ferida incha, fica vermelha e dói muito, e no pior caso um braço ou uma perna pode apodrecer e parar de se mexer. Quando você se machuca, o primeiro passo certo para a ferida não ficar grave é usar água limpa e segura para lavar com força a lama e a sujeira da ferida." },
  { id:6, topic:"Alimentos", emoji:"🦠",
    question:"O que acontece quando a comida estraga (apodrece)?",
    choices:["Fica gostosa","Apodrece e dá dor de barriga","Fica dura","Não muda nada"],
    answerIndex:1,
    explanation:"A comida contém naturalmente, desde o começo, uma pequena quantidade de micróbios invisíveis. Num lugar fresco os micróbios não conseguem agir, mas se você deixar a comida muito tempo num lugar quente, vira o ambiente perfeito para eles, e em poucas horas eles se multiplicam aos milhões, um número assustador. Quando os micróbios se multiplicam tanto e a forma e a natureza da comida mudam, dizemos que ela estragou. A comida estragada guarda o veneno forte que os micróbios produziram, então comê-la causa forte dor de estômago, diarreia e enjoo, e faz mal ao seu corpo." },
  { id:7, topic:"Alimentos", emoji:"👃",
    question:"Qual é um sinal de que a comida estragou?",
    choices:["Um cheiro ou gosto estranho","Uma cor vermelha","Algo frio","Algo bem cozido"],
    answerIndex:0,
    explanation:"Você pode usar o próprio nariz e a língua para checar se a comida estragou e não está mais segura. Se ela tiver um cheiro azedo estranho ou um cheiro forte e ruim, ou um gosto esquisito quando você prova um pouco, ou se estiver grudenta e fizer fios, isso é prova de que os germes se multiplicaram muito e que se formou veneno. Se você se forçar a comer porque seria desperdício, coloca a sua vida em risco por uma forte intoxicação. Se o cheiro ou o gosto estiverem, mesmo que um pouco, suspeitos, decida jogar fora e nunca engula." },
  { id:8, topic:"Alimentos", emoji:"🪰",
    question:"O que fazer com a comida em que uma mosca pousou?",
    choices:["Comer do jeito que está","Não comer a parte que a mosca tocou (jogar fora)","Criar a mosca","Ficar olhando"],
    answerIndex:1,
    explanation:"O inseto que chamamos de mosca gosta de andar por lugares muito sujos e cheios de germes, como fezes de animais, carcaças e lixões. Por isso, germes que causam doenças terríveis grudam nas suas patinhas finas e no corpo. Quando uma mosca dessas pousa na nossa comida, naquele instante os germes das patas passam para a comida. Se você comer o lugar que ela tocou, está colocando na boca, de forma indireta, germes de fezes e lixo, o que pode causar uma doença grave. Mesmo que pareça desperdício, é mais seguro cortar e jogar fora a parte onde a mosca pousou." },
  { id:9, topic:"Prevenir doenças", emoji:"🦟",
    question:"O que acontece se você deixar água parada por muito tempo?",
    choices:["A água fica limpa","Mosquitos nocivos se multiplicam","Seu dinheiro aumenta","Não acontece nada"],
    answerIndex:1,
    explanation:"A água velha que fica parada num só lugar sem correr vira o lugar perfeito para o inseto chamado mosquito pôr os ovos. Se você deixar baldes, pneus velhos ou latas vazias com água ao redor do quintal ou da casa, ali nascem centenas e milhares de mosquitos novos que voam por toda parte. Quando um mosquito chupa o sangue de uma pessoa, injeta no corpo os germes de doenças muito assustadoras e mortais, como a malária e a dengue. Acabar com as poças de água ao redor da casa é um plano importante para proteger a sua família dessas doenças terríveis." },
  { id:10, topic:"Limpeza", emoji:"✋",
    question:"Quando as unhas estão compridas, o que se acumula dentro?",
    choices:["As mãos ficam mais fortes","Sujeira preta e germes se juntam embaixo das unhas","A comida fica mais gostosa","Não muda nada"],
    answerIndex:1,
    explanation:"Quando as unhas crescem compridas, lama e sujeira pretas entram bem apertadas no espaço estreito entre a unha e a pele enquanto você brinca na terra, ajuda ou trabalha. A sujeira que entra nesse espaço não sai fácil só com uma lavagem normal de mãos, e vira o esconderijo perfeito para os germes. Com as unhas compridas, quando você come com as mãos ou toca o próprio rosto ou uma ferida, esses germes escondidos entram fácil no seu corpo. Manter as unhas sempre curtas é um jeito básico de prevenir doenças." },
  { id:11, topic:"Ao tossir", emoji:"🤧",
    question:"O que você deve fazer quando tosse ou espirra?",
    choices:["Fazer na direção do rosto de alguém","Cobrir a boca e o nariz com a mão ou a manga","Gritar alto","Não fazer nada"],
    answerIndex:1,
    explanation:"Quando você está resfriado ou com uma doença no pulmão, uma única tosse ou espirro lança gotinhas de água invisíveis da boca e do nariz, a vários metros e com força. Cada gotinha pode conter dezenas de milhares de germes de doença. Se você tossir na direção do rosto de alguém, transmite a doença direto, e se não cobrir nada, os germes se espalham pelo ar e todos na mesma sala podem ficar doentes. Quando você tosse, cobrir bem a boca e o nariz com a manga ou a mão evita que você espalhe a doença para a família e os amigos queridos ao seu redor." },
  { id:12, topic:"Limpeza", emoji:"🗑️",
    question:"O que acontece se você deixar lixo jogado perto de casa?",
    choices:["A casa fica limpa","Ratos e insetos nocivos se juntam e a doença se espalha","O lixo vira flores","Não tem problema nenhum"],
    answerIndex:1,
    explanation:"Se você jogar restos de comida e lixo bem ao lado de casa, o cheiro atrai muitos seres como ratos, moscas e baratas. Esses seres costumam andar por esgotos e lugares sujos, então carregam no corpo muitos germes que causam doenças assustadoras. Ao aumentar ao redor do lixo, eles acabam entrando em casa e sujam a comida e a água de beber que estão lá dentro. O lixo deve ser jogado num lugar certo, bem longe de casa, ou enterrado fundo num buraco na terra." },
  { id:13, topic:"Dentes saudáveis", emoji:"🪥",
    question:"Qual é o principal motivo de escovar os dentes?",
    choices:["Pintar os dentes de branco","Reduzir os germes da cárie na boca e proteger os dentes","Deixar o queixo mais forte","Encher o estômago"],
    answerIndex:1,
    explanation:"Depois de comer, sempre ficam pequenos restos de comida nos vãos e na superfície dos dentes. Os seres invisíveis chamados germes da cárie, que vivem na nossa boca, adoram esses restos. Se você deixá-los ali, os germes da cárie se alimentam deles e produzem um ácido forte que dissolve os dentes. Por causa desse ácido, aos poucos abrem-se buracos nos dentes, que deveriam ser a parte mais dura do corpo, e quando chega ao nervo dá uma dor tão forte que você não consegue dormir à noite. Escovar os dentes depois de comer é um trabalho totalmente necessário para tirar o alimento dos germes e proteger os seus dentes." },
  { id:14, topic:"Prevenir ferimentos", emoji:"👟",
    question:"Por que você usa calçados ao andar na rua?",
    choices:["Para os pés crescerem","Para impedir que vermes e germes da terra entrem pela pele dos pés","Para treinar corrida","Para não sujar a roupa"],
    answerIndex:1,
    explanation:"Quando você anda descalço na terra e na lama, seres minúsculos escondidos no chão, pequenos demais para ver (as larvas de parasitas), e germes podem atravessar a pele macia da sola dos pés e entrar sozinhos no seu corpo. Os vermes que entram se instalam na sua barriga (os intestinos) e roubam os nutrientes que você come, deixando você muito anêmico, parando o seu crescimento e tirando a sua energia. Usar calçados também protege você de ferimentos graves por pisar em cacos de vidro, pedras pontudas ou espinhos. Use sempre sapatos ou sandálias quando sair." },
  { id:15, topic:"Limpeza", emoji:"👕",
    question:"O que acontece se você continuar usando roupa suja?",
    choices:["A roupa fica mais resistente","A pele coça ou você fica doente","O corpo fica mais forte","Não muda nada"],
    answerIndex:1,
    explanation:"Se você continuar usando roupa encharcada de suor ou suja de lama por muitos dias, mofo e germes se alimentam do suor e da oleosidade da pele que ficam na roupa e se multiplicam muito dentro das fibras. Como essa roupa suja fica roçando na sua pele o tempo todo, a pele pode inchar e ficar vermelha, coçar muito, ou desenvolver uma doença com feridas que soltam pus. A roupa suja pode ficar livre de germes lavando bem com água e sabão e secando bem ao sol (os raios ultravioleta). Usar sempre roupa limpa é importante para proteger a barreira da sua pele." },
  { id:16, topic:"Limpeza", emoji:"🚿",
    question:"O que tem de bom em lavar o corpo?",
    choices:["A pele fica limpa e você previne doenças de pele","Você cresce","Seu cabelo cai","Você fica com fome"],
    answerIndex:0,
    explanation:"Todos os dias saem da pele humana oleosidade invisível (o sebo) e suor, e a poeira e a terra de fora se misturam, sujando o corpo todo. Se você deixar essa sujeira por muitos dias, os germes ruins se multiplicam na superfície da pele, e você pode ter furúnculos terríveis ou uma doença assustadora em que a pele fica em carne viva e apodrece. Lavando regularmente o corpo todo com cuidado, com água e sabão, e tirando a oleosidade e a sujeira velhas, a sua pele fica saudável e forte, formando uma barreira poderosa que impede a doença de entrar de fora." },
  { id:17, topic:"Água segura", emoji:"💧",
    question:"Quando só tem água barrenta, como bebê-la com segurança?",
    choices:["Beber do jeito que está","Filtrar a lama com pano ou areia e depois ferver no fogo","Só deixar no sol e beber","Beber só um pouco"],
    answerIndex:1,
    explanation:"Quando tudo o que você consegue é água barrenta, beber do jeito que está coloca no seu corpo uma enorme quantidade de germes junto com a lama e causa uma doença grave. Para deixá-la segura são precisos dois saberes. Primeiro, passe a água por um pano limpo e fino, ou por um recipiente cheio de areia e pedrinhas, para filtrar a lama e os pedaços grandes e deixar a água clara. Mas ficar clara não basta: os germes invisíveis continuam vivos. Depois, você precisa pôr no fogo e ferver bem até borbulhar, para que o calor elimine os germes e ela enfim vire água segura para beber. Com sabedoria, você pode fazer água que salva vidas até de água barrenta." },
  { id:18, topic:"Bebês", emoji:"🍼",
    question:"Qual é o melhor alimento para um bebê?",
    choices:["Leite de vaca (cru)","O leite da mãe (leite materno)","Água de rio","Água com açúcar"],
    answerIndex:1,
    explanation:"O corpo de um bebê recém-nascido é muito fraco e quase não tem força para vencer os germes das doenças. O leite da mãe (leite materno) não só contém o alimento perfeito para o bebê crescer, mas também grandes quantidades de um componente protetor especial chamado imunidade, que o defende das doenças. Além disso, o leite materno sai direto do corpo, então nunca toca água suja de fora nem germes de recipientes: é o mais limpo e seguro do mundo. O leite cru de outros animais, a água de rio ou a água com açúcar podem arruinar o estômago e o intestino delicados do bebê e tirar a vida dele, por isso você nunca deve dá-los." },
  { id:19, topic:"Prevenir doenças", emoji:"😷",
    question:"O que fazer perto de alguém com tosse forte?",
    choices:["Manter um pouco de distância e virar o rosto ao passar","Respirar fundo na frente da pessoa","Apertar a mão dela","Ficar bem na frente dela"],
    answerIndex:0,
    explanation:"Doenças respiratórias graves como a tuberculose ficam muito tempo no ar, levadas pelas gotinhas minúsculas e invisíveis que se espalham quando uma pessoa doente tosse. Se você respirar fundo por perto, ou ficar perto por muito tempo, leva esses germes para o fundo dos seus pulmões e pode pegar a mesma doença grave. Quando alguém tosse forte, não se trata de ser malvado nem de tratar a pessoa de forma diferente; para se proteger, mantenha vários metros de distância e, ao passar, vire o rosto e expire devagar: é assim que os dois se protegem." },
  { id:20, topic:"Ar fresco", emoji:"🪟",
    question:"Como manter o ar de um cômodo limpo?",
    choices:["Fechar bem todas as portas e janelas","Abrir janelas e portas para trocar o ar","Todos gritarem alto juntos","Não muda nada"],
    answerIndex:1,
    explanation:"Quando muita gente se junta num cômodo pequeno e fechado, os germes e vírus que alguém carrega vão se acumulando cada vez mais no ar, até o ar do cômodo ficar cheio de germes. Se você ficar muito tempo nesse cômodo, todos respiram o ar sujo e ficam doentes juntos (um contágio em grupo). Abrindo janelas e portas em dois ou mais lugares para trocar o ar fresco de fora pelo ar sujo do cômodo (ventilar), você consegue expulsar os germes do ar e proteger a saúde de todos que estão ali." },
  { id:21, topic:"Alavancas", emoji:"🪨",
    question:"Quando você quer mover uma pedra pesada enterrada no chão usando uma alavanca comprida, onde deve empurrar com mais força para movê-la com o menor esforço?",
    choices:["No ponto bem ao lado da pedra","No meio da alavanca","Na ponta mais distante da alavanca, longe da pedra","É igual onde quer que você empurre"],
    answerIndex:2,
    explanation:"Quando você move algo pesado com uma alavanca, existe uma regra chamada princípio da alavanca: quanto mais longe você estiver da pequena pedra que serve de apoio (o ponto de apoio), menos força precisa para empurrar. Se empurrar perto da pedra, a alavanca não se mexe, mas se segurar a ponta mais distante da alavanca e empurrar pondo o seu peso, consegue levantar uma pedra pesada com uma força surpreendentemente pequena. Conhecer como uma ferramenta funciona assim permite multiplicar muitas vezes a sua própria força e realizar trabalhos pesados com facilidade." },
  { id:22, topic:"Alavancas", emoji:"⚖️",
    question:"Quando você levanta uma carga pesada com uma alavanca comprida, onde deve colocar a pequena pedra (o ponto de apoio) que sustenta a alavanca para que ela levante mais facilmente?",
    choices:["Bem ao lado da carga pesada","Bem ao lado de onde você aplica a força","Exatamente no meio da alavanca","É melhor não colocar nenhuma pedra"],
    answerIndex:0,
    explanation:"Quando você levanta algo pesado com uma alavanca, a posição da pequena pedra de apoio (o ponto de apoio) é muito importante. Ao colocar esse apoio bem ao lado da carga pesada, a carga se move apenas uma curta distância, mas a força que você precisa para levantá-la fica muito menor. Ao contrário, se a pedra de apoio estiver perto de você, por mais que empurre não vai conseguir levantar a carga. Quando quiser mover algo pesado, lembre-se da sabedoria de colocar o apoio perto da coisa que quer mover." },
  { id:23, topic:"Rolar", emoji:"🪵",
    question:"Quando você move uma caixa de madeira pesada arrastando-a pelo chão, como pode movê-la mais facilmente com o menor esforço?",
    choices:["Pôr vários toros redondos e duros embaixo da caixa e fazê-la rolar","Puxar com toda a força do jeito que está","Jogar água em cima da caixa","Bater a caixa com força no chão"],
    answerIndex:0,
    explanation:"Quando você arrasta algo pesado direto pelo chão, age com força um freio chamado atrito, criado onde o objeto raspa contra o chão, então mover exige muitíssima força. Mas se você puser toros redondos e duros embaixo da caixa, o movimento deixa de ser arrastar e passa a ser os toros rolando. Rolar tem dezenas de vezes menos força de freio do que arrastar, então até uma só pessoa consegue mover uma carga pesada com facilidade. Quando a carga avança, você pega os toros que saíram atrás e os põe de novo na frente, uma sabedoria que a humanidade usa desde a Antiguidade." },
  { id:24, topic:"Rampas", emoji:"🛝",
    question:"Quando você quer pôr uma carga pesada sobre uma plataforma alta, da altura do peito de um adulto, qual é o jeito de movê-la que menos sobrecarrega o seu corpo?",
    choices:["Ficar na frente da plataforma e levantá-la reto para cima com toda a força","Apoiar uma tábua comprida inclinada contra a plataforma para fazer uma rampa e empurrá-la para cima","Arremessar a carga contra a plataforma de longe","Rebaixar a altura da plataforma para deixá-la mais baixa"],
    answerIndex:1,
    explanation:"Se você tenta levantar uma carga pesada reto para cima, enfrenta de frente a força que puxa as coisas para a terra (a gravidade), então tem de sustentar tudo só com os músculos, o que machuca as costas e os braços. Aqui, se você apoia uma tábua comprida inclinada contra a plataforma para fazer uma rampa (um plano inclinado), a tábua passa a sustentar a maior parte do peso da carga. Ao subir uma rampa, a distância que você caminha aumenta, mas a força necessária para empurrar a carga pode ser reduzida a menos da metade. Quando levar coisas para um lugar alto, procure sempre um jeito de fazer uma rampa." },
  { id:25, topic:"Roldanas", emoji:"🪣",
    question:"Quando você puxa com uma corda um balde pesado cheio de água de um poço fundo, o que fica mais fácil se você instalar na barra acima do poço uma roda redonda que gira (uma roldana) e passar a corda por ela?",
    choices:["O peso da água fica pela metade, mais leve","A quantidade de água aumenta sozinha","Você consegue erguer a água só puxando a corda para baixo","A corda nunca vai arrebentar"],
    answerIndex:2,
    explanation:"Quando você passa uma corda pela roda redonda acima do poço (uma roldana fixa), na verdade o peso da água não fica mais leve. Mas o que há de maravilhoso nessa ferramenta é que ela muda a direção em que você aplica a força. Se você tenta erguer a corda reto para cima, tem de levantá-la só com a força dos braços e das costas; mas se passa a corda pela roda redonda e puxa para baixo, consegue pôr todo o peso do seu corpo sobre a corda. Poder usar o próprio peso para puxar água pesada com facilidade e segurança é a sabedoria dessa roda redonda." },
  { id:26, topic:"Sarilho e eixo", emoji:"🔄",
    question:"Quando você quer girar um parafuso que não gira de jeito nenhum, ou o pesado sarilho de um poço, como pode girá-lo mais facilmente?",
    choices:["Girá-lo usando uma haste curta e fina","Tornar a parte da manivela grande e comprida, e girar essa","Girá-lo só com as pontas dos dedos, sem ferramenta","Bater com força no parafuso com um martelo"],
    answerIndex:1,
    explanation:"Quando você quer girar um eixo que está no centro, se instalar nele uma manivela redonda grande ou um cabo comprido, consegue criar uma grande força de giro com pouco esforço. Isso se chama princípio da roda e eixo. Você não consegue mexer a parte fina girando-a direto com os dedos, mas ao girar a manivela grande de fora, a distância que a sua mão percorre aumenta, enquanto a força sobre o eixo fica muitas vezes maior. A máquina que enrola a corda de um poço, a maçaneta de uma porta em casa, os parafusos das ferramentas; tudo o que gira ao seu redor usa essa sabedoria." },
  { id:27, topic:"Centro de gravidade", emoji:"🏺",
    question:"Há pessoas que andam com destreza carregando um pote de água pesado ou lenha sobre a cabeça. Por que conseguem andar longas distâncias sem machucar o pescoço nem as costas?",
    choices:["Porque andam dobrando muito o corpo para a frente ou para trás","Porque mantêm as costas perfeitamente retas e põem o centro da carga (o seu centro de gravidade) bem acima dos ossos","Porque ficam sacudindo a carga com força sobre a cabeça o tempo todo","Porque todos nascem com os ossos do pescoço mais grossos que os demais"],
    answerIndex:1,
    explanation:"Quando você carrega uma carga pesada nas mãos, o esforço recai só de um lado do corpo e os músculos cansam rápido. Mas se você endireita perfeitamente as costas e põe a carga bem acima da cabeça, o peso do centro da carga (o seu centro de gravidade) desce reto pelo pilar de ossos, da cabeça ao pescoço e à coluna, e sai para o chão. Como são os ossos firmes, e não os músculos, que sustentam o peso, você consegue carregá-la com segurança por longas distâncias sem gastar força muscular, desde que mantenha o equilíbrio. Manter as coisas perto do eixo central do corpo é uma sabedoria importante para não se machucar." },
  { id:28, topic:"Pressão", emoji:"🦶",
    question:"Quando você anda por uma estrada enlameada onde, depois da chuva, vira lama funda e os pés afundam, como pode andar com mais facilidade sem afundar?",
    choices:["Andar na ponta dos pés, deixando a sola dos pés a menor possível","Amarrar à sola dos pés uma tábua de madeira plana e grande, e andar","Simplesmente gritar alto e atravessar correndo","Carregar muita bagagem para ficar mais pesado"],
    answerIndex:1,
    explanation:"O peso que recai sobre o chão se concentra com mais força num ponto e afunda mais fundo, como uma agulha, quanto menor for a superfície que o toca. Isso se chama pressão. Ficar na ponta dos pés deixa a superfície menor, então você afunda ainda mais. Ao contrário, se amarrar à sola dos pés uma tábua de madeira plana e grande, o seu peso se espalha por uma superfície ampla, então a força que empurra o chão para baixo enfraquece e você consegue andar sobre a lama sem afundar. Fazer larga e plana a base de um prédio pesado é a mesma sabedoria para espalhar a pressão." },
  { id:29, topic:"Carroças", emoji:"🛒",
    question:"Quando você quer carregar muita bagagem pesada numa carroça de duas rodas e puxá-la, onde deve pôr as coisas pesadas para que fique o mais leve e fácil de puxar?",
    choices:["Bem ao lado das suas mãos, perto do cabo","Na ponta de trás da carroça","Bem acima do eixo das rodas","É igual onde quer que você carregue"],
    answerIndex:2,
    explanation:"Quando você puxa uma carroça, o peso sobre as suas mãos muda muitíssimo conforme onde você põe a carga. Se puser a bagagem pesada perto das mãos, acaba correndo enquanto levanta o peso da carga direto com os braços, e cansa rápido. Se estiver longe demais, atrás, a carroça tomba para trás, o que é perigoso. A resposta certa é bem acima do eixo das rodas. Se puser as coisas pesadas aqui, as rodas firmes e o chão sustentam todo o peso, então quase nenhum peso recai sobre as suas mãos. Como você só precisa da força de puxar para a frente, consegue transportar uma grande carga com muita facilidade." },
  { id:30, topic:"Gumes", emoji:"🔪",
    question:"Quando você afia o gume de um facão de rachar lenha, ou de uma faca de cozinha de cortar comida, esfregando-o numa pedra (uma pedra de amolar), por que ele corta melhor?",
    choices:["Porque a ponta do gume fica mais fina e delgada, e a força se concentra num só ponto","Porque o gume esquenta e derrete a comida","Porque o gume fica mais pesado","Porque o gume fica arredondado"],
    answerIndex:0,
    explanation:"Que algo seja cortado por um gume acontece porque a força que uma pessoa aplica se concentra no ponto extremamente estreito da ponta do gume e rompe o objeto. Quando um gume envelhece e arredonda, a força se espalha por uma superfície ampla, então por mais que você empurre não corta. Afiar um gume é o trabalho de desbastar a ponta arredondada para deixá-la o mais fina e delgada possível. Uma vez que a ponta fica fina, até uma força pequena cria uma pressão enorme nesse ponto, então você consegue cortar lenha dura ou comida com um toque leve. Cuidar das suas ferramentas é o básico para economizar as suas energias." },
  { id:31, topic:"Atrito", emoji:"👟",
    question:"Quando você anda numa ladeira ou sobre pedras molhadas, o que escorrega menos e é mais seguro: sapatos lisos e escorregadios, ou sapatos com sulcos fundos e cravados na sola?",
    choices:["Sapatos lisos e planos","Sapatos com sulcos fundos e cravados na sola","É igual qualquer um que você use","Escorrega menos sem sapato nenhum"],
    answerIndex:1,
    explanation:"Quando a sola de um sapato raspa contra o chão, age ali um freio chamado atrito que evita que você escorregue. Se a sola é lisa, nenhum freio age entre ela e o chão, e você escorrega e cai com facilidade, sobretudo onde há água ou lama. Se a sola tem sulcos fundos e cravados, esses sulcos se encaixam firmemente nas irregularidades do chão e criam um freio forte. Escorregar e cair pode levar a ferimentos graves, mas conhecendo como o atrito funciona, escolhendo sapatos com sulcos em chão escorregadio ou apoiando toda a sola firmemente no chão, você pode agir com segurança." },
  { id:32, topic:"Flutuar", emoji:"⛵",
    question:"Uma pedrinha afunda na água, e mesmo assim um navio de madeira milhares de vezes mais pesado e maior consegue flutuar na água. Por quê?",
    choices:["Porque o navio tem o formato de uma tigela e guarda muito ar e água dentro","Porque o navio recebe muito vento","Porque há pedras mágicas pintadas no fundo dele","Porque o navio é feito de um óleo mais leve que a água"],
    answerIndex:0,
    explanation:"Sobre um objeto dentro da água age uma força misteriosa chamada empuxo, que o empurra para cima na mesma medida da água que ele desloca. A pedrinha é maciça por dentro e pesada, então a pedra pesa mais que a água que desloca, e afunda. Mas um navio grande tem o formato de uma tigela, e dentro guarda muito ar. Visto no conjunto, fica muito leve para o seu tamanho, então a força da água que empurra de baixo fica mais forte, e até um navio grande consegue flutuar na água sem virar." },
  { id:33, topic:"Triângulos", emoji:"🔺",
    question:"Quando você constrói uma casa ou uma ponte de madeira ou de ferro, por que montar a estrutura em forma de triângulos faz um prédio muito firme e difícil de quebrar?",
    choices:["Porque precisa de mais material que um quadrado","Porque o triângulo tem a propriedade de que a sua forma nunca se deforma, mesmo quando uma força forte é aplicada por cima","Porque fazer triângulos deixa o vento passar mais facilmente","Porque é uma forma antiga usada como amuleto dos deuses"],
    answerIndex:1,
    explanation:"Um prédio feito de pilares montados só em quadrados desaba com facilidade, com as juntas dobrando moles, quando uma força forte ou o tremor de um terremoto é aplicado por cima ou pelo lado. Mas se você acrescenta uma haste inclinada dentro desse quadrado para fazer um triângulo (uma estrutura treliçada), então venha a força da direção que vier, as hastes se puxam e se empurram umas às outras e a forma não se deforma nada. Se você olhar as grandes pontes do mundo, ou a parte de baixo dos telhados dos prédios, esses triângulos sempre estão finamente combinados ali. É uma sabedoria magnífica da construção: mesmo com pouco material, só pensando bem na forma você consegue fazer algo muitas vezes mais firme." },
  { id:34, topic:"Inércia", emoji:"🐎",
    question:"Quando um cavalo ou uma carroça que vai correndo freia de repente e para de vez, o que acontece com a bagagem e as pessoas que estão em cima?",
    choices:["Tombam para trás do jeito que estão","São arremessadas para a frente com força","Pulam reto para cima no mesmo lugar","Nada acontece; param de vez também"],
    answerIndex:1,
    explanation:"No universo existe uma força misteriosa chamada inércia: uma coisa em movimento procura continuar se movendo na mesma velocidade. Mesmo que o cavalo ou a carroça pare de repente, as pessoas e a bagagem em cima ainda procuram continuar avançando. Por isso, se você não firmar bem os pés ou não amarrar a carga com corda, é arremessado para a frente com força e se machuca feio. Quando você para algo em movimento, ou quando anda num veículo veloz, deve ter em mente que essa força que procura lançar as coisas para a frente age sempre, e se preparar para a sua segurança." },
  { id:35, topic:"Tesoura", emoji:"✂️",
    question:"Quando você quer cortar um galho duro ou um tecido grosso com a tesoura, em que parte da lâmina deve prender para cortar mais facilmente com o menor esforço?",
    choices:["Bem na ponta da lâmina","Na base da lâmina (o mais perto do parafuso ou da articulação)","No meio da lâmina","A força necessária é a mesma onde quer que você corte"],
    answerIndex:1,
    explanation:"A tesoura também é uma ferramenta muito prática que usa o princípio da alavanca que viemos aprendendo. O parafuso onde as duas lâminas se cruzam e ficam fixas é o apoio (o ponto de apoio). Quanto mais perto desse parafuso de apoio você cortar, muitas vezes mais forte fica a força que a sua mão que aperta transmite à lâmina. Por isso, com algo duro que não corta, tentar cortar na ponta da tesoura só machuca a sua mão, mas se você prender bem na base da lâmina, consegue cortar de uma tesourada com uma força surpreendentemente pequena. Conheça as características das suas ferramentas e use o ponto mais eficiente." },
  { id:36, topic:"Gravidade", emoji:"🍎",
    question:"Por que, entre deixar cair uma pedrinha sobre o pé da altura do joelho e deixá-la cair do alto do telhado da casa, a que cai do telhado causa um ferimento mais grave?",
    choices:["Porque a pedra fica mais fria lá em cima no telhado","Porque a gravidade, a força que puxa as coisas para a terra, deixa a pedra cada vez mais rápida quanto mais longa a queda, então o impacto na batida é mais forte","Porque uma pedra num lugar alto fica maior de tamanho","Porque o ar empurra a pedra para baixo"],
    answerIndex:1,
    explanation:"Tudo o que está sobre a terra recebe o tempo todo uma força chamada gravidade, que o atrai para o chão. Para algo num lugar alto, quanto mais longa a queda, mais a gravidade continua puxando e mais ele acelera (fica cada vez mais rápido). Um objeto que acelerou cria um enorme poder destrutivo (energia) no instante em que bate no chão ou no seu corpo. Da altura do joelho só dói, mas algo que cai de um telhado alto ou de um penhasco, mesmo uma pedra pequena ou uma ferramenta, vira uma arma capaz de tirar a vida de uma pessoa. Quando trabalhar perto de um lugar alto, deve verificar se não há ninguém embaixo e ter o máximo cuidado para não deixar cair nada." },
  { id:37, topic:"Equilíbrio", emoji:"⚖️",
    question:"Quando você carrega no ombro uma vara comprida (uma vara de carga) com dois potes de água pesados pendurados na frente e atrás, como pode andar com facilidade sem machucar o ombro?",
    choices:["Deixar a carga da frente muito pesada e a de trás leve","Deixar as cargas da frente e de trás exatamente do mesmo peso, e pôr o centro exato da vara sobre o ombro","Não pôr a vara no ombro; carregá-la só com as mãos","Deixar cair as cargas no chão alternadamente enquanto corre"],
    answerIndex:1,
    explanation:"Quando você carrega cargas penduradas de cada lado de uma vara comprida, se os pesos da frente e de trás estão desiguais, a vara pende para um lado e você tem de lutar para segurá-la com as mãos. Isso cansa rápido não só o ombro, mas também os braços e as costas. A resposta certa é deixar as cargas da frente e de trás exatamente com o mesmo equilíbrio. Assim o peso recai por igual bem acima do ombro pela vara, e você consegue carregar cargas pesadas só andando, sem usar músculo a mais para lutar contra a inclinação. Se uma carga for inevitavelmente mais leve, ajuste o equilíbrio deslizando a corda do lado leve para a ponta da vara." },
  { id:38, topic:"Resistência do ar", emoji:"🪂",
    question:"Você tem duas folhas de papel do mesmo tamanho e do mesmo peso. Uma é deixada como folha plana, a outra é amassada com a mão numa bola firme. Quando você as solta ao mesmo tempo de um lugar alto, qual chega primeiro ao chão?",
    choices:["A folha plana do jeito que está","O papel amassado numa bola firme","As duas chegam exatamente ao mesmo tempo","Muda toda vez conforme o vento"],
    answerIndex:1,
    explanation:"Mesmo para coisas do mesmo peso, quando caem pelo ar age um freio chamado resistência do ar, com o ar atrapalhando. A folha de papel plana tem uma superfície ampla, então agarra muito ar embaixo e cai só devagar, feito um paraquedas. Mas o papel amassado numa bolinha toca o ar numa superfície bem estreita, então quase não recebe freio e cai rápido, puxado reto para baixo pela gravidade. Um cata-vento girar com o vento, ou um guarda-chuva quase voar num dia de vento forte, também têm a ver com essa força de freio do ar." },
  { id:39, topic:"Elasticidade", emoji:"🏹",
    question:"Quando você dobra com toda a força um bambu duro e resistente, ou um galho de árvore flexível, e depois solta de repente, ele volta com força à forma original. Para que você pode usar essa propriedade (a elasticidade) para fazer uma ferramenta útil na vida diária?",
    choices:["Uma geladeira para a comida não apodrecer","Um arco e flecha para lançar uma flecha numa presa distante, ou uma armadilha que dispara coisas pesadas","Um filtro para limpar a água","Uma ferramenta para tingir a roupa de branco"],
    answerIndex:1,
    explanation:"A borracha e as molas, e também o bambu e os galhos de árvore, têm uma propriedade misteriosa chamada elasticidade: quando você aplica força a forma deles dobra, e quando solta procuram voltar à forma original a grande velocidade. Enquanto você o segura dobrado com a mão, a força que a pessoa aplica fica guardada um instante dentro dessa ferramenta como energia. No instante em que você solta, essa força guardada é liberada de uma vez, então você consegue lançar uma flecha muitas vezes mais longe, ou acionar uma armadilha, do que arremessando só com o braço. Aproveitando essa força que as plantas da natureza têm, a humanidade fabrica ferramentas para a caça e a vida diária desde a Antiguidade." },
  { id:40, topic:"Lubrificar", emoji:"🛢️",
    question:"As rodas de uma carroça, ou a dobradiça de uma porta, começaram a fazer um barulho chato de rangido e a ficar pesadas toda vez que você as movia. Se você pinga aqui algumas gotas de óleo, por que voltam a se mover suavemente?",
    choices:["Porque o óleo derrete o ferro e o deixa mais leve","Porque o óleo endurece e vira cola","Porque o óleo entra na fresta entre metal e metal e reduz muitíssimo a força de freio do atrito","Porque o cheiro do óleo espanta os insetos"],
    answerIndex:2,
    explanation:"Quando uma máquina ou ferramenta se move, há lugares onde o metal raspa forte e direto contra o metal. Age ali um freio muito forte chamado atrito e, se for deixado assim, ele se desgasta e quebra, ou é preciso muitíssima força para movê-lo. Quando você aplica óleo, forma-se uma fina película de óleo na pequena fresta do metal e impede que raspem direto. Como a força de freio some de uma vez, a ferramenta se move com uma suavidade impressionante e pouca força. Só de aplicar um pouco de óleo de cozinha ou óleo vegetal numa ferramenta, ela dura mais e reduz muito o desgaste das forças da pessoa." },
  { id:41, topic:"Raios", emoji:"⚡",
    question:"Quando está trovejando e você está do lado de fora, para onde é mais seguro fugir?",
    choices:["Bem embaixo de uma árvore alta","No meio de um campo aberto e amplo","Dentro de um prédio resistente, ou de um carro cercado de metal","Em pé, segurando um guarda-chuva grande"],
    answerIndex:2,
    explanation:"O raio tem uma forte tendência a cair sobre as coisas altas. Por isso, se você ficar sozinho em pé num campo aberto, se torna o objeto pontudo mais alto ao redor, e o perigo de um impacto direto fica altíssimo. Além disso, ficar bem embaixo de uma árvore alta é perigoso: o raio que cai na árvore pode saltar para o seu corpo, um fenômeno chamado descarga lateral, e causar ferimentos mortais. Os lugares mais seguros são o interior de um prédio resistente de concreto, ou o interior de um carro cercado por chapas de metal. Mesmo que o raio caia no carro, a eletricidade passa pelo metal de fora e desce até o chão, então as pessoas dentro ficam completamente seguras." },
  { id:42, topic:"Enchentes", emoji:"🌊",
    question:"Com chuva forte a rua virou um rio e você não tem escolha a não ser andar pela água para evacuar. O que é mais seguro calçar nos pés?",
    choices:["Descalço","Sandálias","Sapatos amarrados firmemente com cadarços","Botas de borracha"],
    answerIndex:2,
    explanation:"O fundo de uma rua alagada esconde muitos perigos invisíveis: vidro quebrado, latas afiadas, buracos de bueiro abertos. Descalço ou de sandálias você machuca os pés com facilidade e não consegue mais se mover. As botas de borracha parecem boas, mas quando a água entra por cima ficam pesadas como travesseiros de água, os pés não levantam de jeito nenhum, e isso impede você de andar ou faz você se afogar. O mais seguro são sapatos que não saem do pé e de sola dura: tênis amarrados firmemente com cadarços. Não ficam pesados mesmo que entre água, e protegem seus pés enquanto você anda com firmeza." },
  { id:43, topic:"Evacuação", emoji:"⛰️",
    question:"Uma enchente por chuva forte ou um tsunami chegou, e a água sobe até os seus pés. Para que direção é certo fugir?",
    choices:["Rio abaixo, onde a água corre rápido (um lugar baixo)","Um morro ou montanha alta por perto, ou um andar alto de um prédio resistente (um lugar alto)","A casa de um parente que fica longe","O porão da sua casa (mais baixo que o chão)"],
    answerIndex:1,
    explanation:"Numa enchente ou tsunami, a água se acumula com força tremenda, começando pelos lugares mais baixos. Se você se esconder num porão mais baixo que o chão, a água entra de uma vez pela entrada, você não consegue sair, e se afoga. Além disso, tentar fugir para longe andando de um lado para outro pode fazer você bater em árvores ou carros arrastados, ou ter os pés varridos pela correnteza forte e ser levado. Quando a água se aproxima, a regra de ouro não é ir para longe, mas se dirigir ao lugar alto mais próximo de onde você está agora. Subir num morro ou montanha por perto, ou no 2.º ou 3.º andar de um prédio resistente de concreto, e esperar a água baixar, é a escolha que protege a sua vida." },
  { id:44, topic:"Insolação", emoji:"🥵",
    question:"Num dia muito quente, com a luz do sol muito forte, o que é mais importante para prevenir a doença em que o corpo superaquece e você desmaia (insolação)?",
    choices:["Aguentar sem beber água","Passar barro frio pelo corpo todo","Descansar na sombra e beber água segura aos poucos, muitas vezes","Correr muito para suar"],
    answerIndex:2,
    explanation:"Se você fica muito tempo num lugar muito quente, a água e o sal do seu corpo saem como suor, e o corpo não consegue mais baixar o próprio calor. Este é o estado assustador chamado insolação. Para preveni-lo, é importante achar uma sombra fresca onde a luz do sol não bata diretamente em você, e descansar o corpo. E você precisa beber água segura, fervida e esfriada, aos poucos e muitas vezes, mesmo antes de sentir sede. Em vez de beber muito de uma vez, beber em pequenos goles frequentes faz o corpo absorver bem a água, e assim você passa o dia com energia e segurança mesmo sob o sol forte." },
  { id:45, topic:"Terremotos", emoji:"🪑",
    question:"Quando ocorre um terremoto e o chão e a sua casa começam a tremer com violência, qual é a primeira coisa a fazer dentro do quarto?",
    choices:["Sair correndo para fora em pânico","Se esconder embaixo de uma escrivaninha resistente e proteger a cabeça e o corpo","Fechar bem as janelas e olhar para fora","Enfiar muitas coisas numa bolsa"],
    answerIndex:1,
    explanation:"Quando ocorre um terremoto, o mais perigoso é caírem objetos de cima e tombarem os móveis. Se você sai correndo para fora em pânico, das partes altas dos prédios podem cair vidros quebrados e telhas que batem na sua cabeça: um risco altíssimo de ferimento grave. Quando sentir o tremor, primeiro se enfie ali mesmo embaixo de uma escrivaninha ou cama resistente, segure firme os pés da escrivaninha e proteja a cabeça e o corpo. Se não houver onde se esconder, cubra a cabeça com força com uma almofada, uma bolsa ou os próprios braços, fique pequeno no centro do quarto onde móveis não caiam em cima de você, e espere quieto até o tremor parar por completo: isso é o mais seguro." },
  { id:46, topic:"Raios", emoji:"⚡",
    question:"Quando troveja por perto, qual é a ação mais perigosa de se fazer ao ar livre?",
    choices:["Segurar um brinquedo de plástico","Segurar uma vara longa de metal ou uma vara de pesca erguida bem alto em direção ao céu","Vestir roupa de tecido","Calçar sapatos de madeira"],
    answerIndex:1,
    explanation:"O raio tem a assustadora tendência de cair de forma concentrada sobre as coisas altas e de ponta afiada. Por isso, se ao ar livre você segura uma vara longa de metal, uma vara de pesca ou um guarda-chuva longo erguendo bem alto em direção ao céu, ela vira como uma antena que chama o raio, e ele cai direto em você. Quando ouvir os trovões roncarem, deite imediatamente na horizontal no chão qualquer vara longa que estiver segurando, abaixe a própria postura o máximo possível e agache com a cabeça para baixo. E depois evacue de imediato para dentro de um prédio seguro." },
  { id:47, topic:"Deslizamentos", emoji:"⚠️",
    question:"Quando chove forte sem parar perto de uma montanha, qual é um sinal perigoso de que a montanha pode desabar (um deslizamento de terra)?",
    choices:["A água do rio de repente fica preta e turva, e descem muitos pedaços de madeira","Caem pequenas pedras da montanha aos poucos","Do fundo do chão se ouve um som estranho, como um ronco da terra","Todos esses são sinais perigosos"],
    answerIndex:3,
    explanation:"Quando a chuva forte cai sobre uma montanha, a terra absorve uma enorme quantidade de água, e em um momento o penhasco ou a montanha inteira desaba de uma vez: um grande desastre chamado deslizamento de terra ou fluxo de lama e pedras. Pouco antes de acontecerem, a natureza sempre dá vários sinais de aviso. A água do rio ficar turva de repente e aumentar a madeira arrastada é prova de que lá em cima a terra começa a desabar. Além disso, se caem pedrinhas da montanha, ou se ouve um som assustador vindo do chão, é o sinal de que a montanha inteira vai começar a se mover. Se você encontrar ou sentir mesmo um desses sinais, deve se afastar daquele lugar um segundo antes e fugir para um lugar alto e resistente." },
  { id:48, topic:"Enchentes", emoji:"🦯",
    question:"Quando você tem que andar pela água de uma enchente, numa rua onde a lama deixa o chão totalmente invisível, como deve andar para ficar seguro?",
    choices:["Correr a toda velocidade para escapar rápido","Usar uma vara longa para cutucar e conferir que o chão é seguro, um passo de cada vez","Fechar os olhos e ir reto para a frente","Tirar toda a roupa e avançar nadando"],
    answerIndex:1,
    explanation:"Depois de uma enchente, a água da rua está marrom e turva, com lama e lixo misturados, então você não vê nada de como está o chão. Na verdade, debaixo da água a tampa de um bueiro pode ter se soltado deixando um buraco fundo, ou o chão pode ter se desgastado num valo fundo. Se você corre ou anda sem perceber, pode cair num buraco fundo num instante e afundar na água. Ao andar pela água, segure sempre uma vara longa e resistente como uma bengala e, antes de dar o próximo passo, bata no chão com a vara para conferir se há um buraco, avançando devagar e com cuidado: esse é o jeito de andar que protege a sua vida." },
  { id:49, topic:"Tornados", emoji:"🌪️",
    question:"Quando um tornado (um vento intenso que gira a uma velocidade tremenda) se aproxima, onde dentro da casa é mais seguro se esconder?",
    choices:["Bem ao lado de uma janela com boa vista para fora","No terraço onde o vento é gostoso","Um quarto resistente sem janelas, ou um banheiro ou armário no centro da casa","Deitado numa cama grande"],
    answerIndex:2,
    explanation:"O tornado é a rajada mais violenta da Terra, forte o bastante para arrancar o telhado de uma casa ou erguer no ar grandes árvores e carros. Quando um tornado se aproxima, o mais assustador é um objeto voador atravessar o vidro da janela e os cacos de vidro se espalharem pelo quarto todo a uma velocidade tremenda. Por isso ficar perto de uma janela significa ferimentos graves. O lugar mais seguro é onde as paredes são mais grossas e não há nenhuma janela: um banheiro no centro da casa, um quarto resistente ou um armário. Tranque-se ali, cubra a cabeça com uma almofada ou cobertor, encolha-se e espere quieto a tempestade passar: esse é o jeito certo de se proteger." },
  { id:50, topic:"Incêndio", emoji:"🔥",
    question:"Quando há um incêndio e muita fumaça se acumula no quarto, como você deve escapar para fora?",
    choices:["Ficar bem ereto e correr a toda velocidade","Ficar numa postura baixa, engatinhando no chão, cobrir a boca com um pano e escapar","Fechar todas as janelas para prender a fumaça","Se cobrir com um cobertor grande e dormir na cama"],
    answerIndex:1,
    explanation:"A fumaça de um incêndio contém muito veneno nocivo (como o monóxido de carbono) que faz a pessoa desmaiar no instante em que o respira. Como a fumaça é quente, no quarto ela se acumula primeiro a partir do teto (a parte alta), e o ar relativamente limpo fica por último perto do chão. Por isso, se você fica ereto, respira em cheio a fumaça venenosa mais densa e não consegue mais se mover. Ao escapar, mantenha uma postura baixa com o peito perto do chão, pressione com força um pano ou roupa molhada sobre a boca e o nariz, respire o ar perto do chão e saia rápido para fora: esse é o jeito certo de escapar." },
  { id:51, topic:"Tsunami", emoji:"🌊",
    question:"Quando você está perto do mar e sente um terremoto violento, qual é a coisa mais importante que deve fazer de imediato?",
    choices:["Ir ver se há peixes no mar","Voltar para casa para juntar todas as suas coisas","Se afastar da costa e subir rápido num morro alto ou num terreno alto e resistente","Ficar sentado quieto na praia de areia"],
    answerIndex:2,
    explanation:"Quando ocorre um grande terremoto debaixo do mar, o fundo do mar se move muito e toda a água ao redor avança como uma onda gigante em forma de muro: um grande desastre chamado tsunami. Diferente das ondas comuns, o tsunami tem um peso e uma força destrutiva tremendos, capazes de arrastar prédios e casas num instante. Além disso, antes de o tsunami chegar, a maré pode recuar de repente e deixar ver a areia, mas se você for olhar por curiosidade, no momento seguinte é engolido pela grande onda. Se sentir o tremor perto do mar, não pegue nada, se afaste do mar um segundo antes e fuja para um morro ou montanha alta, ou um andar alto de um prédio resistente. Depois que você vê a onda, já não dá para escapar." },
  { id:52, topic:"Frio", emoji:"🧥",
    question:"Quando você pode se perder num lugar muito frio no inverno, qual é a melhor ação para manter o calor do corpo e sobreviver?",
    choices:["Beber muita água fria","Ficar com a roupa molhada do jeito que está","Se esconder onde o vento não bate e vestir muitas camadas de roupa ou pano","Deitar para dormir direto na neve"],
    answerIndex:2,
    explanation:"O corpo humano, se a temperatura cai demais, não consegue mais se mover e perde a vida (hipotermia). Sobretudo o vento e a roupa molhada são inimigos perigosos que roubam o calor do corpo num instante. Para se proteger num lugar frio, a prioridade máxima é se esconder onde o vento não bate de jeito nenhum, como atrás de uma grande rocha ou dentro de um prédio. Depois, se a roupa estiver molhada, troque sem falta por uma seca e vista muitas camadas da roupa, pano ou papel que tiver. Sobrepor panos cria uma camada de ar quente entre eles: uma parede mágica que não deixa o calor do seu corpo escapar. Dormir direto na neve rouba calor, então pôr capim ou papelão no chão para sentar também é uma sabedoria importante." },
  { id:53, topic:"Vulcões", emoji:"🌋",
    question:"Quando um vulcão próximo (uma montanha que solta fogo e lama quentes) entra em erupção de repente, como você se protege das cinzas e pedras que caem do céu?",
    choices:["Olhar para o céu e observar com atenção o que cai","Entrar num prédio resistente (como uma casa de concreto) e cobrir a boca e o nariz com um pano","Pular num rio próximo e nadar","Correr a toda velocidade em direção à montanha"],
    answerIndex:1,
    explanation:"Quando um vulcão entra em erupção, do topo caem do céu pesada lava em brasa e grandes pedras a uma velocidade assustadora. Se elas batem na sua cabeça é fatal, então você deve se esconder logo dentro de um prédio resistente de concreto ou parecido. Além disso, a cinza vulcânica que o vulcão solta não é areia comum, mas como espinhos de vidro finamente triturado. Respirá-la machuca os pulmões e você não consegue respirar, e se entra nos olhos causa dor forte e você não consegue abri-los. Uma vez dentro do prédio, feche bem as janelas, cubra com firmeza a boca e o nariz com uma máscara ou um pano molhado de água, e proteja-se de jamais respirar a cinza suja." },
  { id:54, topic:"Neblina", emoji:"🌫️",
    question:"Quando a neblina (uma bruma branca que se espalha pelo ar) fica muito densa e você não vê nada à frente, qual é o maior perigo ao andar?",
    choices:["Parar onde você está","Deixar de ouvir os sons ao redor","Não conseguir ver a sua própria posição nem lugares perigosos como penhascos, e por isso se perder ou cair","A roupa ficar um pouco úmida"],
    answerIndex:2,
    explanation:"Quando se forma neblina densa, até a paisagem a só alguns metros fica toda branca e você não vê nada. Se você se força a continuar andando assim, o seu senso de direção, para onde você vai, fica completamente paralisado, e isso pode levar a grandes acidentes: se embrenhar numa floresta profunda e perigosa, ou não perceber um penhasco ou rio fundo bem na frente e despencar de cabeça até a morte. Quando não enxergar à frente, nunca deve avançar à força. A defesa mais segura é parar onde você está num lugar de pisada firme, como o meio de uma estrada larga e segura, e esperar quieto até a neblina se dissipar e você ver bem ao redor de novo." },
  { id:55, topic:"Desmoronamento", emoji:"🪨",
    question:"Quando você está perto de um alto muro de terra (um penhasco) depois de ter caído chuva forte, com o que deve absolutamente tomar cuidado?",
    choices:["A água da chuva pode se infiltrar no penhasco e ele pode desabar de repente (um desmoronamento), então se afaste de imediato","Subir no alto do penhasco e brincar alegremente","Armar uma barraca bem ao pé do penhasco e dormir","Jogar muita água contra a parede do penhasco"],
    answerIndex:0,
    explanation:"Um penhasco ou uma velha encosta de terra, depois de chuva forte, tem uma enorme quantidade de água acumulada ao limite dentro da terra e está num estado muito frágil, mole como uma esponja. Mesmo depois de a chuva parar, de horas a dias depois, ocorre com frequência um desmoronamento em que a parede inteira cai de uma vez como se explodisse, sem nenhum som. Se você brinca ou dorme ao pé do penhasco, fica soterrado sob muitas toneladas de terra pesada num instante e não dá mais para salvar. Durante a chuva forte, e durante os dias depois de a chuva parar, cumpra sempre a regra: nunca se aproxime de um alto muro de terra ou penhasco, se afaste de imediato." },
  { id:56, topic:"Evacuação", emoji:"🏃",
    question:"Quando o rio perto da sua casa cresce cada vez mais com a chuva forte e está prestes a transbordar, quando você deve começar a evacuar?",
    choices:["Depois que a água entrar dentro de casa","Cedo, enquanto ainda há luz lá fora e não há água acumulada na rua, enquanto é seguro","Esperar quieto até a água do rio transbordar por completo","Pensar nisso depois de se deitar na cama para dormir"],
    answerIndex:1,
    explanation:"Tentar evacuar depois que o rio transborda e a água começa a se acumular na rua é a decisão mais perigosa e tardia demais. Quando a água se acumula até a altura do joelho na rua, até um homem adulto é arrastado pela força forte da água e não consegue andar de jeito nenhum. Além disso, quando escurece à noite, você não distingue mais onde é a rua e onde é o rio, e cai no rio e é levado no meio da evacuação. O momento mais certo para começar a evacuar é enquanto ainda há luz lá fora e não há água acumulada aos seus pés, enquanto é seguro. Assim que sentir mesmo um pouco de perigo do rio que cresce, reduza a bagagem ao mínimo e parta cedo em direção a um abrigo alto e seguro: essa é a sabedoria que protege com certeza a sua vida." },
  { id:57, topic:"Choque elétrico", emoji:"🔌",
    question:"Depois de um terremoto ou chuva forte, você encontra em casa um fio elétrico rompido soltando faíscas. Por que não deve tocá-lo de jeito nenhum?",
    choices:["Porque as mãos vão ficar sujas de lama preta","Porque a forte eletricidade que corre no fio passa para o seu corpo e causa ferimentos graves, como o coração parar (choque elétrico)","Porque o fio está frio como gelo","Porque o quarto vai ficar escuro"],
    answerIndex:1,
    explanation:"De um fio rompido, ou de um aparelho elétrico molhado de água, pode estar vazando uma eletricidade muito forte invisível ao olho humano. Se você o toca com a mão sem saber, a eletricidade do fio atravessa o seu corpo num instante e desce até o chão. Isso se chama choque elétrico. Receber eletricidade forte não só queima o seu corpo, mas pode parar o seu coração de vez, um acidente fatal num instante. Sobretudo quando o seu corpo ou as mãos estão molhados de água, a eletricidade passa para o seu corpo muitas vezes mais fácil, o que é ainda mais perigoso. Se encontrar um fio soltando faíscas ou um fio rompido, nunca se aproxime, não toque e avise um adulto." },
  { id:58, topic:"Tufões", emoji:"🌀",
    question:"Quando sopra um vento forte e feroz (um tufão ou ciclone), por que sair para fora é perigoso a ponto de pôr a vida em risco?",
    choices:["Porque o ar de fora não tem um gosto muito bom","Porque placas de lojas, telhas do telhado e galhos grandes de árvore voam e batem na sua cabeça","Porque a sua roupa favorita fica suja de lama","Porque receber vento forte pelo corpo todo faz engordar"],
    answerIndex:1,
    explanation:"Numa tempestade feroz como um tufão ou ciclone, a força do vento fica muito além do que os humanos imaginam. Ser levado pelo próprio vento já é perigoso, mas o mais assustador é tudo o que há na cidade virar uma arma e voar na sua direção. Pesadas placas de lojas, telhas duras de telhado, galhos quebrados de árvore e afins vêm voando de lado a uma velocidade como uma faca afiada ou uma bala. Se mesmo um deles bate no seu corpo, é um ferimento fatal. Enquanto se ouve o som do vento forte, por mais que você tenha o que fazer, não deve sair para fora de jeito nenhum. Ficar numa casa segura, longe das janelas, e esperar quieto a tempestade passar por completo é a ação correta." },
  { id:59, topic:"Tempestades de areia", emoji:"🏜️",
    question:"Quando ocorre uma tempestade de areia (areia e poeira levantadas por vento forte), o que você deve fazer para proteger os olhos e os pulmões?",
    choices:["Abrir bem os olhos e a boca e receber o vento","Cobrir com firmeza o rosto, a boca e o nariz com um lenço ou pano, e se esconder dentro de um prédio resistente","Sair para fora e apostar corrida com os amigos","Olhar para o céu para ver até onde a areia voa"],
    answerIndex:1,
    explanation:"Uma tempestade de areia que ocorre perto de um deserto ou numa região seca é uma grande tempestade que levanta com vento forte centenas de milhões de finos grãos de areia e poeira suja. Se você respira essa areia e essa poeira do jeito que estão, a areia se acumula no fundo dos seus pulmões e você tosse com violência, uma doença grave em que não consegue respirar. Além disso, os olhos podem se machucar com a areia e você não enxerga. Quando uma tempestade de areia se aproximar, evacue logo para dentro de um prédio resistente e feche janelas e portas sem frestas. E depois, sobreponha muitas vezes o lenço ou o pano de roupa que tiver e cubra o rosto todo, sobretudo a boca e o nariz, com força para fazer uma máscara que impeça a entrada da areia. Até a tempestade passar, proteja-se respirando em silêncio só o ar que passa pelo pano." },
  { id:60, topic:"Enchentes", emoji:"🌊",
    question:"Durante uma enchente em que a água cheia de lama invade a casa, por que estar no porão (um cômodo mais baixo que o chão) é absolutamente proibido?",
    choices:["Porque o porão é mais fresco e confortável que os outros cômodos","Porque a água com lama da rua de cima entra de uma vez como uma cachoeira, a saída fica bloqueada, e você se afoga num instante","Porque o porão fica escuro quando falta luz","Porque às vezes ratos pequenos moram no porão"],
    answerIndex:1,
    explanation:"Um porão ou um cômodo semienterrado mais baixo que o chão se transforma no lugar mais mortal e perigoso do mundo quando ocorre uma enchente. A água com lama que transbordou na rua de cima entra de uma vez pela escada e pelas janelas do porão com a força e o peso tremendos de uma cachoeira. A força da água que desce a escada é intensa, e nem a força de um adulto consegue resistir a ela para subir. Além disso, o peso da água empurra a porta do porão por fora, e fica absolutamente impossível abri-la por dentro. O cômodo se enche de água num instante, a rota de fuga some por completo, e você se afoga. Quando a chuva apertar, a regra de ouro absoluta é: nunca se aproxime do porão, suba agora mesmo para um andar de cima." }
];
