/*
 * Wise World - Quiz data (English)
 * ⚠ AI translation from the Japanese source. Review by a native speaker /
 *    health expert is recommended before relying on it.
 * Keep id / answerIndex / emoji identical across all languages.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).en = [
  { id:1, topic:"Safe water", emoji:"💧",
    question:"Which water is safe and won't make your tummy hurt?",
    choices:["River water","Well water","Water boiled hard over a fire","Rain water"],
    answerIndex:2,
    explanation:"River water, well water, and rain water may look perfectly clear and clean, but they can be full of tiny living things too small for our eyes to see (germs and viruses). If you drink that water as it is, it can cause terrible stomach pain or a serious, life-threatening illness. But when you put water over a fire and boil it hard until it bubbles, the heat kills all of those harmful living things. That is why water that has been boiled well and then cooled is the safest water in the world, and the water you can drink with confidence." },
  { id:2, topic:"Washing hands", emoji:"🧼",
    question:"What should you do before eating?",
    choices:["Wash your hands with water and soap","Wipe your hands on your clothes","Do nothing","Touch the soil"],
    answerIndex:0,
    explanation:"Our hands touch many tools and the ground every day, so without noticing it we pick up many invisible germs. If you touch food with those hands, the germs move onto the food, and you swallow them into your body along with the food. Wiping your hands on dirty clothes, or just splashing them with water, will not remove the germs — they cling on. Only by using soap and scrubbing your palms, the backs of your hands, and between your fingers with a good lather, then rinsing with water, can you truly wash the germs away." },
  { id:3, topic:"Washing hands", emoji:"🚽",
    question:"What should you do after using the toilet?",
    choices:["Go and play right away","Wash your hands with water and soap","Rub your hands on your clothes","Wipe your hands on your trousers"],
    answerIndex:1,
    explanation:"After going to the toilet, very strong germs from stool and urine that cause disease stick to your hands easily. If you go off to play without washing, those germs get onto the doorknobs and toys you touch, and pass the illness to the next friend or family member who touches them. And if you touch your own mouth or eyes with those hands, you can make yourself sick too. No matter how much of a hurry you are in, always washing your hands well with water and soap after the toilet is a rule that protects your life and the lives of those around you." },
  { id:4, topic:"Health", emoji:"💧",
    question:"When your tummy is upset and your stool turns watery (diarrhoea), what matters most?",
    choices:["Eat a lot of food","Drink nothing","Drink plenty of safe water","Run around and play"],
    answerIndex:2,
    explanation:"When your tummy is upset and watery stool (diarrhoea) keeps coming out, precious water and nourishment are being lost from your body again and again. This is called dehydration. When the body runs short of water, the important functions that keep us alive begin to stop, and small children especially can suddenly lose their lives. When you have diarrhoea, rather than forcing down solid food, the best treatment is first to replace the water you have lost. By drinking safe, boiled-and-cooled water little by little, many times over, you can keep your strength and protect your life." },
  { id:5, topic:"Treating wounds", emoji:"🩹",
    question:"When you fall and bleed, what should you do first?",
    choices:["Put soil on it","Wash it well with clean water","Leave it alone and do nothing","Rub it with a leaf"],
    answerIndex:1,
    explanation:"When you fall and get a wound that bleeds, the wound is covered with dirt, mud, and dust from the ground, along with many germs. If you believe old sayings and smear soil on it, rub it with a dirty leaf, or just leave it alone, the germs go deep into the wound and multiply. Then the wound swells up red and hurts badly, and in the worst case an arm or leg can rot and stop moving. When you are hurt, the first correct step to keep a wound from becoming serious is to use clean, safe water nearby to rinse the mud and dirt off the wound with a strong flow." },
  { id:6, topic:"Food", emoji:"🦠",
    question:"What happens when food goes rotten (spoils)?",
    choices:["It becomes tasty","It rots and gives you a stomach ache","It becomes hard","Nothing changes"],
    answerIndex:1,
    explanation:"Food naturally holds a tiny number of invisible microbes from the start. In a cool place the microbes cannot be active, but if you leave food in a warm, hot place for a long time, it becomes the perfect environment for them, and within a few hours they multiply into millions — a frightening number. When microbes multiply this much and the shape and nature of the food change, we say it has gone rotten (spoiled). Rotten food holds the strong poison the microbes have made, so eating it brings severe stomach pain, diarrhoea, and nausea, and harms your body." },
  { id:7, topic:"Food", emoji:"👃",
    question:"What is a sign that food has gone bad?",
    choices:["A strange smell or taste","A red colour","Something cold","Something well cooked"],
    answerIndex:0,
    explanation:"You can use your own nose and tongue to check whether food has gone bad and is no longer safe. If it has an unusual sour smell or a sharp, unpleasant smell, or a strange taste when you put a little in your mouth, or if it is sticky and stringy, that is proof that germs have multiplied greatly and poison has formed. If you force yourself to eat it because it would be a waste, you put your life in danger from severe food poisoning. If the smell or taste is even a little suspicious, decide to throw it away and never swallow it." },
  { id:8, topic:"Food", emoji:"🪰",
    question:"What should you do with food a fly has landed on?",
    choices:["Eat it as it is","Don't eat the part the fly touched (throw it away)","Raise the fly as a pet","Stare at it"],
    answerIndex:1,
    explanation:"The insect we call a fly likes to walk around very dirty places full of germs, such as animal droppings, dead bodies, and rubbish dumps. Because of this, frightening disease-causing germs stick thickly to a fly's thin legs and body. When such a fly lands on our food, in that instant the germs on its legs move onto the food. If you eat the spot it touched, you are indirectly putting droppings and rubbish germs into your mouth, which can cause serious illness. Even if it feels wasteful, it is safer to cut away and throw out the part of the food the fly landed on." },
  { id:9, topic:"Preventing disease", emoji:"🦟",
    question:"What happens if you leave water standing for a long time?",
    choices:["The water becomes clean","Harmful mosquitoes multiply","Your money grows","Nothing happens"],
    answerIndex:1,
    explanation:"Old water that stays in one place without flowing becomes the perfect spot for the insect called the mosquito to lay its eggs. If you leave buckets, old tyres, or empty cans around your yard or house holding water, hundreds and thousands of new mosquitoes are born there and fly all around. When a mosquito sucks a person's blood, it injects into the body the germs of very frightening, life-threatening diseases such as malaria and dengue fever. Getting rid of pools of water around the house is an important plan to protect your family from these terrible diseases." },
  { id:10, topic:"Cleanliness", emoji:"✋",
    question:"When your nails are long, what builds up inside them?",
    choices:["Your hands get stronger","Black dirt and germs collect under the nails","Food tastes better","Nothing changes"],
    answerIndex:1,
    explanation:"When your fingernails grow long, black mud and dirt pack tightly into the narrow gap between the nail and the skin while you play in the soil, help out, or work. The dirt that gets into this gap does not come off easily with ordinary hand-washing, and it becomes the perfect hideout for germs. With long nails, when you eat with your hands or touch your own face or a wound, those hidden germs easily get into your body. Keeping your nails cut short at all times is a basic way to prevent illness." },
  { id:11, topic:"Cough manners", emoji:"🤧",
    question:"What should you do when you cough or sneeze?",
    choices:["Do it towards someone's face","Cover your mouth and nose with your hand or sleeve","Shout loudly","Do nothing"],
    answerIndex:1,
    explanation:"When you have a cold or a lung illness, a single cough or sneeze sends tiny droplets of water you cannot see flying out of your mouth and nose, several metres away with great force. Each droplet can contain tens of thousands of disease germs. If you cough towards someone's face you pass the illness directly, and if you cover nothing the germs spread through the air and everyone in the same room can get sick. When you cough, firmly covering your mouth and nose with your sleeve or hand keeps you from spreading illness to the precious family and friends around you." },
  { id:12, topic:"Cleanliness", emoji:"🗑️",
    question:"What happens if you leave rubbish lying near the house?",
    choices:["The house becomes clean","Harmful rats and insects gather and disease spreads","The rubbish turns into flowers","Nothing goes wrong"],
    answerIndex:1,
    explanation:"If you throw food scraps and kitchen rubbish away right next to your house, the smell draws many creatures such as rats, flies, and cockroaches. These creatures usually walk around sewers and filthy places, so they carry many frightening disease germs on their bodies. As they increase around the rubbish, they eventually get into the house and dirty the precious food and drinking water inside. Rubbish must be thrown away in a set place far enough from the house, or buried deep in a hole in the ground." },
  { id:13, topic:"Healthy teeth", emoji:"🪥",
    question:"What is the main reason for brushing your teeth?",
    choices:["To paint the teeth white","To reduce cavity germs in the mouth and protect the teeth","To make your jaw strong","To fill your stomach"],
    answerIndex:1,
    explanation:"After you eat, small scraps of food always remain in the gaps and on the surface of your teeth. The invisible creatures called cavity germs that live in our mouths love these food scraps. If you leave the scraps there, the cavity germs feed on them and make a strong acid that dissolves the teeth. Because of this acid, holes slowly open in the teeth — which should be the hardest part of the body — and when it reaches the nerve it brings pain so fierce you cannot sleep at night. Brushing your teeth after eating is absolutely necessary work to remove the germs' food and protect your teeth." },
  { id:14, topic:"Preventing injury", emoji:"👟",
    question:"Why do you wear shoes when you walk outside?",
    choices:["To make your feet bigger","To stop worms and germs in the soil from entering through the skin of your feet","To practise running","To keep your clothes clean"],
    answerIndex:1,
    explanation:"When you walk barefoot on soil and mud, tiny creatures hiding in the ground that are too small to see (the larvae of parasites) and germs can break through the soft skin of the soles of your feet and enter your body on their own. The worms that get in settle in your tummy (intestines) and steal the nourishment you eat, making you badly anaemic, stopping your growth, and draining your energy. Wearing shoes also protects you from serious injury caused by stepping on broken glass, sharp stones, or wooden thorns. Always wear shoes or sandals when you go outside." },
  { id:15, topic:"Cleanliness", emoji:"👕",
    question:"What happens if you keep wearing dirty clothes?",
    choices:["The clothes get stronger","Your skin gets itchy or you become ill","Your body gets stronger","Nothing changes"],
    answerIndex:1,
    explanation:"If you keep wearing clothes soaked with sweat or stained with mud for many days, mould and germs feed on the human sweat and skin oil on the clothes and multiply explosively inside the fibres. As those dirty clothes keep rubbing against your skin, the skin can swell up red, become very itchy, or develop a sore, oozing illness. Dirty clothes can be completely rid of germs by washing them clean with water and soap and drying them well in the sunlight (ultraviolet rays). Always wearing clean clothes is important for protecting the barrier of your skin." },
  { id:16, topic:"Cleanliness", emoji:"🚿",
    question:"What is good about washing your body?",
    choices:["Your skin gets clean and you prevent skin disease","You grow taller","Your hair falls out","You get hungry"],
    answerIndex:0,
    explanation:"Every day invisible oil (sebum) and sweat come out of human skin, and outside dust and soil mix in, making the whole body dirty. If you leave this dirt for many days, bad germs multiply on the surface of the skin, and you can get terrible boils or a frightening illness where the skin festers and rots. By regularly washing your whole body gently with water and soap and resetting the old oil and dirt, your skin is kept healthy and strong, building a powerful barrier that keeps illness from getting in from outside." },
  { id:17, topic:"Safe water", emoji:"💧",
    question:"When you only have muddy water, how can you drink it safely?",
    choices:["Drink it as it is","Filter out the mud with cloth or sand, then boil it over a fire","Just leave it in the sun and drink it","Drink only a little"],
    answerIndex:1,
    explanation:"When all you can get is muddy water, drinking it as it is sends a huge amount of germs into your body along with the mud and causes serious illness. Making it safe takes two pieces of wisdom. First, pass the water through fine, clean cloth, or a container packed with sand and small stones, to filter out the mud and large bits and make the water clear. But being clear is not enough — invisible germs are still alive. After that, you must put it over a fire and boil it hard until it bubbles, so the heat wipes out the germs and it finally becomes safe drinking water. With wisdom, you can make life-saving water even from muddy water." },
  { id:18, topic:"Babies", emoji:"🍼",
    question:"What is the best nourishment for a baby?",
    choices:["Cow's milk (raw)","The mother's milk (breast milk)","River water","Sugar water"],
    answerIndex:1,
    explanation:"A newborn baby's body is very weak and has almost no power to beat disease germs. A mother's milk (breast milk) not only holds perfect nourishment for the baby to grow, but also large amounts of a special protective ingredient called immunity that guards against illness. Breast milk also comes straight from the body, so it never touches dirty outside water or germs on containers — it is the cleanest and safest in the world. Other animals' raw milk, river water, or sugar water can wreck a baby's delicate stomach and intestines and take its life, so you must never give them." },
  { id:19, topic:"Preventing disease", emoji:"😷",
    question:"What should you do near someone with a bad cough?",
    choices:["Keep a little distance, and turn your face away when passing","Take a big breath in front of them","Shake hands with them","Stand right in front of them"],
    answerIndex:0,
    explanation:"Serious breathing illnesses such as tuberculosis (TB) float in the air for a long time, carried on the tiny invisible droplets that scatter when a sick person coughs. If you take a big breath nearby, or stay close for a long time, you breathe those germs deep into your own lungs and can catch the same serious illness. When someone has a bad cough, it is not about being unkind or treating them differently; to protect yourself, keep several metres of distance, and when passing, turn your face away and breathe out gently — this is the right way for both of you to stay safe." },
  { id:20, topic:"Fresh air", emoji:"🪟",
    question:"How do you keep the air in a room clean?",
    choices:["Shut all the doors and windows tight","Open windows and doors to let the air change","Everyone shout loudly together","Nothing changes"],
    answerIndex:1,
    explanation:"When many people gather in a small, closed room, the disease germs and viruses someone carries build up more and more in the air, until the air in the room is full of germs. If you stay in that room a long time, everyone breathes the dirty air and gets sick together (a group infection). By opening windows and doors in two or more places to exchange the fresh outside air with the dirty air in the room (ventilating), you can drive the germs out of the air and protect the health of everyone in the room." }
];
