/*
 * Wise World - Quiz data (English)
 * ⚠ AI translation from the Japanese source. Review by a native speaker /
 *    health expert is recommended before relying on it.
 * Keep id / answerIndex / emoji identical across all languages.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).en = [
  { id:1, topic:"Safe water", emoji:"💧",
    question:"Which water is safe and won't make your tummy hurt?",
    choices:["River water","Well water","Water boiled hard over a fire","Rain water"],
    answerIndex:2,
    explanation:"River water, well water, and rain water may look perfectly clear and clean, but they can be full of tiny living things too small for our eyes to see (germs and viruses). If you drink that water as it is, it can cause terrible stomach pain or a serious, life-threatening illness. But when you put water over a fire and boil it hard until it bubbles, the heat kills all of those harmful living things. That is why water that has been boiled well and then cooled is the safest water in the world, and the water you can drink with confidence." },
  { id:2, topic:"Washing hands", emoji:"🧼",
    question:"What should you do before eating?",
    choices:["Wash your hands with water and soap","Wipe your hands on your clothes","Do nothing","Touch the soil"],
    answerIndex:0,
    explanation:"Our hands touch many tools and the ground every day, so without noticing it we pick up many invisible germs. If you touch food with those hands, the germs move onto the food, and you swallow them into your body along with the food. Wiping your hands on dirty clothes, or just splashing them with water, will not remove the germs — they cling on. Only by using soap and scrubbing your palms, the backs of your hands, and between your fingers with a good lather, then rinsing with water, can you truly wash the germs away." },
  { id:3, topic:"Washing hands", emoji:"🚽",
    question:"What should you do after using the toilet?",
    choices:["Go and play right away","Wash your hands with water and soap","Rub your hands on your clothes","Wipe your hands on your trousers"],
    answerIndex:1,
    explanation:"After going to the toilet, very strong germs from stool and urine that cause disease stick to your hands easily. If you go off to play without washing, those germs get onto the doorknobs and toys you touch, and pass the illness to the next friend or family member who touches them. And if you touch your own mouth or eyes with those hands, you can make yourself sick too. No matter how much of a hurry you are in, always washing your hands well with water and soap after the toilet is a rule that protects your life and the lives of those around you." },
  { id:4, topic:"Health", emoji:"💧",
    question:"When your tummy is upset and your stool turns watery (diarrhoea), what matters most?",
    choices:["Eat a lot of food","Drink nothing","Drink plenty of safe water","Run around and play"],
    answerIndex:2,
    explanation:"When your tummy is upset and watery stool (diarrhoea) keeps coming out, precious water and nourishment are being lost from your body again and again. This is called dehydration. When the body runs short of water, the important functions that keep us alive begin to stop, and small children especially can suddenly lose their lives. When you have diarrhoea, rather than forcing down solid food, the best treatment is first to replace the water you have lost. By drinking safe, boiled-and-cooled water little by little, many times over, you can keep your strength and protect your life." },
  { id:5, topic:"Treating wounds", emoji:"🩹",
    question:"When you fall and bleed, what should you do first?",
    choices:["Put soil on it","Wash it well with clean water","Leave it alone and do nothing","Rub it with a leaf"],
    answerIndex:1,
    explanation:"When you fall and get a wound that bleeds, the wound is covered with dirt, mud, and dust from the ground, along with many germs. If you believe old sayings and smear soil on it, rub it with a dirty leaf, or just leave it alone, the germs go deep into the wound and multiply. Then the wound swells up red and hurts badly, and in the worst case an arm or leg can rot and stop moving. When you are hurt, the first correct step to keep a wound from becoming serious is to use clean, safe water nearby to rinse the mud and dirt off the wound with a strong flow." },
  { id:6, topic:"Food", emoji:"🦠",
    question:"What happens when food goes rotten (spoils)?",
    choices:["It becomes tasty","It rots and gives you a stomach ache","It becomes hard","Nothing changes"],
    answerIndex:1,
    explanation:"Food naturally holds a tiny number of invisible microbes from the start. In a cool place the microbes cannot be active, but if you leave food in a warm, hot place for a long time, it becomes the perfect environment for them, and within a few hours they multiply into millions — a frightening number. When microbes multiply this much and the shape and nature of the food change, we say it has gone rotten (spoiled). Rotten food holds the strong poison the microbes have made, so eating it brings severe stomach pain, diarrhoea, and nausea, and harms your body." },
  { id:7, topic:"Food", emoji:"👃",
    question:"What is a sign that food has gone bad?",
    choices:["A strange smell or taste","A red colour","Something cold","Something well cooked"],
    answerIndex:0,
    explanation:"You can use your own nose and tongue to check whether food has gone bad and is no longer safe. If it has an unusual sour smell or a sharp, unpleasant smell, or a strange taste when you put a little in your mouth, or if it is sticky and stringy, that is proof that germs have multiplied greatly and poison has formed. If you force yourself to eat it because it would be a waste, you put your life in danger from severe food poisoning. If the smell or taste is even a little suspicious, decide to throw it away and never swallow it." },
  { id:8, topic:"Food", emoji:"🪰",
    question:"What should you do with food a fly has landed on?",
    choices:["Eat it as it is","Don't eat the part the fly touched (throw it away)","Raise the fly as a pet","Stare at it"],
    answerIndex:1,
    explanation:"The insect we call a fly likes to walk around very dirty places full of germs, such as animal droppings, dead bodies, and rubbish dumps. Because of this, frightening disease-causing germs stick thickly to a fly's thin legs and body. When such a fly lands on our food, in that instant the germs on its legs move onto the food. If you eat the spot it touched, you are indirectly putting droppings and rubbish germs into your mouth, which can cause serious illness. Even if it feels wasteful, it is safer to cut away and throw out the part of the food the fly landed on." },
  { id:9, topic:"Preventing disease", emoji:"🦟",
    question:"What happens if you leave water standing for a long time?",
    choices:["The water becomes clean","Harmful mosquitoes multiply","Your money grows","Nothing happens"],
    answerIndex:1,
    explanation:"Old water that stays in one place without flowing becomes the perfect spot for the insect called the mosquito to lay its eggs. If you leave buckets, old tyres, or empty cans around your yard or house holding water, hundreds and thousands of new mosquitoes are born there and fly all around. When a mosquito sucks a person's blood, it injects into the body the germs of very frightening, life-threatening diseases such as malaria and dengue fever. Getting rid of pools of water around the house is an important plan to protect your family from these terrible diseases." },
  { id:10, topic:"Cleanliness", emoji:"✋",
    question:"When your nails are long, what builds up inside them?",
    choices:["Your hands get stronger","Black dirt and germs collect under the nails","Food tastes better","Nothing changes"],
    answerIndex:1,
    explanation:"When your fingernails grow long, black mud and dirt pack tightly into the narrow gap between the nail and the skin while you play in the soil, help out, or work. The dirt that gets into this gap does not come off easily with ordinary hand-washing, and it becomes the perfect hideout for germs. With long nails, when you eat with your hands or touch your own face or a wound, those hidden germs easily get into your body. Keeping your nails cut short at all times is a basic way to prevent illness." },
  { id:11, topic:"Cough manners", emoji:"🤧",
    question:"What should you do when you cough or sneeze?",
    choices:["Do it towards someone's face","Cover your mouth and nose with your hand or sleeve","Shout loudly","Do nothing"],
    answerIndex:1,
    explanation:"When you have a cold or a lung illness, a single cough or sneeze sends tiny droplets of water you cannot see flying out of your mouth and nose, several metres away with great force. Each droplet can contain tens of thousands of disease germs. If you cough towards someone's face you pass the illness directly, and if you cover nothing the germs spread through the air and everyone in the same room can get sick. When you cough, firmly covering your mouth and nose with your sleeve or hand keeps you from spreading illness to the precious family and friends around you." },
  { id:12, topic:"Cleanliness", emoji:"🗑️",
    question:"What happens if you leave rubbish lying near the house?",
    choices:["The house becomes clean","Harmful rats and insects gather and disease spreads","The rubbish turns into flowers","Nothing goes wrong"],
    answerIndex:1,
    explanation:"If you throw food scraps and kitchen rubbish away right next to your house, the smell draws many creatures such as rats, flies, and cockroaches. These creatures usually walk around sewers and filthy places, so they carry many frightening disease germs on their bodies. As they increase around the rubbish, they eventually get into the house and dirty the precious food and drinking water inside. Rubbish must be thrown away in a set place far enough from the house, or buried deep in a hole in the ground." },
  { id:13, topic:"Healthy teeth", emoji:"🪥",
    question:"What is the main reason for brushing your teeth?",
    choices:["To paint the teeth white","To reduce cavity germs in the mouth and protect the teeth","To make your jaw strong","To fill your stomach"],
    answerIndex:1,
    explanation:"After you eat, small scraps of food always remain in the gaps and on the surface of your teeth. The invisible creatures called cavity germs that live in our mouths love these food scraps. If you leave the scraps there, the cavity germs feed on them and make a strong acid that dissolves the teeth. Because of this acid, holes slowly open in the teeth — which should be the hardest part of the body — and when it reaches the nerve it brings pain so fierce you cannot sleep at night. Brushing your teeth after eating is absolutely necessary work to remove the germs' food and protect your teeth." },
  { id:14, topic:"Preventing injury", emoji:"👟",
    question:"Why do you wear shoes when you walk outside?",
    choices:["To make your feet bigger","To stop worms and germs in the soil from entering through the skin of your feet","To practise running","To keep your clothes clean"],
    answerIndex:1,
    explanation:"When you walk barefoot on soil and mud, tiny creatures hiding in the ground that are too small to see (the larvae of parasites) and germs can break through the soft skin of the soles of your feet and enter your body on their own. The worms that get in settle in your tummy (intestines) and steal the nourishment you eat, making you badly anaemic, stopping your growth, and draining your energy. Wearing shoes also protects you from serious injury caused by stepping on broken glass, sharp stones, or wooden thorns. Always wear shoes or sandals when you go outside." },
  { id:15, topic:"Cleanliness", emoji:"👕",
    question:"What happens if you keep wearing dirty clothes?",
    choices:["The clothes get stronger","Your skin gets itchy or you become ill","Your body gets stronger","Nothing changes"],
    answerIndex:1,
    explanation:"If you keep wearing clothes soaked with sweat or stained with mud for many days, mould and germs feed on the human sweat and skin oil on the clothes and multiply explosively inside the fibres. As those dirty clothes keep rubbing against your skin, the skin can swell up red, become very itchy, or develop a sore, oozing illness. Dirty clothes can be completely rid of germs by washing them clean with water and soap and drying them well in the sunlight (ultraviolet rays). Always wearing clean clothes is important for protecting the barrier of your skin." },
  { id:16, topic:"Cleanliness", emoji:"🚿",
    question:"What is good about washing your body?",
    choices:["Your skin gets clean and you prevent skin disease","You grow taller","Your hair falls out","You get hungry"],
    answerIndex:0,
    explanation:"Every day invisible oil (sebum) and sweat come out of human skin, and outside dust and soil mix in, making the whole body dirty. If you leave this dirt for many days, bad germs multiply on the surface of the skin, and you can get terrible boils or a frightening illness where the skin festers and rots. By regularly washing your whole body gently with water and soap and resetting the old oil and dirt, your skin is kept healthy and strong, building a powerful barrier that keeps illness from getting in from outside." },
  { id:17, topic:"Safe water", emoji:"💧",
    question:"When you only have muddy water, how can you drink it safely?",
    choices:["Drink it as it is","Filter out the mud with cloth or sand, then boil it over a fire","Just leave it in the sun and drink it","Drink only a little"],
    answerIndex:1,
    explanation:"When all you can get is muddy water, drinking it as it is sends a huge amount of germs into your body along with the mud and causes serious illness. Making it safe takes two pieces of wisdom. First, pass the water through fine, clean cloth, or a container packed with sand and small stones, to filter out the mud and large bits and make the water clear. But being clear is not enough — invisible germs are still alive. After that, you must put it over a fire and boil it hard until it bubbles, so the heat wipes out the germs and it finally becomes safe drinking water. With wisdom, you can make life-saving water even from muddy water." },
  { id:18, topic:"Babies", emoji:"🍼",
    question:"What is the best nourishment for a baby?",
    choices:["Cow's milk (raw)","The mother's milk (breast milk)","River water","Sugar water"],
    answerIndex:1,
    explanation:"A newborn baby's body is very weak and has almost no power to beat disease germs. A mother's milk (breast milk) not only holds perfect nourishment for the baby to grow, but also large amounts of a special protective ingredient called immunity that guards against illness. Breast milk also comes straight from the body, so it never touches dirty outside water or germs on containers — it is the cleanest and safest in the world. Other animals' raw milk, river water, or sugar water can wreck a baby's delicate stomach and intestines and take its life, so you must never give them." },
  { id:19, topic:"Preventing disease", emoji:"😷",
    question:"What should you do near someone with a bad cough?",
    choices:["Keep a little distance, and turn your face away when passing","Take a big breath in front of them","Shake hands with them","Stand right in front of them"],
    answerIndex:0,
    explanation:"Serious breathing illnesses such as tuberculosis (TB) float in the air for a long time, carried on the tiny invisible droplets that scatter when a sick person coughs. If you take a big breath nearby, or stay close for a long time, you breathe those germs deep into your own lungs and can catch the same serious illness. When someone has a bad cough, it is not about being unkind or treating them differently; to protect yourself, keep several metres of distance, and when passing, turn your face away and breathe out gently — this is the right way for both of you to stay safe." },
  { id:20, topic:"Fresh air", emoji:"🪟",
    question:"How do you keep the air in a room clean?",
    choices:["Shut all the doors and windows tight","Open windows and doors to let the air change","Everyone shout loudly together","Nothing changes"],
    answerIndex:1,
    explanation:"When many people gather in a small, closed room, the disease germs and viruses someone carries build up more and more in the air, until the air in the room is full of germs. If you stay in that room a long time, everyone breathes the dirty air and gets sick together (a group infection). By opening windows and doors in two or more places to exchange the fresh outside air with the dirty air in the room (ventilating), you can drive the germs out of the air and protect the health of everyone in the room." },
  { id:21, topic:"Levers", emoji:"🪨",
    question:"When you want to move a heavy stone buried in the ground using a long pole, where should you push hardest to move it with the least force?",
    choices:["The spot right next to the stone","The middle of the pole","The very far end of the pole, away from the stone","It is the same wherever you push"],
    answerIndex:2,
    explanation:"When you move something heavy with a pole, there is a rule called 'the lever principle': the farther you are from the small stone that acts as the support (the fulcrum), the less force you need to push with. If you push near the stone the pole will not budge, but if you grip the very far end of the pole and push by leaning your weight on it, you can lift a heavy stone with surprisingly little force. Knowing how a tool works like this lets you make your own strength many times greater and do heavy jobs easily." },
  { id:22, topic:"Levers", emoji:"⚖️",
    question:"When you lift a heavy load using a long pole, where should you place the small stone (the fulcrum) that supports the pole so it lifts most easily?",
    choices:["Right next to the heavy load","Right next to where you push with your force","Exactly in the middle of the pole","It is better not to place a small stone at all"],
    answerIndex:0,
    explanation:"When you lift something heavy with a pole, the position of the small supporting stone (the fulcrum) is very important. By placing this support right next to the heavy load, the load moves only a short distance, but the force you need to lift it becomes dramatically smaller. The other way around, if the support stone is close to you, no matter how hard you press you cannot lift the load. When you want to move something heavy, remember the wisdom of placing the support close to the thing you want to move." },
  { id:23, topic:"Rolling", emoji:"🪵",
    question:"When you move a heavy wooden box by dragging it along the ground, how can you move it most easily with the least force?",
    choices:["Lay several round, hard logs under the box and roll it","Just pull it with all your might","Pour water on top of the box","Smash the box hard against the floor"],
    answerIndex:0,
    explanation:"When you drag something heavy straight along the ground, a braking force called 'friction', made where the object rubs against the ground, works strongly, so it takes enormous force to move. But if you lay round, hard logs under the box, the motion changes from dragging to the logs rolling. Rolling has dozens of times less braking force than dragging, so even one person can move a heavy load smoothly. When the load moves forward, you take the logs that come out at the back and lay them in front again, a piece of wisdom humans have used since ancient times." },
  { id:24, topic:"Ramps", emoji:"🛝",
    question:"When you want to put a heavy load onto a high platform about chest height for an adult, which way of moving it puts the least strain on your body?",
    choices:["Stand in front of the platform and lift it straight up with all your might","Lean a long board against the platform at a slant to make a slope, and push it up","Throw the load at the platform from far away","Shave the platform down to make it lower"],
    answerIndex:1,
    explanation:"If you try to lift a heavy load straight up, you face head-on the force that pulls things down toward the earth (gravity), so you must support everything with your muscles alone, which hurts your back and arms. Here, if you lean a long board against the platform at a slant to make a slope (an inclined plane), the board comes to support most of the load's weight. Going up a slope, the distance you walk gets longer, but the force needed to push the load can be cut to less than half. When carrying things to a high place, always find a way to make a slope." },
  { id:25, topic:"Pulleys", emoji:"🪣",
    question:"When you pull a heavy bucket of water up from a deep well with a rope, what becomes easier if you fit a 'round wheel that spins (a pulley)' on the bar above the well and hang the rope over it?",
    choices:["The weight of the water becomes half as light","The amount of water increases on its own","You can raise the water just by pulling the rope downward","The rope will never break"],
    answerIndex:2,
    explanation:"When you hang a rope over the round wheel above the well (a fixed pulley), the weight of the water itself does not actually get lighter. But the wonderful thing about this tool is that it changes the direction in which you apply force. If you try to lift the rope straight up, you must raise it with the strength of your arms and back alone; but if you hang the rope over the round wheel and pull downward, you can put your whole body weight onto the rope. Being able to use your own body weight to pull heavy water up easily and safely is the wisdom of this round wheel." },
  { id:26, topic:"Wheel and axle", emoji:"🔄",
    question:"When you want to turn a screw that just will not turn, or a heavy well winch, how can you turn it most easily?",
    choices:["Turn it using a short, thin rod","Make the handle part large and long, and turn that","Turn it with just your fingertips, using no tool","Hit the screw hard with a hammer"],
    answerIndex:1,
    explanation:"When you want to turn an axle at the center, if you fit a large round handle or a long grip onto that axle, you can create a large turning force with a small effort. This is called the 'wheel-and-axle' principle. You cannot budge the thin part by turning it directly with your fingers, but when you turn the large outer handle, the distance your hand moves gets longer while the force on the axle becomes many times stronger. A machine that winds up a well rope, a doorknob at home, the screws on tools, every turning tool around you uses this wisdom." },
  { id:27, topic:"Center of gravity", emoji:"🏺",
    question:"There are people who walk skillfully with a heavy water jar or firewood balanced on top of their head. Why can they walk long distances without hurting their neck or back?",
    choices:["Because they walk bending their body far forward or backward","Because they keep their back perfectly straight and place the center of the load (its center of gravity) right above their bones","Because they constantly shake the load violently on their head","Because everyone is born with neck bones thicker than other people's"],
    answerIndex:1,
    explanation:"When you carry a heavy load in your hands, the strain falls on only one side of your body and your muscles tire quickly. But if you straighten your back perfectly and place the load right on top of your head, the weight at the center of the load (its center of gravity) passes straight down through the pillar of bones, from head to neck to spine, and out into the ground. Because the sturdy bones, not the muscles, support the weight, you can carry it safely over long distances without wasting muscle power, as long as you keep your balance. Keeping things close to the central axis of your body is important wisdom for not hurting yourself." },
  { id:28, topic:"Pressure", emoji:"🦶",
    question:"When you walk on a muddy road where, after rain, it turns to deep mud and your feet sink in, how can you walk more easily without sinking?",
    choices:["Walk on your tiptoes, making the soles of your feet as small as possible","Tie a flat, large wooden board to the soles of your feet and walk","Just shout loudly and run across","Carry a lot of luggage to make yourself heavier"],
    answerIndex:1,
    explanation:"The weight pressing on the ground concentrates more strongly in one spot and sinks in deeper, like a needle, the smaller the area touching it. This is called 'pressure.' Standing on tiptoe makes the area smaller, so you sink in even deeper. The other way around, if you attach a flat, large wooden board to the soles of your feet, your body weight is spread over a wide area, so the force pushing the ground down weakens and you can walk on the mud without sinking. Making the base of a heavy building wide and flat is the same wisdom for spreading out pressure." },
  { id:29, topic:"Carts", emoji:"🛒",
    question:"When you want to load a two-wheeled cart with lots of heavy luggage and pull it, where should you place the heavy things so it is lightest and easiest to pull?",
    choices:["Right next to your hands, by the handle","At the very back end of the cart","Right above the axle of the wheels","It is the same wherever you load it"],
    answerIndex:2,
    explanation:"When you pull a cart, the weight on your hands changes dramatically depending on where you place the load. If you load the heavy luggage near your hands, you end up running while lifting the load's weight directly with your arms, and tire quickly. If it is too far back, the cart tips over backward, which is dangerous. The correct answer is right above the axle of the wheels. If you load the heavy things here, the sturdy wheels and the ground support all of the weight, so almost no weight falls on your hands. Since you only need the force to pull it forward, you can carry a large load very easily." },
  { id:30, topic:"Blades", emoji:"🔪",
    question:"When you sharpen the tip of a hatchet for splitting firewood, or a kitchen knife for cutting food, by rubbing it on a stone (a whetstone), why does it cut better?",
    choices:["Because the tip of the blade gets thinner and finer, so the force concentrates in one spot","Because the blade gets hot and melts the food","Because the blade gets heavier","Because the blade becomes rounded"],
    answerIndex:0,
    explanation:"When something is cut by a blade, it happens because the force a person applies concentrates on the extremely narrow spot of the blade's tip and breaks through the object. When a blade gets old and rounded, the force spreads over a wide area, so no matter how hard you press it will not cut. Sharpening a blade is the work of shaving the rounded tip to make it as fine and thin as possible. Once the tip is fine, even a small force creates enormous pressure at that spot, so you can slice through hard firewood or food with a light touch. Caring for your tools is basic to saving your energy." },
  { id:31, topic:"Friction", emoji:"👟",
    question:"When you walk on a slope or on wet rocks, which is harder to slip on and safer: smooth, slippery shoes, or shoes with deep, spiky grooves on the sole?",
    choices:["Smooth, flat shoes","Shoes with deep, spiky grooves on the sole","It is the same whichever you wear","You slip less with no shoes at all"],
    answerIndex:1,
    explanation:"When the sole of a shoe rubs against the ground, a braking force called 'friction' works there to stop you slipping. If the sole is smooth, no braking works between it and the ground, and you slip and fall easily, especially where there is water or mud. If the sole has deep, spiky grooves, those grooves bite firmly into the bumps of the ground and create a strong braking force. Slipping and falling can lead to serious injury, but by knowing how friction works, choosing shoes with grooves on slippery ground or putting your whole sole firmly on the ground, you can act safely." },
  { id:32, topic:"Floating", emoji:"⛵",
    question:"A small pebble sinks in water, yet a wooden ship thousands of times heavier and bigger can float on the water. Why?",
    choices:["Because the ship is shaped like a bowl, holding lots of air and water inside","Because the ship gets a lot of wind","Because magic stones are painted on the ship's bottom","Because the ship is made of oil that is lighter than water"],
    answerIndex:0,
    explanation:"On an object in water, a mysterious force called 'buoyancy' works, pushing it upward by as much as the water it pushes aside. A pebble is packed solid inside and heavy, so the pebble is heavier than the water it pushes aside, and it sinks. But a large ship is shaped like a bowl, and inside it holds lots of air. Looked at as a whole, it becomes very light for its size, so the force of the water pushing up from below becomes stronger, and even a large ship can float on the water without tipping over." },
  { id:33, topic:"Triangles", emoji:"🔺",
    question:"When you build a house or a bridge out of wood or iron, why does shaping the frame into triangles make a very sturdy building that is hard to break?",
    choices:["Because it needs more material than a square","Because a triangle has the property that its shape never distorts even when strong force is applied from above","Because making triangles lets the wind pass through more easily","Because it is an old shape used as a charm from the gods"],
    answerIndex:1,
    explanation:"A building made of pillars joined only into squares easily collapses, with the joints bending limp, when strong force or the shaking of an earthquake is applied from above or the side. But if you add one slanted rod inside that square to make a triangle (a truss structure), then no matter which direction force comes from, the rods pull and push against each other so the shape does not distort at all. If you look at large bridges around the world, or the underside of building roofs, these triangles are always finely combined together. It is a wonderful building wisdom: even with little material, just by working out the shape you can make something many times sturdier." },
  { id:34, topic:"Inertia", emoji:"🐎",
    question:"When a running horse or cart slams on the brakes and stops dead, what happens to the luggage and people riding on top?",
    choices:["They tip over backward as they are","They are flung forward with great force","They jump straight up on the spot","Nothing happens; they stop dead too"],
    answerIndex:1,
    explanation:"In the universe there is a mysterious force called 'inertia': a moving thing tries to keep moving at the same speed. Even when a horse or cart suddenly stops, the people and luggage on top are still trying to keep going forward. So unless you brace your feet firmly or tie the luggage down with rope, you are flung forward with great force and badly hurt. When you stop something that is moving, or when you ride a fast vehicle, you must keep in mind that this force that tries to fling things forward is always at work, and prepare for safety." },
  { id:35, topic:"Scissors", emoji:"✂️",
    question:"When you want to cut a hard branch or thick cloth with scissors, at which part of the blade should you hold it to cut most easily with the least force?",
    choices:["At the very tip of the blade","At the base of the blade (closest to the screw or hinge)","At the middle of the blade","The force needed is the same wherever you cut"],
    answerIndex:1,
    explanation:"Scissors, too, are a very handy tool that uses the lever principle we have been learning. The screw where the two blades cross and are fixed becomes the support (the fulcrum). The closer to this supporting screw you cut, the many times stronger the force becomes that your gripping hand passes to the blade. So with something hard that will not cut, trying to cut at the scissor tip only makes your hand hurt, but if you grip it deep at the base of the blade, you can snip it off with surprisingly little force. Know the nature of your tools and use the most efficient spot." },
  { id:36, topic:"Gravity", emoji:"🍎",
    question:"Why is it that dropping a small pebble onto your foot from knee height, versus from the high roof of your house, the one dropped from the roof causes a worse injury?",
    choices:["Because the stone gets colder up on the roof","Because gravity, the force pulling things down toward the earth, makes the stone faster and faster the longer the drop, so the impact when it hits is stronger","Because a stone in a high place becomes bigger in size","Because the air pushes the stone down"],
    answerIndex:1,
    explanation:"Everything on the earth is constantly pulled by a force called 'gravity', drawn toward the ground. For something in a high place, the longer the drop, the more it keeps being pulled by gravity and speeds up faster and faster (it accelerates). An object that has sped up creates enormous destructive power (energy) the instant it hits the ground or your body. From knee height it only hurts, but something falling from a high roof or cliff, even a small stone or tool, becomes a weapon that can take a person's life. When you work near a high place, you must check that no one is below and take the greatest care not to drop anything." },
  { id:37, topic:"Balance", emoji:"⚖️",
    question:"When you carry two heavy water jars hung on the front and back of a single long pole (a carrying pole) on your shoulder, how can you walk easily without hurting your shoulder?",
    choices:["Make the front load very heavy and the back load light","Make the front and back loads exactly the same weight, and put the very middle of the pole on your shoulder","Do not put the pole on your shoulder; carry it with your hands only","Drop the loads to the ground alternately as you run"],
    answerIndex:1,
    explanation:"When you carry loads hung on each side of a long pole, if the front and back weights are uneven, the pole tilts to one side and you have to fight to hold it down with your hands. This tires not only your shoulder but your arms and back quickly. The correct answer is to make the front and back loads exactly the same balance. Then the weight presses evenly right above your shoulder through the carrying pole, and you can carry heavy loads just by walking, without using extra muscle to fight a tilt. If one load is unavoidably lighter, adjust the balance by sliding the rope of the lighter side toward the end of the pole." },
  { id:38, topic:"Air resistance", emoji:"🪂",
    question:"You have two sheets of paper of the same size and same weight. One is left as a flat sheet, the other is squeezed by hand into a tight ball. When you drop them at the same time from a high place, which lands on the ground first?",
    choices:["The flat sheet left as it is","The paper squeezed into a tight ball","Both land at exactly the same time","It changes every time depending on the wind"],
    answerIndex:1,
    explanation:"Even for things of the same weight, when they fall through the air a braking force called 'air resistance' works, with the air getting in the way. The flat sheet of paper has a wide area, so it catches a lot of the air beneath it and falls only slowly, like a parachute. But the paper squeezed into a small ball touches the air over a very narrow area, so it receives almost no braking and falls fast, pulled straight down by gravity. A windmill turning in the wind, or an umbrella nearly being blown away on a windy day, also have to do with this braking force of the air." },
  { id:39, topic:"Elasticity", emoji:"🏹",
    question:"When you bend a hard, sturdy bamboo or a supple tree branch with all your might and then let go, it springs back to its original shape with force. What can you use this property (elasticity) for to make a handy tool useful in daily life?",
    choices:["A refrigerator to keep food from rotting","A bow and arrow to shoot an arrow at distant prey, or a trap that flings heavy things","A filter to clean water","A tool to dye clothes white"],
    answerIndex:1,
    explanation:"Rubber and springs, and bamboo and tree branches too, have a mysterious property called 'elasticity': when you apply force their shape bends, and when you let go they try to return to their original shape at great speed. While you hold it bent by hand, the force a person applies is stored up inside that tool for a moment as energy. The instant you let go, that stored force is released all at once, so you can shoot an arrow many times farther, or work a trap, than by throwing with your arm alone. Using this power that natural plants have, humans have made tools for hunting and daily life since ancient times." },
  { id:40, topic:"Oiling", emoji:"🛢️",
    question:"The wheels of a cart, or a door's hinge, started making a nasty squeak-squeak sound and getting heavy every time you moved them. If you drip a few drops of oil here, why does it move smoothly again?",
    choices:["Because the oil melts the iron and makes it lighter","Because the oil hardens and becomes glue","Because the oil gets into the gap between metal and metal and dramatically reduces the rubbing braking force (friction)","Because the smell of the oil drives insects away"],
    answerIndex:2,
    explanation:"When a machine or tool moves, there are places where metal rubs hard and directly against metal. A very strong braking force called 'friction' works there, and if left alone it wears down and breaks, or it takes enormous force to move. When you apply oil, a thin film of oil forms in the tiny gap of the metal and keeps it from rubbing directly. Because the braking force suddenly disappears, the tool moves astonishingly smoothly with little force. Just by applying a little cooking oil or plant oil to a tool, the tool lasts longer and greatly reduces the wearing-out of a person's strength." },
  { id:41, topic:"Lightning", emoji:"⚡",
    question:"When thunder is rumbling and you are outside, where is the safest place to escape to?",
    choices:["Right under a tall tree","In the middle of a wide open field","Inside a sturdy building, or a car surrounded by metal","Standing while holding up a big umbrella"],
    answerIndex:2,
    explanation:"Lightning has a strong tendency to strike tall things. So if you stand alone in a wide open field, you become the tallest pointed thing around, and the danger of a direct strike becomes very high. Also, standing right under a tall tree is dangerous: lightning that hits the tree can jump across to your body, a phenomenon called a side flash, causing fatal injury. The safest places are inside a sturdy building made of concrete, or inside a car surrounded by metal panels. Even if lightning hits the car, the electricity flows through the outer metal and down into the ground, so the people inside are completely safe." },
  { id:42, topic:"Floods", emoji:"🌊",
    question:"In heavy rain the road has turned into a river, and you have no choice but to walk through the water to evacuate. What is the safest thing to wear on your feet?",
    choices:["Bare feet","Sandals","Shoes tied firmly with laces","Rubber boots"],
    answerIndex:2,
    explanation:"The bottom of a flooded road hides many invisible dangers: broken glass, sharp cans, open manhole holes. With bare feet or sandals you easily injure your feet and can no longer move. Rubber boots may look good, but once water gets in from the top they become heavy like water-filled pillows, your feet cannot lift at all, and you cannot walk or even drown. The safest are shoes that do not slip off and have a hard sole: sneakers tied firmly with laces. They do not get heavy even when water enters, and they protect your feet while letting you walk steadily." },
  { id:43, topic:"Evacuation", emoji:"⛰️",
    question:"A flood from heavy rain or a tsunami has come, and water is rushing up to your feet. Which direction is it right to flee?",
    choices:["Downstream where the water flows fast (a low place)","A nearby high hill or mountain, or an upper floor of a sturdy building (a high place)","A relative's house far away","Your home's basement (lower than the ground)"],
    answerIndex:1,
    explanation:"In a flood or tsunami, water fills up with tremendous force, starting from the lowest places. If you hide in a basement lower than the ground, water pours in from the entrance all at once, you cannot get out, and you drown. Also, trying to flee far away by wandering around, you may be hit by drifting trees or cars, or have your feet swept out by the fierce flow and be carried away. When water closes in, the rule is not to go far, but to head for the nearest high place from where you are now. Climbing a nearby hill or mountain, or the 2nd or 3rd floor of a sturdy concrete building, and waiting for the water to recede, is the choice that protects your life." },
  { id:44, topic:"Heatstroke", emoji:"🥵",
    question:"On a very hot day when the sunlight is extremely strong, what is the most important thing to prevent the illness where your body overheats and you collapse (heatstroke)?",
    choices:["Endure it without drinking any water","Smear cold mud all over your body","Rest in the shade, and drink safe water little by little, many times","Run a lot to sweat it out"],
    answerIndex:2,
    explanation:"If you stay in a very hot place for a long time, the water and salt in your body leave as sweat, and your body can no longer lower its own heat. This is the frightening condition called heatstroke. To prevent it, it is important to find cool shade where the sunlight does not hit you directly, and rest your body. And you need to drink safe, boiled-and-cooled water little by little, many times over, even before you feel thirsty. Rather than gulping a lot at once, drinking in small frequent sips lets your body absorb water well, so you can stay healthy and safe even under the hot sun." },
  { id:45, topic:"Earthquakes", emoji:"🪑",
    question:"When an earthquake hits and the ground and your house start shaking violently, what is the first thing to do inside the room?",
    choices:["Panic and rush outside","Hide under a sturdy desk and protect your head and body","Shut the windows tight and look outside","Stuff a lot of things into a bag"],
    answerIndex:1,
    explanation:"When an earthquake hits, the most dangerous things are objects falling from above and furniture toppling over. If you panic and rush outside, broken glass and roof tiles can fall from the upper parts of buildings and hit your head, a very high risk of serious injury. When you feel shaking, first crawl under a sturdy desk or bed right where you are, grip the desk legs firmly, and protect your head and body. If there is nowhere to hide, cover your head tightly with a cushion, a bag, or your own arms, make yourself small in the middle of the room where furniture will not fall on you, and wait quietly until the shaking completely stops, that is safest." },
  { id:46, topic:"Lightning", emoji:"⚡",
    question:"When thunder is rumbling nearby, which action is the most dangerous to do while outside?",
    choices:["Holding a plastic toy","Holding a long metal pole or fishing rod up high toward the sky","Wearing cloth clothes","Wearing wooden shoes"],
    answerIndex:1,
    explanation:"Lightning has a frightening tendency to strike intensively at things that are tall and have a pointed tip. So if you are outside holding a long metal pole, a fishing rod, or a long umbrella thrust up high toward the sky, it becomes like an antenna calling the lightning, and you get struck directly. When you hear thunder rumbling, immediately lay any long pole you are holding down flat on the ground, lower your own posture as much as possible, and crouch with your head down. Then evacuate into a safe building right away." },
  { id:47, topic:"Landslides", emoji:"⚠️",
    question:"When heavy rain keeps falling near a mountain, which is a dangerous sign that the mountain might collapse (a landslide)?",
    choices:["The river water suddenly turns pitch-black and muddy, and lots of wood chips flow down","Small stones come tumbling down from the mountain bit by bit","A strange rumbling sound, like the ground groaning, comes from deep underground","All of these are dangerous signs"],
    answerIndex:3,
    explanation:"When heavy rain pours onto a mountain, the soil soaks up a huge amount of water, and at some moment the cliff or the whole mountain collapses all at once, a great disaster called a landslide or a debris flow. Just before these happen, nature always gives several warning signs. River water suddenly turning muddy with more driftwood is proof that soil is starting to collapse higher up. Also, if small stones fall from the mountain, or an eerie sound comes from the ground, it is a signal that the whole mountain is about to move. If you find or feel even one of these signs, you must leave that place even one second sooner and flee to a high, sturdy place." },
  { id:48, topic:"Floods", emoji:"🦯",
    question:"When you must walk through flood water, on a road where mud makes the ground completely invisible, how should you walk to be safe?",
    choices:["Run at full speed to escape quickly","Use a long pole to tap and check the ground is safe, one step at a time","Close your eyes and go straight ahead","Take off all your clothes and swim"],
    answerIndex:1,
    explanation:"After a flood, the road water is muddy brown with mixed-in mud and rubbish, so you cannot see at all what the ground is like. In fact, under the water a manhole cover may have come off leaving a deep hole, or the ground may have eroded into a deep ditch. If you run or walk without noticing, you can fall into a deep hole in an instant and sink underwater. When walking through water, always hold a long, sturdy pole like a cane, and before taking the next step, tap the ground with the pole to check whether there is a hole, advancing slowly and carefully, that is the way of walking that protects your life." },
  { id:49, topic:"Tornadoes", emoji:"🌪️",
    question:"When a tornado (an intense wind spinning around at tremendous speed) approaches, where in the house is the safest place to hide?",
    choices:["Right next to a window with a good view outside","On the rooftop where the wind feels nice","A sturdy room with no windows, or a toilet or closet in the center of the house","Lying down on a big bed"],
    answerIndex:2,
    explanation:"A tornado is the most violent gust on Earth, strong enough to blow off a house roof or whirl big trees and cars into the air. When a tornado approaches, the most frightening thing is flying objects smashing through the window glass, scattering glass shards around the room at tremendous speed. So being near a window means serious injury. The safest place is where the walls are thickest and there are absolutely no windows: a toilet, a sturdy room, or a closet in the center of the house. Shut yourself in there, cover your head with a cushion or blanket, curl up small, and wait quietly for the storm to pass, that is the right way to hide." },
  { id:50, topic:"Fire", emoji:"🔥",
    question:"When a fire breaks out and a lot of smoke builds up in the room, how should you escape outside?",
    choices:["Stand up tall and run at full speed","Get into a low posture, crawling on the floor, cover your mouth with cloth, and escape","Shut all the windows to trap the smoke","Pull a big blanket over yourself and sleep in bed"],
    answerIndex:1,
    explanation:"The smoke produced by a fire contains a lot of harmful poison (such as carbon monoxide) that makes a person faint the instant they breathe it in. Because smoke is hot, it builds up in the room starting from the ceiling (the high area) first, and relatively clean air remains last near the floor. So if you stand up tall, you breathe in the thickest poisonous smoke head-on and can no longer move. When escaping, keep a low posture with your chest near the floor, press a wet cloth or clothing firmly over your mouth and nose, breathe the air near the floor, and quickly get outside, that is the right way to escape." },
  { id:51, topic:"Tsunami", emoji:"🌊",
    question:"When you are near the sea and feel a violent earthquake, what is the most important thing you must do immediately?",
    choices:["Go to see if there are fish in the sea","Return home to gather all your belongings","Get away from the coast and quickly climb a high mountain or sturdy high ground","Sit still on the sandy beach"],
    answerIndex:2,
    explanation:"When a large earthquake occurs under the sea, the seabed moves greatly, and all the surrounding water surges in as a huge wall-like wave, a great disaster called a tsunami. Unlike ordinary waves, a tsunami has tremendous weight and destructive power, enough to sweep away buildings and houses in an instant. Also, before a tsunami arrives, the tide may suddenly pull back and reveal the sandy bottom, but if you go to look at it for fun, the next moment you are swallowed by the great wave. If you feel shaking near the sea, take nothing, get away from the sea even one second sooner, and flee to a high hill or mountain, or an upper floor of a sturdy building. Once you can see the wave, it is too late to escape." },
  { id:52, topic:"Cold", emoji:"🧥",
    question:"When you might get lost in a freezing cold place in winter, what is the best action to keep your body warm and survive?",
    choices:["Drink a lot of cold water","Stay in your wet clothes as they are","Hide where the wind does not hit you, and put on many layers of clothes or cloth","Lie down and sleep directly on the snow"],
    answerIndex:2,
    explanation:"The human body, if its temperature drops too much, can no longer move and loses its life (hypothermia). Especially wind and wet clothes are dangerous enemies that steal heat from the body in an instant. To protect yourself in a cold place, the top priority is to hide where the wind absolutely does not hit you, such as behind a big rock or inside a building. Then, if your clothes are wet, be sure to change into dry ones, and put on many layers of the clothes, cloth, or paper you have. Layering cloth creates a layer of warm air between the layers, a magic wall that keeps your body heat from escaping. Sleeping directly on snow steals your heat, so spreading grass or cardboard on the ground to sit on is also important wisdom." },
  { id:53, topic:"Volcanoes", emoji:"🌋",
    question:"When a nearby volcano (a mountain that spews hot fire and mud) suddenly erupts, how do you protect yourself from the ash and stones flying from the sky?",
    choices:["Look up at the sky and watch carefully what is falling","Go inside a sturdy building (such as a concrete house) and cover your mouth and nose with cloth","Jump into a nearby river and swim","Run at full speed toward the mountain"],
    answerIndex:1,
    explanation:"When a volcano erupts, heavy red-hot lava and big stones come down from the sky at frightening speed from the summit. If these hit your head it is life-threatening, so you must hide right away inside a sturdy building made of concrete or the like. Also, the volcanic ash that the volcano spews out is not ordinary sand but like fine, crushed glass thorns. Breathing it in injures your lungs so you cannot breathe, and getting it in your eyes causes strong pain so you cannot open them. Once inside the building, shut the windows tight, cover your mouth and nose firmly with a mask or a water-dampened cloth, and protect yourself from ever breathing in the filthy ash." },
  { id:54, topic:"Fog", emoji:"🌫️",
    question:"When fog (white haze spreading through the air) becomes extremely thick and you cannot see ahead at all, what is the most dangerous thing about walking?",
    choices:["Stopping where you are","No longer being able to hear the sounds around you","Not being able to see your own position or dangerous places like cliffs, so you get lost or fall","Your clothes getting a little damp and wet"],
    answerIndex:2,
    explanation:"When thick fog forms, even the scenery just a few meters ahead turns pure white and you can see nothing. If you force yourself to keep walking in this state, your sense of direction, of where you are heading, becomes completely paralyzed, and it can lead to serious accidents: wandering into a dangerous deep forest, or failing to notice a deep cliff or river right in front of you and plunging straight down to your death. When you cannot see ahead, you must never push on. The safest defense is to stop where you are in a place with sure footing, such as the middle of a safe wide road, and wait quietly until the fog clears and you can see around you well again." },
  { id:55, topic:"Cliff collapse", emoji:"🪨",
    question:"When you are near a high wall of earth (a cliff) after heavy rain has fallen, what must you absolutely be careful of?",
    choices:["The rainwater may soak into the cliff and it may suddenly collapse (a cliff collapse), so get away immediately","Climb up onto the cliff and play happily","Pitch a tent right under the cliff and sleep","Pour lots of water at the cliff wall"],
    answerIndex:0,
    explanation:"A cliff or old earthen slope after heavy rain has a huge amount of water packed to the limit inside the soil, and it is in a very fragile, sponge-like soggy state. Even after the rain stops, hours to days later, a cliff collapse frequently happens where the whole wall suddenly crumbles down as if exploding, with no sound at all. If you play or sleep at the foot of the cliff, you get buried under many tons of heavy earth in an instant and cannot be saved. During heavy rain, and for several days after the rain stops, you must always keep the rule: never go near a high earthen wall or cliff, get away immediately." },
  { id:56, topic:"Evacuation", emoji:"🏃",
    question:"When the river near your house is rising more and more in heavy rain and is about to overflow, when should you start evacuating?",
    choices:["After water has come into the house","Early, while it is still light outside and no water has built up on the road, while it is safe","Wait quietly until the river water completely overflows","Think about it after getting into bed and sleeping"],
    answerIndex:1,
    explanation:"Trying to evacuate after the river overflows and water starts building up on the road is the most dangerous, too-late decision. When water builds up to knee height on the road, even a grown man is swept away by the strong force of the water and cannot walk at all. Also, once it gets dark at night, you can no longer tell where the road is and where the river is, and you fall into the river and are carried away on the way to evacuate. The most correct timing to start evacuating is while it is still light outside and no water has built up at your feet, while it is safe. The moment you sense even a little danger from the rising river, keep your belongings to a minimum and set out early toward a high, safe shelter, that is the wisdom that surely protects your life." },
  { id:57, topic:"Electric shock", emoji:"🔌",
    question:"After an earthquake or heavy rain, you find a broken electric wire in the house giving off sparks. Why must you absolutely not touch it?",
    choices:["Because your hands will get dirty with black mud","Because the strong electricity flowing in the wire flows into your body and causes serious injury, such as your heart stopping (electric shock)","Because the wire is cold like ice","Because the room will go pitch dark"],
    answerIndex:1,
    explanation:"From a broken wire, or from an electrical appliance wet with water, very strong electricity invisible to the human eye may be leaking out. If you touch it with your hand without knowing, the electricity in the wire shoots through your body in an instant and flows down into the ground. This is called electric shock. Receiving strong electricity not only burns your body but can make your heart stop dead, a fatal accident in an instant. Especially when your body or hands are wet with water, electricity flows into your body many times more easily, which is even more dangerous. If you find a sparking wire or a snapped wire, never go near it, never touch it, and report it to an adult." },
  { id:58, topic:"Typhoons", emoji:"🌀",
    question:"When a fierce strong wind (a typhoon or cyclone) is blowing, why is going outside dangerous enough to be life-threatening?",
    choices:["Because the air outside does not taste very good","Because shop signboards, roof tiles, and big tree branches fly at you and hit your head","Because your favorite clothes get dirty with mud","Because getting strong wind all over your body makes you fat"],
    answerIndex:1,
    explanation:"In a fierce storm like a typhoon or cyclone, the force of the wind becomes far beyond what humans imagine. Being blown away by the wind itself is dangerous, but the most frightening thing is everything in town becoming a weapon and flying at you. Heavy shop signboards, hard roof tiles, broken tree branches and the like come flying sideways at a speed like a sharp knife or a bullet. If even one of these hits your body, it is a fatal injury. While you can hear the sound of strong wind, no matter what business you have, you must absolutely not go outside. Staying in a safe house away from windows and waiting quietly for the storm to completely pass is the right action." },
  { id:59, topic:"Sandstorms", emoji:"🏜️",
    question:"When a sandstorm (sand and dust whirled up by strong wind) happens, what should you do to protect your eyes and lungs?",
    choices:["Open your eyes and mouth wide and take in the wind","Cover your face, mouth, and nose firmly with a scarf or cloth, and hide inside a sturdy building","Go outside and run races with your friends","Look up at the sky to see how far the sand flies"],
    answerIndex:1,
    explanation:"A sandstorm that happens near a desert or in a dry region is a great storm that whirls up hundreds of millions of fine sand grains and filthy dust with strong wind. If you breathe this sand and dust in as it is, sand builds up deep in your lungs and you cough violently, becoming a serious illness where you cannot breathe. Also your eyes can be injured by sand so you cannot see. When a sandstorm approaches, evacuate inside a sturdy building right away and close the windows and doors with no gaps. Then, layer the scarf or clothing cloth you have many times over and cover your whole face, especially your mouth and nose, tightly to make a mask that blocks the sand from getting in. Until the storm passes, protect yourself by quietly breathing only the air that comes through the cloth." },
  { id:60, topic:"Floods", emoji:"🌊",
    question:"During a flood where muddy water surges into the house, why is being in the basement (a room lower than the ground) absolutely not allowed?",
    choices:["Because the basement is cooler and more comfortable than other rooms","Because muddy water from the road above pours in all at once like a waterfall, the exit gets blocked, and you drown in an instant","Because the basement goes pitch dark when the power goes out","Because small rats sometimes live in the basement"],
    answerIndex:1,
    explanation:"A basement or semi-basement room lower than the ground turns into the most life-threatening, most dangerous place in the world when a flood occurs. The muddy water that has overflowed onto the road above pours in all at once through the basement's stairs and windows with the tremendous force and weight of a waterfall. The force of the water flowing down the stairs is intense, and even an adult's strength cannot resist it to climb up. Furthermore, the weight of the water pushes the basement door from outside, and it becomes absolutely impossible to open from inside. The room fills with water in an instant, the escape route is completely lost, and you drown. When the rain gets heavy, the absolute iron rule is: never go near the basement, climb to an upper floor right now." }
];
