/*
 * Wise World - Data kuis (Bahasa Indonesia)
 * ⚠ Terjemahan AI dari naskah asli bahasa Jepang. Disarankan ditinjau oleh
 *    penutur asli atau ahli kesehatan sebelum digunakan.
 * Jaga id / answerIndex / emoji tetap sama untuk semua bahasa.
 */
(window.WISE_WORLD_Q = window.WISE_WORLD_Q || {}).id = [
  { id:1, topic:"Air aman", emoji:"💧",
    question:"Air mana yang aman dan tidak membuat perutmu sakit?",
    choices:["Air sungai","Air sumur","Air yang direbus mendidih di atas api","Air hujan"],
    answerIndex:2,
    explanation:"Air sungai, air sumur, dan air hujan bisa terlihat sangat jernih dan bersih, tetapi bisa penuh dengan makhluk hidup sangat kecil yang tidak bisa dilihat mata kita (kuman dan virus). Jika kamu minum air itu begitu saja, bisa menyebabkan sakit perut yang hebat atau penyakit serius yang mengancam nyawa. Namun, ketika kamu menaruh air di atas api dan merebusnya kuat sampai menggelegak, panas itu membunuh semua makhluk berbahaya tersebut. Itulah sebabnya air yang sudah direbus dengan baik lalu didinginkan adalah air paling aman di dunia, dan air yang bisa kamu minum dengan tenang." },
  { id:2, topic:"Mencuci tangan", emoji:"🧼",
    question:"Apa yang harus kamu lakukan sebelum makan?",
    choices:["Mencuci tangan dengan air dan sabun","Mengelap tangan ke baju","Tidak melakukan apa-apa","Menyentuh tanah"],
    answerIndex:0,
    explanation:"Tangan kita menyentuh banyak benda dan tanah setiap hari, jadi tanpa sadar tangan kita membawa banyak kuman yang tidak terlihat. Jika kamu menyentuh makanan dengan tangan itu, kuman berpindah ke makanan dan kamu menelannya ke dalam tubuh bersama makanan. Mengelap tangan ke baju kotor, atau hanya membasahinya dengan air, tidak menghilangkan kuman: kuman tetap menempel. Hanya dengan memakai sabun dan menggosok telapak tangan, punggung tangan, dan sela-sela jari dengan busa yang banyak, lalu membilasnya dengan air, kamu benar-benar bisa menghilangkan kuman." },
  { id:3, topic:"Mencuci tangan", emoji:"🚽",
    question:"Apa yang harus kamu lakukan setelah dari toilet?",
    choices:["Langsung pergi bermain","Mencuci tangan dengan air dan sabun","Menggosok tangan ke baju","Mengeringkan tangan di celana"],
    answerIndex:1,
    explanation:"Setelah dari toilet, kuman yang sangat kuat dari tinja dan air seni, yang menyebabkan penyakit, mudah menempel di tanganmu. Jika kamu langsung bermain tanpa mencuci tangan, kuman itu berpindah ke gagang pintu dan mainan yang kamu sentuh, lalu menularkan penyakit kepada teman atau keluarga berikutnya yang menyentuhnya. Dan jika kamu menyentuh mulut atau matamu sendiri dengan tangan itu, kamu juga bisa jatuh sakit. Seberapa pun terburu-burunya kamu, selalu mencuci tangan dengan baik memakai air dan sabun setelah dari toilet adalah aturan yang melindungi nyawamu dan nyawa orang di sekitarmu." },
  { id:4, topic:"Kesehatan", emoji:"💧",
    question:"Saat perutmu sakit dan tinja menjadi cair (diare), apa yang paling penting?",
    choices:["Makan banyak","Tidak minum apa-apa","Minum banyak air yang aman","Berlari dan bermain"],
    answerIndex:2,
    explanation:"Saat perutmu sakit dan tinja cair (diare) keluar berulang kali, tubuhmu terus-menerus kehilangan air dan zat gizi yang berharga. Ini disebut dehidrasi. Saat tubuh kekurangan air, fungsi-fungsi penting yang menjaga kita tetap hidup mulai berhenti, dan anak kecil terutama bisa tiba-tiba kehilangan nyawa. Saat diare, daripada memaksakan diri makan makanan padat, yang terbaik adalah lebih dulu mengganti air yang hilang. Dengan minum air yang aman, yang sudah direbus dan didinginkan, sedikit demi sedikit dan berkali-kali, kamu bisa menjaga tenaga dan melindungi nyawamu." },
  { id:5, topic:"Merawat luka", emoji:"🩹",
    question:"Saat kamu jatuh dan berdarah, apa yang harus dilakukan lebih dulu?",
    choices:["Menaruh tanah di atasnya","Mencucinya bersih dengan air bersih","Membiarkannya tanpa berbuat apa-apa","Menggosoknya dengan daun"],
    answerIndex:1,
    explanation:"Saat kamu jatuh dan mendapat luka yang berdarah, luka itu tertutup tanah, lumpur, dan debu dari tanah, beserta banyak kuman. Jika kamu percaya pada perkataan lama dan mengoleskan tanah, menggosoknya dengan daun kotor, atau membiarkannya begitu saja, kuman masuk jauh ke dalam luka dan berkembang biak. Lalu luka membengkak merah dan sangat sakit, dan dalam kasus terburuk lengan atau kaki bisa membusuk dan tidak bisa digerakkan. Saat kamu terluka, langkah pertama yang benar agar luka tidak menjadi parah adalah memakai air bersih dan aman untuk membilas lumpur dan kotoran dari luka dengan kuat." },
  { id:6, topic:"Makanan", emoji:"🦠",
    question:"Apa yang terjadi saat makanan membusuk (rusak)?",
    choices:["Menjadi enak","Membusuk dan membuat sakit perut","Menjadi keras","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Makanan secara alami sudah mengandung sedikit mikroba tak terlihat sejak awal. Di tempat sejuk mikroba tidak bisa aktif, tetapi jika kamu membiarkan makanan lama di tempat yang hangat dan panas, itu menjadi lingkungan yang sempurna bagi mereka, dan dalam beberapa jam mereka berkembang biak hingga jutaan, jumlah yang menakutkan. Saat mikroba berkembang biak sebanyak itu dan bentuk serta sifat makanan berubah, kita katakan makanan itu membusuk. Makanan busuk menyimpan racun kuat yang dibuat mikroba, sehingga memakannya menyebabkan sakit perut hebat, diare, dan mual, serta merusak tubuhmu." },
  { id:7, topic:"Makanan", emoji:"👃",
    question:"Apa tanda bahwa makanan sudah rusak?",
    choices:["Bau atau rasa yang aneh","Warna merah","Sesuatu yang dingin","Sesuatu yang matang dengan baik"],
    answerIndex:0,
    explanation:"Kamu bisa memakai hidung dan lidahmu sendiri untuk memeriksa apakah makanan sudah rusak dan tidak lagi aman. Jika baunya asam tidak biasa atau berbau tajam dan tidak enak, atau rasanya aneh saat kamu mencicipi sedikit, atau jika lengket dan berlendir, itu bukti bahwa kuman sudah berkembang biak banyak dan racun sudah terbentuk. Jika kamu memaksakan diri memakannya karena sayang dibuang, kamu membahayakan nyawamu karena keracunan yang berat. Jika bau atau rasanya sedikit saja mencurigakan, putuskan untuk membuangnya dan jangan pernah menelannya." },
  { id:8, topic:"Makanan", emoji:"🪰",
    question:"Apa yang harus dilakukan pada makanan yang dihinggapi lalat?",
    choices:["Memakannya begitu saja","Tidak memakan bagian yang dihinggapi lalat (membuangnya)","Memelihara lalatnya","Memandanginya saja"],
    answerIndex:1,
    explanation:"Serangga yang kita sebut lalat suka berjalan-jalan di tempat yang sangat kotor dan penuh kuman, seperti kotoran hewan, bangkai, dan tempat sampah. Karena itu, kuman penyebab penyakit yang mengerikan menempel di kaki-kaki halus dan tubuhnya. Saat lalat seperti itu hinggap di makanan kita, pada saat itu juga kuman di kakinya berpindah ke makanan. Jika kamu memakan bagian yang dihinggapinya, secara tidak langsung kamu memasukkan kuman dari kotoran dan sampah ke mulutmu, yang bisa menyebabkan penyakit berat. Walau terasa sayang, lebih aman memotong dan membuang bagian makanan yang dihinggapi lalat." },
  { id:9, topic:"Mencegah penyakit", emoji:"🦟",
    question:"Apa yang terjadi jika kamu membiarkan air tergenang lama?",
    choices:["Airnya menjadi bersih","Nyamuk berbahaya berkembang biak","Uangmu bertambah","Tidak terjadi apa-apa"],
    answerIndex:1,
    explanation:"Air lama yang menggenang di satu tempat tanpa mengalir menjadi tempat yang sempurna bagi serangga bernama nyamuk untuk bertelur. Jika kamu membiarkan ember, ban bekas, atau kaleng kosong berisi air di sekitar halaman atau rumah, dari situ lahir ratusan dan ribuan nyamuk baru yang terbang ke mana-mana. Saat nyamuk mengisap darah seseorang, ia menyuntikkan ke dalam tubuh kuman penyakit yang sangat menakutkan dan mematikan seperti malaria dan demam berdarah. Menghilangkan genangan air di sekitar rumah adalah rencana penting untuk melindungi keluargamu dari penyakit-penyakit yang mengerikan itu." },
  { id:10, topic:"Kebersihan", emoji:"✋",
    question:"Saat kuku panjang, apa yang menumpuk di dalamnya?",
    choices:["Tangan menjadi lebih kuat","Kotoran hitam dan kuman menumpuk di bawah kuku","Makanan menjadi lebih enak","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Saat kuku tumbuh panjang, lumpur dan kotoran hitam masuk berdesakan ke celah sempit antara kuku dan kulit ketika kamu bermain di tanah, membantu, atau bekerja. Kotoran yang masuk ke celah ini tidak mudah hilang hanya dengan cuci tangan biasa, dan menjadi tempat persembunyian yang sempurna bagi kuman. Dengan kuku panjang, saat kamu makan dengan tangan atau menyentuh wajah atau luka, kuman yang tersembunyi itu mudah masuk ke tubuhmu. Menjaga kuku selalu pendek adalah cara dasar untuk mencegah penyakit." },
  { id:11, topic:"Saat batuk", emoji:"🤧",
    question:"Apa yang harus kamu lakukan saat batuk atau bersin?",
    choices:["Melakukannya ke arah wajah orang","Menutup mulut dan hidung dengan tangan atau lengan baju","Berteriak keras","Tidak melakukan apa-apa"],
    answerIndex:1,
    explanation:"Saat kamu pilek atau sakit paru-paru, sekali batuk atau bersin saja melontarkan percikan air sangat kecil yang tak terlihat dari mulut dan hidungmu, sejauh beberapa meter dengan kuat. Setiap percikan bisa mengandung puluhan ribu kuman penyakit. Jika kamu batuk ke arah wajah orang, kamu menularkan penyakit secara langsung, dan jika tidak menutupinya, kuman menyebar ke udara dan semua orang di ruangan yang sama bisa jatuh sakit. Saat batuk, menutup rapat mulut dan hidung dengan lengan baju atau tangan mencegahmu menularkan penyakit kepada keluarga dan teman tersayang di sekitarmu." },
  { id:12, topic:"Kebersihan", emoji:"🗑️",
    question:"Apa yang terjadi jika kamu membiarkan sampah berserakan dekat rumah?",
    choices:["Rumah menjadi bersih","Tikus dan serangga berbahaya berkumpul dan penyakit menyebar","Sampah berubah menjadi bunga","Tidak ada masalah"],
    answerIndex:1,
    explanation:"Jika kamu membuang sisa makanan dan sampah tepat di samping rumah, baunya menarik banyak makhluk seperti tikus, lalat, dan kecoa. Makhluk-makhluk ini biasa berjalan di selokan dan tempat kotor, jadi mereka membawa banyak kuman penyebab penyakit yang menakutkan di tubuhnya. Saat mereka bertambah banyak di sekitar sampah, akhirnya mereka masuk ke dalam rumah dan mengotori makanan dan air minum yang ada di dalam. Sampah harus dibuang di tempat tertentu yang cukup jauh dari rumah, atau dikubur dalam-dalam di lubang di tanah." },
  { id:13, topic:"Gigi sehat", emoji:"🪥",
    question:"Apa alasan utama menyikat gigi?",
    choices:["Mengecat gigi menjadi putih","Mengurangi kuman gigi berlubang di mulut dan melindungi gigi","Menguatkan rahang","Mengenyangkan perut"],
    answerIndex:1,
    explanation:"Setelah makan, selalu ada sisa makanan kecil yang tertinggal di sela dan permukaan gigi. Makhluk tak terlihat yang disebut kuman gigi berlubang, yang hidup di mulut kita, sangat menyukai sisa makanan itu. Jika kamu membiarkannya, kuman gigi berlubang memakannya dan menghasilkan asam kuat yang melarutkan gigi. Karena asam ini, sedikit demi sedikit lubang terbuka di gigi, yang seharusnya bagian paling keras di tubuh, dan saat mencapai saraf menimbulkan rasa sakit yang begitu hebat sampai kamu tidak bisa tidur di malam hari. Menyikat gigi setelah makan adalah pekerjaan yang benar-benar perlu untuk menghilangkan makanan kuman dan melindungi gigimu." },
  { id:14, topic:"Mencegah luka", emoji:"👟",
    question:"Mengapa kamu memakai alas kaki saat berjalan di luar?",
    choices:["Agar kaki menjadi besar","Untuk mencegah cacing dan kuman dari tanah masuk lewat kulit kaki","Untuk latihan berlari","Agar baju tidak kotor"],
    answerIndex:1,
    explanation:"Saat kamu berjalan tanpa alas kaki di atas tanah dan lumpur, makhluk sangat kecil yang bersembunyi di tanah yang terlalu kecil untuk dilihat (larva cacing parasit) dan kuman bisa menembus kulit lembut telapak kakimu dan masuk sendiri ke dalam tubuhmu. Cacing yang masuk menetap di perutmu (usus) dan mencuri zat gizi yang kamu makan, membuatmu sangat kekurangan darah, menghentikan pertumbuhanmu, dan menguras tenagamu. Memakai alas kaki juga melindungimu dari luka parah karena menginjak pecahan kaca, batu tajam, atau duri kayu. Selalu pakai sepatu atau sandal saat keluar." },
  { id:15, topic:"Kebersihan", emoji:"👕",
    question:"Apa yang terjadi jika kamu terus memakai baju kotor?",
    choices:["Baju menjadi lebih kuat","Kulit gatal atau kamu jatuh sakit","Tubuh menjadi lebih kuat","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Jika kamu terus memakai baju yang basah oleh keringat atau kotor oleh lumpur selama berhari-hari, jamur dan kuman memakan keringat dan minyak kulit yang ada di baju dan berkembang biak luar biasa banyak di dalam seratnya. Karena baju kotor itu terus bergesekan dengan kulitmu, kulit bisa membengkak merah, sangat gatal, atau terkena penyakit dengan luka yang bernanah. Baju kotor bisa dibebaskan dari kuman dengan mencucinya bersih memakai air dan sabun lalu menjemurnya sampai kering di bawah sinar matahari (sinar ultraviolet). Selalu memakai baju bersih penting untuk melindungi pelindung kulitmu." },
  { id:16, topic:"Kebersihan", emoji:"🚿",
    question:"Apa untungnya membersihkan badan?",
    choices:["Kulit menjadi bersih dan kamu mencegah penyakit kulit","Kamu bertambah tinggi","Rambutmu rontok","Kamu menjadi lapar"],
    answerIndex:0,
    explanation:"Setiap hari, minyak tak terlihat (sebum) dan keringat keluar dari kulit manusia, dan debu serta tanah dari luar bercampur, mengotori seluruh tubuh. Jika kamu membiarkan kotoran ini berhari-hari, kuman jahat berkembang biak di permukaan kulit, dan kamu bisa terkena bisul yang parah atau penyakit menakutkan di mana kulit luka dan membusuk. Dengan rutin membersihkan seluruh tubuh secara lembut, memakai air dan sabun, dan menghilangkan minyak dan kotoran lama, kulitmu tetap sehat dan kuat, membentuk pelindung yang kuat yang mencegah penyakit masuk dari luar." },
  { id:17, topic:"Air aman", emoji:"💧",
    question:"Saat hanya ada air berlumpur, bagaimana cara meminumnya dengan aman?",
    choices:["Meminumnya begitu saja","Menyaring lumpur dengan kain atau pasir, lalu merebusnya di atas api","Hanya menjemurnya di bawah matahari lalu meminumnya","Meminumnya sedikit saja"],
    answerIndex:1,
    explanation:"Saat yang bisa kamu dapatkan hanyalah air berlumpur, meminumnya begitu saja memasukkan kuman dalam jumlah sangat banyak ke tubuhmu bersama lumpur dan menyebabkan penyakit berat. Membuatnya aman memerlukan dua kebijaksanaan. Pertama, alirkan air melewati kain bersih yang halus, atau wadah yang diisi pasir dan kerikil, untuk menyaring lumpur dan kotoran besar agar air menjadi bening. Namun, menjadi bening saja belum cukup: kuman tak terlihat masih hidup. Setelah itu, kamu harus menaruhnya di atas api dan merebusnya kuat sampai menggelegak, agar panas memusnahkan kuman dan akhirnya menjadi air minum yang aman. Dengan kebijaksanaan, kamu bisa membuat air yang menyelamatkan nyawa bahkan dari air berlumpur." },
  { id:18, topic:"Bayi", emoji:"🍼",
    question:"Apa makanan terbaik untuk bayi?",
    choices:["Susu sapi (mentah)","Susu ibu (ASI)","Air sungai","Air gula"],
    answerIndex:1,
    explanation:"Tubuh bayi yang baru lahir sangat lemah dan hampir tidak punya tenaga untuk mengalahkan kuman penyakit. Susu ibu (ASI) tidak hanya mengandung gizi yang sempurna agar bayi tumbuh, tetapi juga sejumlah besar zat pelindung khusus bernama kekebalan, yang melindunginya dari penyakit. Selain itu, ASI keluar langsung dari tubuh, jadi tidak pernah tersentuh air kotor dari luar atau kuman dari wadah: ASI adalah yang paling bersih dan paling aman di dunia. Susu mentah hewan lain, air sungai, atau air gula bisa merusak lambung dan usus bayi yang lembut dan merenggut nyawanya, jadi kamu tidak boleh memberikannya." },
  { id:19, topic:"Mencegah penyakit", emoji:"😷",
    question:"Apa yang harus dilakukan di dekat orang yang batuk parah?",
    choices:["Menjaga sedikit jarak dan memalingkan wajah saat berpapasan","Menarik napas dalam-dalam di depan orang itu","Berjabat tangan dengannya","Berdiri tepat di depannya"],
    answerIndex:0,
    explanation:"Penyakit pernapasan berat seperti TBC mengapung di udara dalam waktu lama, terbawa oleh percikan sangat kecil dan tak terlihat yang berhamburan saat orang yang sakit batuk. Jika kamu menarik napas dalam-dalam di dekatnya, atau berada dekat lama-lama, kamu menghirup kuman itu jauh ke dalam paru-parumu dan bisa tertular penyakit berat yang sama. Saat ada orang yang batuk parah, ini bukan soal bersikap jahat atau memperlakukannya berbeda; untuk melindungi diri, jagalah jarak beberapa meter, dan saat berpapasan, palingkan wajah dan embuskan napas perlahan: begitulah cara kalian berdua saling menjaga." },
  { id:20, topic:"Udara segar", emoji:"🪟",
    question:"Bagaimana menjaga udara di dalam ruangan tetap bersih?",
    choices:["Menutup rapat semua pintu dan jendela","Membuka jendela dan pintu untuk mengganti udara","Semua orang berteriak keras bersama","Tidak ada yang berubah"],
    answerIndex:1,
    explanation:"Saat banyak orang berkumpul di ruangan kecil yang tertutup, kuman dan virus yang dibawa seseorang makin lama makin menumpuk di udara, sampai udara di ruangan penuh kuman. Jika kamu berada lama di ruangan itu, semua orang menghirup udara kotor dan jatuh sakit bersama-sama (penularan beramai-ramai). Dengan membuka jendela dan pintu di dua tempat atau lebih untuk mengganti udara segar dari luar dengan udara kotor di ruangan (ventilasi), kamu bisa mengusir kuman dari udara dan melindungi kesehatan semua orang yang ada di ruangan." },
  { id:21, topic:"Pengungkit", emoji:"🪨",
    question:"Saat kamu ingin memindahkan batu berat yang terkubur di tanah menggunakan tongkat panjang, di mana kamu harus menekan paling kuat agar batu bergerak dengan tenaga sekecil mungkin?",
    choices:["Di titik tepat di sebelah batu","Di tengah tongkat","Di ujung tongkat yang paling jauh, jauh dari batu","Sama saja di mana pun kamu menekan"],
    answerIndex:2,
    explanation:"Saat memindahkan benda berat dengan tongkat, ada aturan yang disebut prinsip pengungkit: makin jauh kamu dari batu kecil yang jadi tumpuan (titik tumpu), makin kecil tenaga yang kamu perlukan untuk menekan. Jika kamu menekan dekat batu, tongkat tidak akan bergeser, tetapi jika kamu memegang ujung tongkat yang paling jauh dan menekan sambil menaruh berat badanmu, kamu bisa mengangkat batu berat dengan tenaga yang sangat kecil. Dengan mengetahui cara kerja sebuah alat seperti ini, kamu bisa melipatgandakan tenagamu sendiri dan mengerjakan pekerjaan berat dengan mudah." },
  { id:22, topic:"Pengungkit", emoji:"⚖️",
    question:"Saat kamu mengangkat beban berat dengan tongkat panjang, di mana kamu harus meletakkan batu kecil (titik tumpu) yang menyangga tongkat agar paling mudah terangkat?",
    choices:["Tepat di sebelah beban berat","Tepat di sebelah tempat kamu mengerahkan tenaga","Tepat di tengah tongkat","Lebih baik tidak meletakkan batu sama sekali"],
    answerIndex:0,
    explanation:"Saat mengangkat benda berat dengan tongkat, posisi batu kecil penyangga (titik tumpu) sangat penting. Dengan meletakkan penyangga ini tepat di sebelah beban berat, beban hanya bergerak sedikit, tetapi tenaga yang kamu perlukan untuk mengangkatnya jadi jauh lebih kecil. Sebaliknya, jika batu penyangga dekat denganmu, sekuat apa pun kamu menekan, kamu tidak akan bisa mengangkat beban. Saat ingin memindahkan benda berat, ingatlah kebijaksanaan meletakkan penyangga dekat dengan benda yang ingin dipindahkan." },
  { id:23, topic:"Menggelinding", emoji:"🪵",
    question:"Saat kamu memindahkan peti kayu berat dengan menyeretnya di atas tanah, bagaimana cara memindahkannya paling mudah dengan tenaga sekecil mungkin?",
    choices:["Meletakkan beberapa batang kayu bulat dan keras di bawah peti lalu menggelindingkannya","Menariknya sekuat tenaga apa adanya","Menyiram air ke atas peti","Membanting peti keras-keras ke lantai"],
    answerIndex:0,
    explanation:"Saat kamu menyeret benda berat langsung di atas tanah, bekerja kuat sebuah rem bernama gesekan, yang timbul di tempat benda bergesekan dengan tanah, sehingga butuh tenaga yang sangat besar untuk memindahkannya. Tetapi jika kamu meletakkan batang kayu bulat dan keras di bawah peti, gerakannya berubah dari menyeret menjadi kayu menggelinding. Menggelinding punya rem berpuluh kali lebih kecil daripada menyeret, sehingga satu orang pun bisa memindahkan beban berat dengan mulus. Saat beban maju, kamu ambil kayu yang keluar di belakang dan meletakkannya lagi di depan, kebijaksanaan yang dipakai manusia sejak zaman dulu." },
  { id:24, topic:"Bidang miring", emoji:"🛝",
    question:"Saat kamu ingin menaikkan beban berat ke atas panggung tinggi setinggi dada orang dewasa, cara memindahkan yang mana yang paling sedikit membebani tubuhmu?",
    choices:["Berdiri di depan panggung dan mengangkatnya lurus ke atas sekuat tenaga","Menyandarkan papan panjang miring ke panggung untuk membuat tanjakan, lalu mendorongnya ke atas","Melempar beban ke panggung dari jauh","Memangkas tinggi panggung agar lebih rendah"],
    answerIndex:1,
    explanation:"Jika kamu mencoba mengangkat beban berat lurus ke atas, kamu menghadang langsung gaya yang menarik benda ke bumi (gravitasi), sehingga harus menyangga semuanya hanya dengan ototmu, yang membuat punggung dan lenganmu cedera. Di sini, jika kamu menyandarkan papan panjang miring ke panggung untuk membuat tanjakan (bidang miring), papan itu jadi menyangga sebagian besar berat beban. Saat menaiki tanjakan, jarak yang kamu tempuh memang jadi lebih panjang, tetapi tenaga untuk mendorong beban bisa dikurangi hingga kurang dari setengahnya. Saat membawa barang ke tempat tinggi, selalu carilah cara membuat tanjakan." },
  { id:25, topic:"Katrol", emoji:"🪣",
    question:"Saat kamu menarik ember berat berisi air dari sumur dalam dengan tali, apa yang jadi lebih mudah jika kamu memasang roda bulat yang berputar (katrol) pada palang di atas sumur dan menyangkutkan tali padanya?",
    choices:["Berat air menjadi setengahnya, lebih ringan","Jumlah air bertambah dengan sendirinya","Kamu bisa menaikkan air hanya dengan menarik tali ke bawah","Tali tidak akan pernah putus"],
    answerIndex:2,
    explanation:"Saat kamu menyangkutkan tali pada roda bulat di atas sumur (katrol tetap), sebenarnya berat air sendiri tidak menjadi lebih ringan. Tetapi yang hebat dari alat ini adalah ia mengubah arah kamu mengerahkan tenaga. Jika kamu mencoba menaikkan tali lurus ke atas, kamu harus mengangkatnya hanya dengan tenaga lengan dan punggungmu; tetapi jika kamu menyangkutkan tali pada roda bulat lalu menarik ke bawah, kamu bisa menaruh seluruh berat tubuhmu pada tali. Bisa memakai berat tubuhmu sendiri untuk menarik air berat dengan mudah dan aman, itulah kebijaksanaan roda bulat ini." },
  { id:26, topic:"Roda dan poros", emoji:"🔄",
    question:"Saat kamu ingin memutar sekrup yang sama sekali tidak mau berputar, atau mesin penggulung sumur yang berat, bagaimana cara memutarnya paling mudah?",
    choices:["Memutarnya dengan batang pendek dan tipis","Membuat bagian pegangan jadi besar dan panjang, lalu memutar itu","Memutarnya hanya dengan ujung jari, tanpa alat","Memukul sekrup keras-keras dengan palu"],
    answerIndex:1,
    explanation:"Saat kamu ingin memutar poros yang ada di tengah, jika kamu memasang pegangan bulat besar atau gagang panjang pada poros itu, kamu bisa menghasilkan gaya putar yang besar dengan sedikit tenaga. Ini disebut prinsip roda dan poros. Kamu tidak bisa menggerakkan bagian tipis dengan memutarnya langsung pakai jari, tetapi saat kamu memutar pegangan besar di luar, jarak yang ditempuh tanganmu jadi lebih panjang, sementara gaya pada poros jadi berkali-kali lebih kuat. Mesin penggulung tali sumur, kenop pintu di rumah, sekrup pada alat-alat; semua benda yang berputar di sekitarmu memakai kebijaksanaan ini." },
  { id:27, topic:"Titik berat", emoji:"🏺",
    question:"Ada orang yang berjalan dengan cekatan sambil membawa kendi air berat atau kayu bakar di atas kepala. Mengapa mereka bisa berjalan jauh tanpa melukai leher atau punggung?",
    choices:["Karena mereka berjalan sambil membungkukkan tubuh jauh ke depan atau belakang","Karena mereka menjaga punggung lurus sempurna dan menaruh pusat beban (titik beratnya) tepat di atas tulang mereka","Karena mereka terus mengguncang beban keras-keras di atas kepala","Karena setiap orang lahir dengan tulang leher lebih tebal dari yang lain"],
    answerIndex:1,
    explanation:"Saat kamu membawa beban berat di tangan, bebannya hanya jatuh pada satu sisi tubuh dan ototmu cepat lelah. Tetapi jika kamu meluruskan punggung sempurna dan menaruh beban tepat di atas kepala, berat pusat beban (titik beratnya) turun lurus melewati pilar tulang, dari kepala ke leher lalu ke tulang punggung, dan keluar ke tanah. Karena tulang yang kokoh, bukan otot, yang menyangga berat, kamu bisa membawanya dengan aman menempuh jarak jauh tanpa membuang tenaga otot, asalkan kamu menjaga keseimbangan. Menjaga benda dekat dengan poros tengah tubuhmu adalah kebijaksanaan penting agar tidak cedera." },
  { id:28, topic:"Tekanan", emoji:"🦶",
    question:"Saat kamu berjalan di jalan berlumpur yang, setelah hujan, jadi lumpur dalam dan kaki terbenam, bagaimana cara berjalan lebih mudah tanpa terbenam?",
    choices:["Berjalan berjinjit, membuat telapak kaki sekecil mungkin","Mengikatkan papan kayu datar dan besar ke telapak kaki, lalu berjalan","Cukup berteriak keras dan menyeberang sambil berlari","Memikul banyak barang agar tubuh lebih berat"],
    answerIndex:1,
    explanation:"Berat yang menekan tanah makin terpusat kuat di satu titik dan terbenam makin dalam, seperti jarum, makin kecil luas permukaan yang menyentuhnya. Ini disebut tekanan. Berjinjit membuat luas permukaan jadi kecil, sehingga kamu terbenam makin dalam. Sebaliknya, jika kamu mengikatkan papan kayu datar dan besar ke telapak kaki, berat tubuhmu tersebar di luas permukaan yang lebar, sehingga gaya yang menekan tanah ke bawah melemah dan kamu bisa berjalan di atas lumpur tanpa terbenam. Membuat dasar bangunan berat jadi lebar dan datar juga kebijaksanaan yang sama untuk menyebarkan tekanan." },
  { id:29, topic:"Gerobak", emoji:"🛒",
    question:"Saat kamu ingin memuat banyak barang berat di gerobak beroda dua lalu menariknya, di mana kamu harus menaruh benda berat agar paling ringan dan mudah ditarik?",
    choices:["Tepat di sebelah tanganmu, dekat pegangan","Di ujung paling belakang gerobak","Tepat di atas poros roda","Sama saja di mana pun kamu memuatnya"],
    answerIndex:2,
    explanation:"Saat kamu menarik gerobak, berat di tanganmu berubah drastis tergantung di mana kamu menaruh beban. Jika kamu memuat barang berat dekat tanganmu, kamu jadi berlari sambil mengangkat berat beban langsung dengan lengan, dan cepat lelah. Jika terlalu ke belakang, gerobak terjungkal ke belakang, yang berbahaya. Jawaban yang benar adalah tepat di atas poros roda. Jika kamu menaruh benda berat di sini, roda yang kokoh dan tanah menyangga seluruh berat, sehingga hampir tidak ada berat yang jatuh ke tanganmu. Karena kamu hanya perlu tenaga untuk menarik ke depan, kamu bisa mengangkut beban besar dengan sangat mudah." },
  { id:30, topic:"Mata pisau", emoji:"🔪",
    question:"Saat kamu mengasah ujung golok pembelah kayu bakar, atau pisau dapur pemotong makanan, dengan menggosoknya pada batu (batu asah), mengapa jadi lebih tajam memotong?",
    choices:["Karena ujung mata pisau jadi makin tipis dan halus, dan tenaga terpusat di satu titik","Karena mata pisau jadi panas dan melelehkan makanan","Karena mata pisau jadi lebih berat","Karena mata pisau jadi tumpul membulat"],
    answerIndex:0,
    explanation:"Sesuatu bisa terpotong oleh mata pisau karena tenaga yang dikerahkan seseorang terpusat di titik yang sangat sempit pada ujung mata pisau dan menembus benda. Saat mata pisau jadi tua dan membulat, tenaga tersebar di luas permukaan yang lebar, sehingga sekuat apa pun kamu menekan, ia tidak memotong. Mengasah mata pisau adalah pekerjaan menggerus ujung yang membulat agar setipis dan sehalus mungkin. Begitu ujungnya halus, tenaga kecil pun menciptakan tekanan yang sangat besar di titik itu, sehingga kamu bisa membelah kayu keras atau makanan dengan sentuhan ringan. Merawat alat-alatmu adalah dasar untuk menghemat tenagamu." },
  { id:31, topic:"Gesekan", emoji:"👟",
    question:"Saat kamu berjalan di tanjakan atau di atas batu basah, mana yang tidak mudah tergelincir dan lebih aman: sepatu yang licin mulus, atau sepatu dengan alur dalam bergerigi di solnya?",
    choices:["Sepatu datar yang licin mulus","Sepatu dengan alur dalam bergerigi di solnya","Sama saja yang mana pun kamu pakai","Lebih tidak licin tanpa sepatu sama sekali"],
    answerIndex:1,
    explanation:"Saat sol sepatu bergesekan dengan tanah, di situ bekerja rem bernama gesekan yang mencegahmu tergelincir. Jika sol licin mulus, tidak ada rem yang bekerja antara sol dan tanah, dan kamu mudah tergelincir lalu jatuh, terutama di tempat ada air atau lumpur. Jika sol punya alur dalam bergerigi, alur itu mencengkeram kuat ketidakrataan tanah dan menciptakan rem yang kuat. Tergelincir dan jatuh bisa menyebabkan cedera parah, tetapi dengan mengetahui cara kerja gesekan, memilih sepatu beralur di tempat licin atau menapakkan seluruh telapak kaki kuat ke tanah, kamu bisa bertindak dengan aman." },
  { id:32, topic:"Mengapung", emoji:"⛵",
    question:"Kerikil kecil tenggelam di air, tetapi kapal kayu yang ribuan kali lebih berat dan besar bisa mengapung di air. Mengapa?",
    choices:["Karena kapal berbentuk seperti mangkuk dan menyimpan banyak udara dan air di dalamnya","Karena kapal terkena banyak angin","Karena ada batu ajaib yang dilumurkan di dasarnya","Karena kapal terbuat dari minyak yang lebih ringan dari air"],
    answerIndex:0,
    explanation:"Pada benda di dalam air bekerja gaya misterius bernama gaya apung, yang mendorongnya ke atas sebanyak air yang ia singkirkan. Kerikil padat di dalamnya dan berat, sehingga kerikil lebih berat daripada air yang ia singkirkan, dan tenggelam. Tetapi kapal besar berbentuk seperti mangkuk, dan di dalamnya menyimpan banyak udara. Dilihat secara keseluruhan, ia jadi sangat ringan untuk ukurannya, sehingga gaya air yang mendorong dari bawah jadi lebih kuat, dan kapal besar pun bisa mengapung di air tanpa terbalik." },
  { id:33, topic:"Segitiga", emoji:"🔺",
    question:"Saat kamu membangun rumah atau jembatan dari kayu atau besi, mengapa menyusun rangka dalam bentuk segitiga membuat bangunan sangat kokoh dan sulit rusak?",
    choices:["Karena butuh lebih banyak bahan daripada segi empat","Karena segitiga punya sifat bahwa bentuknya tidak pernah berubah, bahkan saat gaya kuat menekan dari atas","Karena membuat segitiga membuat angin lebih mudah lewat","Karena itu bentuk kuno yang dipakai sebagai jimat dari para dewa"],
    answerIndex:1,
    explanation:"Bangunan dari tiang yang disusun hanya dalam bentuk segi empat mudah runtuh, dengan sambungannya melengkung lemas, saat gaya kuat atau guncangan gempa menekan dari atas atau samping. Tetapi jika kamu menambah satu batang miring di dalam segi empat itu untuk membuat segitiga (struktur rangka batang), maka dari arah mana pun gaya datang, batang-batang saling menarik dan mendorong sehingga bentuknya sama sekali tidak berubah. Jika kamu melihat jembatan besar di dunia, atau bagian bawah atap bangunan, segitiga ini selalu tersusun rapi di sana. Inilah kebijaksanaan bangunan yang luar biasa: meski dengan sedikit bahan, hanya dengan memikirkan bentuk, kamu bisa membuat sesuatu yang berkali-kali lebih kokoh." },
  { id:34, topic:"Inersia", emoji:"🐎",
    question:"Saat kuda atau gerobak yang sedang berlari mengerem mendadak dan berhenti seketika, apa yang terjadi pada barang dan orang yang ada di atasnya?",
    choices:["Terjungkal ke belakang apa adanya","Terlempar ke depan dengan kuat","Melompat lurus ke atas di tempat","Tidak terjadi apa-apa; ikut berhenti seketika"],
    answerIndex:1,
    explanation:"Di alam semesta ada gaya misterius bernama inersia (kelembaman): benda yang bergerak berusaha terus bergerak pada kecepatan yang sama. Meski kuda atau gerobak berhenti mendadak, orang dan barang di atasnya masih berusaha terus maju. Karena itu, jika kamu tidak memancangkan kaki kuat-kuat atau tidak mengikat beban dengan tali, kamu terlempar ke depan dengan kuat dan terluka parah. Saat kamu menghentikan sesuatu yang bergerak, atau saat kamu naik kendaraan cepat, kamu harus ingat bahwa gaya yang berusaha melemparkan benda ke depan ini selalu bekerja, dan bersiap demi keselamatanmu." },
  { id:35, topic:"Gunting", emoji:"✂️",
    question:"Saat kamu ingin memotong ranting keras atau kain tebal dengan gunting, di bagian mata gunting yang mana kamu harus menjepitnya agar paling mudah memotong dengan tenaga sekecil mungkin?",
    choices:["Di ujung paling depan mata gunting","Di pangkal mata gunting (paling dekat sekrup atau engsel)","Di tengah mata gunting","Tenaga yang dibutuhkan sama saja di mana pun kamu memotong"],
    answerIndex:1,
    explanation:"Gunting juga alat yang sangat praktis yang memakai prinsip pengungkit yang sudah kita pelajari. Sekrup tempat dua bilah bersilangan dan terkunci menjadi tumpuan (titik tumpu). Makin dekat ke sekrup tumpuan ini kamu memotong, makin berkali-kali kuat gaya yang tanganmu yang menggenggam teruskan ke bilah. Karena itu, dengan benda keras yang tidak terpotong, mencoba memotong di ujung gunting hanya membuat tanganmu sakit, tetapi jika kamu menjepitnya dalam-dalam di pangkal bilah, kamu bisa memotongnya putus dengan tenaga yang sangat kecil. Kenali sifat alat-alatmu dan pakai bagian yang paling efisien." },
  { id:36, topic:"Gravitasi", emoji:"🍎",
    question:"Mengapa antara menjatuhkan kerikil kecil ke kaki dari setinggi lutut dan menjatuhkannya dari atas atap rumah, yang jatuh dari atap menyebabkan luka lebih parah?",
    choices:["Karena batu jadi lebih dingin di atas atap","Karena gravitasi, gaya yang menarik benda ke bumi, membuat batu makin cepat seiring makin panjang jatuhnya, sehingga benturan saat menumbuk lebih kuat","Karena batu di tempat tinggi jadi lebih besar ukurannya","Karena udara mendorong batu ke bawah"],
    answerIndex:1,
    explanation:"Segala sesuatu di bumi terus-menerus ditarik oleh gaya bernama gravitasi, ditarik ke arah tanah. Untuk benda di tempat tinggi, makin panjang jatuhnya, makin terus ditarik gravitasi dan makin cepat lajunya (ia berakselerasi). Benda yang sudah cepat menciptakan daya hancur yang sangat besar (energi) pada saat menumbuk tanah atau tubuhmu. Dari setinggi lutut hanya terasa sakit, tetapi sesuatu yang jatuh dari atap tinggi atau tebing, sekecil apa pun batu atau alatnya, menjadi senjata yang bisa merenggut nyawa seseorang. Saat bekerja dekat tempat tinggi, kamu harus memastikan tidak ada orang di bawah dan berhati-hati sekali agar tidak menjatuhkan apa pun." },
  { id:37, topic:"Keseimbangan", emoji:"⚖️",
    question:"Saat kamu memikul di bahu sebatang tongkat panjang (pikulan) dengan dua kendi air berat tergantung di depan dan belakang, bagaimana cara berjalan dengan mudah tanpa bahu sakit?",
    choices:["Membuat beban depan sangat berat dan beban belakang ringan","Membuat beban depan dan belakang sama persis beratnya, dan menaruh tepat tengah tongkat di bahu","Tidak memikul tongkat di bahu; membawanya hanya dengan tangan","Menjatuhkan beban ke tanah bergantian sambil berlari"],
    answerIndex:1,
    explanation:"Saat kamu memikul beban yang tergantung di kedua sisi tongkat panjang, jika berat depan dan belakang tidak seimbang, tongkat miring ke satu sisi dan kamu harus berjuang menahannya dengan tangan. Ini cepat melelahkan bukan hanya bahu, tetapi juga lengan dan punggung. Jawaban yang benar adalah membuat beban depan dan belakang seimbang persis sama. Dengan begitu berat menekan rata tepat di atas bahu lewat pikulan, dan kamu bisa memikul beban berat hanya dengan berjalan, tanpa memakai otot tambahan untuk melawan kemiringan. Jika satu beban terpaksa lebih ringan, atur keseimbangan dengan menggeser tali sisi yang ringan ke ujung tongkat." },
  { id:38, topic:"Hambatan udara", emoji:"🪂",
    question:"Kamu punya dua lembar kertas yang sama ukuran dan sama berat. Satu dibiarkan sebagai lembaran datar, satu lagi diremas dengan tangan jadi bola padat. Saat kamu menjatuhkannya bersamaan dari tempat tinggi, mana yang lebih dulu sampai ke tanah?",
    choices:["Lembaran datar apa adanya","Kertas yang diremas jadi bola padat","Keduanya sampai persis bersamaan","Berubah-ubah tiap kali tergantung angin"],
    answerIndex:1,
    explanation:"Walau benda sama beratnya, saat jatuh melewati udara bekerja rem bernama hambatan udara, dengan udara menghalangi. Lembaran kertas datar punya luas permukaan yang lebar, sehingga menangkap banyak udara di bawahnya dan jatuh pelan saja, seperti parasut. Tetapi kertas yang diremas jadi bola kecil menyentuh udara di luas permukaan yang sangat sempit, sehingga hampir tidak menerima rem dan jatuh cepat, ditarik lurus ke bawah oleh gravitasi. Kincir angin berputar terkena angin, atau payung hampir terbang di hari berangin kencang, juga berkaitan dengan gaya rem udara ini." },
  { id:39, topic:"Elastisitas", emoji:"🏹",
    question:"Saat kamu menekuk sekuat tenaga bambu yang keras dan kokoh, atau ranting pohon yang lentur, lalu melepaskannya tiba-tiba, ia kembali ke bentuk semula dengan kuat. Untuk apa kamu bisa memakai sifat ini (kelenturan) agar jadi alat berguna dalam kehidupan sehari-hari?",
    choices:["Lemari es agar makanan tidak membusuk","Busur dan anak panah untuk melesatkan anak panah ke mangsa yang jauh, atau jerat yang melontarkan benda berat","Saringan untuk membersihkan air","Alat untuk mewarnai pakaian jadi putih"],
    answerIndex:1,
    explanation:"Karet dan pegas, juga bambu dan ranting pohon, punya sifat misterius bernama kelenturan (elastisitas): saat kamu memberi gaya bentuknya menekuk, dan saat kamu melepaskan ia berusaha kembali ke bentuk semula dengan kecepatan tinggi. Selagi kamu menahannya tertekuk dengan tangan, tenaga yang dikerahkan seseorang tersimpan sejenak di dalam alat itu sebagai energi. Pada saat kamu melepaskan, tenaga tersimpan itu dilepaskan sekaligus, sehingga kamu bisa melesatkan anak panah berkali-kali lebih jauh, atau menjalankan jerat, dibanding melempar hanya dengan lengan. Dengan memanfaatkan gaya yang dimiliki tumbuhan alam ini, manusia membuat alat untuk berburu dan kehidupan sehari-hari sejak zaman dulu." },
  { id:40, topic:"Pelumas", emoji:"🛢️",
    question:"Roda gerobak, atau engsel pintu, mulai berbunyi mencicit menyebalkan dan jadi berat setiap kali kamu menggerakkannya. Jika kamu meneteskan beberapa tetes minyak di sini, mengapa jadi bergerak ringan kembali?",
    choices:["Karena minyak melelehkan besi dan membuatnya ringan","Karena minyak mengeras dan jadi lem","Karena minyak masuk ke celah antara logam dan logam dan mengurangi drastis gaya rem gesekan","Karena bau minyak mengusir serangga"],
    answerIndex:2,
    explanation:"Saat mesin atau alat bergerak, ada tempat di mana logam bergesekan kuat dan langsung dengan logam. Di situ bekerja rem yang sangat kuat bernama gesekan dan, jika dibiarkan, ia terkikis dan rusak, atau butuh tenaga yang sangat besar untuk menggerakkannya. Saat kamu memberi minyak, terbentuk lapisan tipis minyak di celah kecil logam dan mencegahnya bergesekan langsung. Karena gaya rem hilang seketika, alat bergerak dengan kemulusan yang mengagumkan dan sedikit tenaga. Hanya dengan memberi sedikit minyak goreng atau minyak nabati pada alat, alat itu jadi lebih awet dan sangat mengurangi pengurasan tenaga manusia." }
];
